### ISSUE TITLE
Flaky tests: EnsureCreateIdentityTokenSigningCertificate_CreatesACertificate_WhenThereAreNoHttpsCertificates et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#3354] opened 2018-07-23 17:52 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=512272&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) occasionally with the following error:
```
Assert.Equal() Failure
Expected: Succeeded
Actual:   ErrorSavingTheCertificateIntoTheCurrentUserPersonalStore
   at Microsoft.AspNetCore.Certificates.Generation.Tests.CertificateManagerTests.EnsureCreateIdentityTokenSigningCertificate_CreatesACertificate_WhenThereAreNoHttpsCertificates() in /_/test/Microsoft.Extensions.Internal.Test/CertificateManagerTests.cs:line 220
```
Possibly this is an agent state issue since we only have one High-Sierra agent and no code appears to have changed before the failures started.

**Comment by Eilon** [comment] 2018-07-23 20:52
@javiercn can you please take a look at this flaky test as a high priority?

**Comment by javiercn** [comment] 2018-07-23 22:00
Is there more information than the failed test?
Can we reboot the agent and validate if it fixes the issue?
In the past people login through SSH has caused these tests to start failing on the agent.

**Comment by ryanbrandenburg** [comment] 2018-07-23 23:20
You're correct that rebooting the agent has worked in the past. We tried to reboot it from the TC UI but it seemed to hang. I did it manually and we'll see what happens the next time it gets there.

**Comment by Eilon** [comment] 2018-07-24 00:10
Would it be possible (or make sense) to add more diagnostic information to the test to help find out the cause in a future failure?

**Comment by Eilon** [comment] 2018-10-01 20:50
Might be best to close this for now because it's so old...

**Closed** 2018-10-01 21:38 UTC
Labels: PRI: 1 - Required, flaky, repo:Common
