### ISSUE TITLE
Can't get ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by Boombasteg** [aspnet/Home#2310] opened 2017-12-18 15:31 UTC
I set ASPNETCORE_ENVIRONMENT via Environment Variables or in code
`Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "dev");`

But when trying to read it:
`var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");`
I'm getting null.

Has anyone encountered a similar one?
Thanx.

**Comment by Tratcher** [comment] 2017-12-18 16:49
Context? Are these back-to-back calls?

**Comment by Eilon** [comment] 2018-01-09 16:33
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2018-01-09 16:33 UTC

**Comment by Boombasteg** [comment] 2018-01-10 07:20
Problem was in VS. It should be restarted after changing "ASPNETCORE_ENVIRONMENT".
