### ISSUE TITLE
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0...'

### ISSUE THREAD

**Issue by pingvinius** [aspnet/Home#2753] opened 2018-01-09 04:59 UTC
_From @pingvinius on January 7, 2018 18:43_

Hello,

I found a strange issue when using CodePagesEncodingProvider of System.Text.Encoding.CodePages assembly.
I did not test other encoding but when I try to return a file in aspnet core mvc application in the following encoding CodePagesEncodingProvider.Instance.GetEncoding(866), the application throws an exception:

> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> 
> File name: 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>    at aspnet_codepage_test.Controllers.HomeController.GetFile()
>    at lambda_method(Closure , Object , Object[] )
>    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
> 

A code is extremely simple:
```
public IActionResult GetFile()
{
       var encoding = CodePagesEncodingProvider.Instance.GetEncoding(866);
       var bytes = encoding.GetBytes("Cтрока");

       return File(new MemoryStream(bytes), "text/plain", "111.txt");
}
```
As a initial string I use Russian word.

The interesting fact is it reproduces only in a production settings, so when I try to run it from a working directory, it works perfectly. Once I publish and run "dotnet ./project.dll", it fails.

I created a sample application to give it to you, so you can reproduce an issue. I also tried to run this application in a docker container, it has the same result.
[aspnet-codepage-test.zip](https://github.com/dotnet/corefx/files/1610082/aspnet-codepage-test.zip)

I have the following environment:
ubuntu 16.04
dotnet version: 2.0.0

Please find the steps to reproduce below:
- unzip an archive
- go to an extracted folder
- run: dotnet restore
- run: dotnet build -c Release
- run: dotnet publish -c Release
- run: dotnet ./bin/Release/netcoreapp2.0/publish/aspnet-codepage-test.dll 
- go to a browser and open http://localhost:5000/
- find a menu item "Get file" at the top of the page and click it

Please let me know if I missed something.
Thanks in advance.

_Copied from original issue: dotnet/corefx#26211_

**Comment by pingvinius** [comment] 2018-01-09 04:59
_From @karelz on January 7, 2018 21:11_

Can you reproduce it in a Console application as well (outside of MVC)?
Are you running on .NET Core 2.0 or on .NET Framework 4.6.1+?

**Comment by pingvinius** [comment] 2018-01-09 04:59
I've forgotten to tell, I also tried to reproduce this issue on a console application, both on my local pc and in a docker container, but it works as expected.
I am running .NET Core 2.0 (netcoreapp2.0) framework.

Also I tried to add the line below to project file:
`<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>`
It did not help at all.

Please correct me, if I'm wrong, I add to the project System.Text.Encoding.CodePages assembly version 4.4.0, but it looks for version 4.1.0.0. For me, it seems strange.

**Comment by pingvinius** [comment] 2018-01-09 04:59
_From @tarekgh on January 8, 2018 18:13_

This is a duplicate of https://github.com/aspnet/Mvc/issues/6983. please follow the resolution steps there.

**Comment by pingvinius** [comment] 2018-01-09 04:59
I already tried both solutions, they are not helpful, just test them with a sample project and you will see that the issue is still reproducible. Please re-open the issue.

**Comment by pingvinius** [comment] 2018-01-09 04:59
_From @tarekgh on January 8, 2018 19:4_

did you try 

```
install the runtime store. If you are trying to deploy to a linux machine, you will need to install the dotnet-hosting-2.0.0 package
```

This is aspnet publishing issue. so if you think this is a different issue, please move this issue to aspnet repo.

**Comment by pingvinius** [comment] 2018-01-10 17:59
Is there anybody here? The issue is still not resolved.

**Comment by tarekgh** [comment] 2018-01-10 18:08
maybe better to move it to aspnet/Mvc repo instead. 

I am CC'ing @JunTaoLuo who investigated the other related issue before so he may help.

**Comment by Eilon** [comment] 2018-01-11 21:47
@JunTaoLuo any ideas on this? Or what the root cause might be?

**Comment by JunTaoLuo** [comment] 2018-01-12 00:17
Is there any reason the `System.Text.Encoding.CodePages` is marked with `PrivateAssets="All"`. The exception went away when I removed it.

**Comment by JunTaoLuo** [comment] 2018-01-12 00:24
It looks like when the package reference is marked as PrivateAssets="All", it is not included in the published .deps.json files. I assume this is why the .dll wasn't able to be loaded at runtime.

**Comment by pingvinius** [comment] 2018-01-12 20:45
Thanks! It helped me! Without PrivateAssets="All" it works as expected.
Seems I used Ctrl+C,Ctrl+V that's why this attribute is present.

Thanks a lot! 
I think that the issue should be closed.

**Closed** 2018-01-12 20:45 UTC

**Comment by TeaBeard** [comment] 2019-08-01 20:08
I just got this error when attempting to run a web application on .net core v3 that has nuget packages with preview 7 version but did not have preview 7 on my box. The box had preview 6 installed on it. when i installed preview 7 and restarted, the errors abated.
