### ISSUE TITLE
MissingManifestResourceException from included assembly although present

### ISSUE THREAD

**Issue by gimlichael** [aspnet/Home#1534] opened 2016-06-02 15:37 UTC
I have an `ASP.NET Core Web Application (.NET Framework)` that is using a number of assemblies.
For my current issue, our web application references a `Class Library (.NET Core)` that have several .resx files. Each of these files have there associated `*.Designer.cs`.

When trying to access the values in our Razor view, we are met with this exception:

```
System.Reflection.TargetInvocationException was unhandled
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
  InnerException: 
       HResult=-2146233038
       Message=Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Cosmos.ViewModels.Default.resources" was correctly embedded or linked into assembly "Cosmos.ViewModels" at compile time, or that all the satellite assemblies required are loadable and fully signed.
       Source=mscorlib
       StackTrace:
            at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
            at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
            at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
            at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
            at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
            at Cosmos.ViewModels.Resources.da.Default.get_Head_Title() in C:\Cosmos\src\Cosmos.ViewModels\Resources\da\Default.Designer.cs:line 67
       InnerException: 

```

I have tried following the guidelines from this StackOverflow issue, [http://stackoverflow.com/questions/37360068/localization-in-separate-project-asp-net-core-mvc](http://stackoverflow.com/questions/37360068/localization-in-separate-project-asp-net-core-mvc), but i don't know how to configure the embed section, as there "perse" is no file to embed?

UPDATE: using DotPeek from JetBrains, I can see that embedded resource files are present.
![2016-06-03_1051](https://cloud.githubusercontent.com/assets/8550919/15773753/17776630-2979-11e6-9dc8-36e2c61ce7c4.png)

The default .Designer.cs has this implementation:

```
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("**Cosmos.ViewModels.Default**", typeof(Default).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
```

Where, if i manually change the **Cosmos.ViewModels.Default** to **Cosmos.ViewModels.Resources.da.Default**, it works. It's like the auto-generated code does not follow the structure of the solution.

With these new finding, I don' think this is related to the aspnet location .. it think it should be in the core cli or whatever team controls the auto-generation tool for the Designer.cs file.

This worked fine with RC1, with the twist, that the resources was in the same project; not a seperate assembly.

Also, this message `Make sure "Cosmos.ViewModels.Default.resources" was correctly embedded or linked into assembly "Cosmos.ViewModels" at compile time`, makes no sense to me, as we only have the `Default.resx` file and `Default.Designer.cs` file (maybe consider rephrasing?).

**Comment by StephenLujan** [comment] 2016-08-04 19:54
In my case I've observed that it used to be added to the assembly named after its full namespace, but it now appears to follow the pattern AssemblyName.ResourceName

**Comment by jaskiewicz-de** [comment] 2016-11-16 01:16
Today I got exactly the same problem using dotnet --version 1.0.0-preview2-1-003155 on Ubuntu 14.04.
ILSpy shows me, that the string tables are embedded but with wrong names not matching the resx designer namespace and class name. Also the naming of the resx satellite assemblies and o/c the embedded string tables ignore the outputName setting:

"compilationOptions": {
    "outputName": "DDDN.Hr.Client.Web",
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  }

e.g. for the same project/files:
resx designer class FullName is DDDN.Hr.Client.Web.Resources.ResAbout

embedded string table name on Ubuntu is hr.Resources.ResAbout.resources
embedded string table name on Windows is DDDN.Hr.Client.Web.Resources.ResAbout.resources
satellite assembly name on Ubuntu is hr.resources.dll
satellite assembly name on Wwindows is DDDN.Hr.Client.Web.resources.dll

So this problem still hasn't been fixed in the 1.0.0-preview2-1-003155???

**Comment by jaskiewicz-de** [comment] 2016-11-17 12:31
The problem is that the "outputName": "DDDN.Hr.Client.Web" setting is ignored when generating the embedded resource names of the string tables. In my case with the outputName setting, dotnet CLI is compiling my app not to hr.dll but correctly to DDDN.Hr.Client.Web.dll, but misses to also rename the resource names of the string tables.

My workaround for, under Windows/VS2015 generated resx designer classes:

Assuming the default namespace DDDN.Hr.Client.Web and that the resource files are in the ~Resources folder and the resource file name is ResAbout.resx and that dotnet CLI is compiling the application to hr.dll

In the ResAbout.Designer.cs file, change the FullName of the resource:

global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDDN.Hr.Client.Web.Resources.ResAbout", typeof(ResAbout).GetTypeInfo().Assembly);

to

global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hr.Resources.ResAbout", typeof(ResAbout).GetTypeInfo().Assembly);

after that you don't get the exception any more:
Message=Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "DDDN.Hr.Client.Web.Resources.ResAbout.resources" was correctly embedded or linked into assembly "hr" at compile time, or that all the satellite assemblies required are loadable and fully signed.

**Comment by aspnet-hello** [comment] 2017-12-30 23:57
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Closed** 2017-12-30 23:57 UTC
