### ISSUE TITLE
appsettings.json intellisense support missing

### ISSUE THREAD

**Issue by Legends** [aspnet/Home#2926] opened 2018-03-06 13:20 UTC
I am using VS2017 and created an ASP.NET Core 2.0 project, but I have no intellisense support in the appsettings.json file?

Any planned support for this?

**Comment by Tratcher** [comment] 2018-03-06 16:16
What kind of settings did you have in mind? Intellisense is challenging in this context as it's a free-form structure, the developer can bind any section to any component. The ASP.NET components read almost no data direct from appsettings by default (Kestrel is the only one I can think of and that's new in 2.1).

@shirhatti @glennc

**Comment by natemcmaster** [comment] 2018-03-06 17:31
Duplicate of https://github.com/aspnet/Home/issues/2867

**Closed** 2018-03-06 18:29 UTC

**Comment by Legends** [comment] 2018-03-06 18:44
Something like this:

```
{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "Jwt": {
    "Key": "veryVerySecretKey",
    "Issuer": "http://localhost:63939/"
  }
}

```
