### ISSUE TITLE
Allow collections to be replaced, when defined in IConfiguration

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2385] opened 2018-01-01 20:11 UTC
_From @TsengSR on Thursday, November 9, 2017 2:45:00 AM_

I am currently running into an issue with the way the options are populated/bound to a model. 

I got an options class with a collection/list which contains a few default values. I want this to remain there, when the options aren't used and be replaced when they are defined in appsettings.json.

```
    public class SampleOptions
    {
        public List<string> Names1 { get; set; } = new List<string>
        {
            "name1", "name2", "name3"
        };
        public List<string> Names2 { get; set; } = new List<string>
        {
            "name1", "name2", "name3"
        };
    }
```

and a appsettings.json

```
{
  "SampleOptions"; {
    "Names1": ["name4", "name5", "name6"]
  }
}
```

so that the `Names2` list remains as it is and `Names1` gets replaced with the new values.

However, the `Names1` will now have 6 values. 3 old and the 3 newly added ones.

_Copied from original issue: aspnet/Options#241_

**Comment by ajcvickers** [comment] 2018-03-10 01:12
Duplicate of https://github.com/aspnet/Configuration/issues/694

**Closed by ajcvickers** 2018-03-10 01:12 UTC
Labels: repo:Options

**Comment by MAGALY956** [comment] 2018-03-24 23:33
http://newlifestylechoices.com/3-steps-to-making-money-from-surveys/
Cindy M Torres @Mob4all

**Comment by MAGALY956** [comment] 2018-03-25 02:18
http://newlifestylechoices.com/3-steps-to-making-money-from-surveys/
