### ISSUE TITLE
Data Protection: Exception - "The parameter is incorrect"

### ISSUE THREAD

**Issue by Pete1138** [aspnet/Home#3005] opened 2018-03-27 15:31 UTC
I receive a CryptographicException when the AntiForgeryToken is rendered in my MVC view (@Html.AntiForgeryToken). The error doesn't appear on a colleague's machine with identical code.

My setup is:

    var cert = GetCert()
     services.AddDataProtection()
                    .ProtectKeysWithCertificate(cert.Thumbprint)
                    .PersistKeysToRedis(redisConnection, "foo:dpikeys")
                    .SetApplicationName("foo.IdentityServer");

The keys are being successfully written to redis. I have  "[ValidateAntiForgeryToken]" attributes on my controller actions.

Exception stack trace:

    System.Security.Cryptography.CryptographicException: "The parameter is incorrect"
    at System.Security.Cryptography.NCryptNative.DecryptData[T](SafeNCryptKeyHandle key, Byte[] data, T& paddingInfo, AsymmetricPaddingMode paddingMode, NCryptDecryptor`1 decryptor)
    at System.Security.Cryptography.NCryptNative.DecryptDataPkcs1(SafeNCryptKeyHandle key, Byte[] data)
      at System.Security.Cryptography.RSACng.Decrypt(Byte[] data, RSAEncryptionPadding padding)
      at System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.DecryptKeyExchange(Byte[] rgbIn)
      at System.Security.Cryptography.Xml.EncryptedXml.DecryptEncryptedKey(EncryptedKey encryptedKey)
      at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
     at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
     at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
     at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
    at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
    at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>b__0()
    at System.Lazy`1.CreateValue()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Lazy`1.get_Value()
    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
    at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
      at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
      at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
       at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Serialize(AntiforgeryToken token)
       at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.Serialize(IAntiforgeryFeature antiforgeryFeature)
      at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetAndStoreTokens(HttpContext httpContext)
      at Microsoft.AspNetCore.Mvc.ViewFeatures.AntiforgeryExtensions.GetHtml(IAntiforgery antiforgery, HttpContext httpContext)
      at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateAntiforgery(ViewContext viewContext)
     at Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper.Process(TagHelperContext context, TagHelperOutput output)
       at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
       at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    at AspNetCore._Views_Account_Login_cshtml.<ExecuteAsync>d__27.MoveNext() in
    C:\Code\foo\foo.IdentityServer\Views\Account\Login.cshtml:line 0

**Comment by blowdart** [comment] 2018-03-27 17:05
This looks like a keyring error. Are you sharing keys? Where are they persisted?

**Comment by Pete1138** [comment] 2018-03-28 07:02
I'm using Redis. I'm only running this locally, and I've flushed my Redis Db to see if that would help (it doesn't).

**Comment by blowdart** [comment] 2018-03-28 12:41
Huh, that is weird. @BrennanConroy can you investigate?

**Comment by natemcmaster** [comment] 2018-03-28 19:38
@Pete1138 which version of aspnetcore are you using?

**Comment by Pete1138** [comment] 2018-03-29 08:09
Microsoft.AspNetCore is v2.0.1. My project is targeting .NET v4.6.2.

**Comment by Eilon** [comment] 2018-04-13 18:27
This is likely an issue with corruption in the encrypted file. We'll look at adding more debug logging info.

**Comment by natemcmaster** [comment] 2018-08-24 22:05
I've taken a closer look at this. Based on the stack trace and where the error occurred, I'm not really sure what DataProtection could do differently. The only thing I could think to add to debug logging is the raw contents of the encrypted xml, but that seems risky.

> The error doesn't appear on a colleague's machine with identical code.

The error appears to be due to differences in how the X.509 certificates are configured on different machines. In 2.0, it was pretty common to run into errors like when the X.509 cert was not installed into the right location in the Windows cert store. For anyone running into this in the future with 2.1 or above, I would recommended making this change.
```diff
X509Certificate2 cert = GetCert();

services.AddDataProtection()
-                .ProtectKeysWithCertificate(cert.Thumbprint)
+                .ProtectKeysWithCertificate(cert)
```

Closing as I'm not sure there is any action to take here, and I don't have steps to reproduce this. Feel free to continue discussion.

**Closed by natemcmaster** 2018-08-24 22:05 UTC
Labels: 1 - Ready, bug, repo:DataProtection

**Comment by natemcmaster** [comment] 2018-09-06 15:32
Without steps to reproduce, there isn't much I can do to help. The stack trace shows the error as coming from several layers below the ASP.NET stack which leads me to believe there is a problem with how the certificate was generated or there is a bug deep in the System.Security.Cryptography stack. Try creating a repro by using EncryptedXml APIs directly: https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-decrypt-xml-elements-with-x-509-certificates. That will get you closer to the source of the exception.

**Comment by NtFreX** [comment] 2018-09-07 07:48
Since my coworker installed the latest windows updates it seems to work on his machine. We still have some other machines where it doesn't work. Where should I report a issue with System.Security.Cryptography?

**Comment by NtFreX** [comment] 2018-09-07 11:12
The problem on my colleagues machine was that the certificate was only in the machine store and when decrypting an xml only the user store will be searched...

Strange as I though when using the certificate directly it will not try to load it from the store when decrypting? But the article you linked makes it clear that the certificate must be in the user store.

> The code example in this procedure decrypts an XML element using an X.509 certificate from the local certificate store of the current user account. 

https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-decrypt-xml-elements-with-x-509-certificates

Maybe this method produces the wrong result or is this the intended bahaivor?

    System.Security.Cryptography.Xml.Utils.BuildBagOfCerts

**Comment by janmarques** [comment] 2019-05-09 10:42
Running on .NET Core 2.2

Below example generates the error.
Note that if you keep the data array under 215, it won't crash, but anything 215 or over crashes

`using System;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var certificate = new X509Certificate2(Convert.FromBase64String("MIIDBzCCAe+gAwIBAgIJAPJHcapCIZ+TMA0GCSqGSIb3DQEBBQUAMBoxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbTAeFw0xOTA1MDkxMDE5MThaFw0yOTA1MDYxMDE5MThaMBoxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANarpMb78bHob2DNjcxMt0JNC9wzOCbxE7QoGaUqwtRPDWxeZS1vdS/C2pmdTA/jByePUKZDZT4DF+bGT5Yz7X+drIbTD6fnQ1vLBRblKrJlh/jUOqRMem5rcVvi51vXymSf5D2q/0ng/EeDtMsbZhI9S/L9N1gAH33LrpuMyFWeoDtYjZDykCB03Ph5A0CmJvhiJx4MyjHLzyTprsiCxa8SNggWMA2HiV7bRB1uabjP9PLYG55DAOFEcr7hd1tBtqxBWALa4AGtAYxTYEoioiYeG2GHjae1fXAxtlvQHW4WiXsAdyJG5vJ8f8xKZWMkdGONiYiPjhiq1SXuUeOW19MCAwEAAaNQME4wHQYDVR0OBBYEFLYsUPqOS2e7AEAipuiGy4Q1/ex9MB8GA1UdIwQYMBaAFLYsUPqOS2e7AEAipuiGy4Q1/ex9MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAATWrl4O8T1gwmxvwj8WAh8I4Wl7RUPHMHEYezyu6b+JSMQEYy2RPOjiOk8gE/CVtbRBL2kCjA0OoKBvP07PvnPGLQDPRJIeYdMjvZIgoyRrB4pz9ERD43rSgDB8/KOuQZ8pwLq8qDdesgRV4rRZWEqbgQoXmMpbSeD3eDFo7s0zd84h+NhgaGZ0lGasdzFV1p3jOMPtAJ4NVc1lUYkDzx+C09KHiwZ8AJAEsKZ+IeQtVP7zKLqpEA7t6d3F6AwSKYPFVhEdolC7EA+1ZPw3oDLjvevR4LcjZGBxKXfyhjWfjMtM813gd/6xlS7AYvwkZ494jDGqnJ32Nz8DQBbIuTo="));
            var data = new byte[215];
            new Random().NextBytes(data);
            using (var rsa = certificate.GetRSAPublicKey())
            {
                var encryptedMessageData = rsa.Encrypt(data, RSAEncryptionPadding.OaepSHA1);
            }
        }
    }
}
`
