### ISSUE TITLE
Nested sites in Azure app service gives 0x800700b7 "The specified CGI application encountered an error and the server terminated the process."

### ISSUE THREAD

**Issue by sdekock** [aspnet/Home#2822] opened 2018-01-24 23:51 UTC
I am trying to host 2 applications on 1 single Azure app service.
One application on the root / and one in /UI.
They are both configured as Application in the Application settings for the Azure app service.
Files are in site\wwwroot and site\wwwrootui respectively.

The root application works but the nested one gives "The specified CGI application encountered an error and the server terminated the process.".

If I change it so the root app also runs in a folder instead of the root (so no nesting) then both apps work fine.

The detailed error message reveals:

```
HTTP Error 502.3 - Bad Gateway
There was a connection error while trying to route the request.
Module	   AspNetCoreModule
Notification	   ExecuteRequestHandler
Handler	   aspNetCore
Error Code	   0x800700b7
Requested URL	   https://myapp:80/UI/
Physical Path	   D:\home\site\wwwrootui\
Logon Method	   Anonymous
Logon User	   Anonymous
```

Relevant lines in failed request trace:

```
87. | NOTIFY_MODULE_START | ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotification="false" | 23:35:00.587
-- | -- | -- | --
88. | MODULE_SET_RESPONSE_ERROR_STATUSWarning | ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="Cannot create a file when that file already exists.  (0x800700b7)", ConfigExceptionInfo="" | 23:35:00.587
89. | SET_RESPONSE_ERROR_DESCRIPTIONWarning | ErrorDescription="There was a connection error while trying to route the request." | 23:35:00.587
90. | NOTIFY_MODULE_END | ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", NotificationStatus="NOTIFICATION_FINISH_REQUEST" | 23:35:00.587
```

Web.config for the root app:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\MyApp.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Acc" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
```

Web.config for the nested app:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\MyApp.UI.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Acc" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
```

**Comment by Tratcher** [comment] 2018-01-24 23:55
@pan-wang wasn't there a bug with nested environmentVariables nodes?

Does it work if you remove environmentVariables?

**Comment by sdekock** [comment] 2018-01-25 00:10
@Tratcher 
Yes. That does seem to fix the error.
It also seems to inherit the environment variables so that is good enough for us for now.

Nesting the environment variables does work on a local IIS with 1.1.2 of Windows Server Hosting installed.

**Comment by Tratcher** [comment] 2018-01-25 00:27
Closing this as a duplicate of https://github.com/aspnet/AspNetCoreModule/issues/150#issuecomment-332067460

**Closed by Tratcher** 2018-01-25 00:27 UTC

**Comment by firecube** [comment] 2019-01-16 18:03
The suggested duplicate is not the same issue.  We have just been caught out by this after upgrading from v1 of asp dotnet core hosting bundle to 2.1.  The IIS hosting module has a different behaviour.

We have the same setup as described in this ticket.  A root dotnet core app with a child dotnet core app with both specifying the ASPNETCORE_ENVIRONMENT environment variable of production.  After the upgrade the child site crashes.  

The fix is to remove the setting in the child application and is not something that would be fixed by an SDK update in the linked issue.

Thanks, Simon
