### ISSUE TITLE
Cannot add reference to .net core Class library asp.net core RC2

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#1513] opened 2016-05-27 16:10 UTC
[Reference from Stackoverflow](https://github.com/aspnet/Home/issues/new)

Using RC2, When i add a reference to a dotnet console or web app from a dotnet class library, it by default does not build and has a dependnecy error.

Now the solution for me was NOT the accepted answer on that stackoverflow.  All I had to do was click "restore packages" for the project with the reference error.

Just want to make sure this gets logged and can be fixed for next release.

**Comment by davidfowl** [comment] 2016-05-29 05:40
Can you make a repo solution and push to github? It'll be easier to see if it's a bug or if something is misconfigured.

**Comment by igeligel** [comment] 2016-05-29 17:19
I have a similar error. I created a repository to show it:
[TestApplicationLibraryReferenceing](https://github.com/igeligel/TestApplicationLibraryReferenceing).

Preconditions

- Visual Studio Version 14.25123.00 Update 2
- dotnet --version is giving me: 1.0.0-preview1-002702

Procedure i have done for creating the console application and the class library:

1. [Create new .net core console application](http://i.imgur.com/HmjRBZv.png)
2. [Add another project to the solution](http://i.imgur.com/y1U8q0V.png)
3. [Choose class library for .net core](http://i.imgur.com/7Wzoihz.png)
4. [Add the reference](http://i.imgur.com/F5syqbW.png)


**project.json** of the console application:
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "TestClassLibrary": "1.0.0-*"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

**project.json** of the class library:
```json
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  }
}
```

**global.json**
```json
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview1-002702"
  }
}
```

**Comment by Sharpiro** [comment] 2016-05-30 17:09
I am actually now unable to re-create this issue.

All new dotnet core applications I create are no longer having trouble restoring packages when added as a reference.

I also pulled @igeligel 's solution down and tested it, and it worked fine for me as well.

This may only be a rare issue for people with a fresh install of RC2 VS tools.

**Comment by igeligel** [comment] 2016-05-30 17:34
Have you been using Visual Studio too or just the command line tools?

**Comment by Sharpiro** [comment] 2016-05-31 00:43
@igeligel I'm only using visual studio, no command line.

**Comment by Eneuman** [comment] 2016-06-07 17:34
I can confirm that this is a bug but it only happens when you do like this:
Open a project created in RC1.
Start upgrading it to RC2 by changing the global.json
Upgrade you first .dll project to RC2.
Upgrade the project referencing your first .dll project to RC2.
Compile.

Now the first project does not get compiled and the .dll is not copied.

A restart of VS solved my problem.

**Comment by Sharpiro** [comment] 2016-06-11 16:06
i'm actually finding that with RC2, after I make a change to my package.json, i'm almost always having to right click the project and click "restore packages" before it will do so.

**Comment by thomasthiry** [comment] 2016-06-26 15:20
I have this issue too. I think it's not a small issue, it's totally preventing me from using RC2. :-(
I have cloned igeligel's repo and I have the issue.

Has anybody found an solution since then? 
(restarting VS or forcing a restore did not change anything for me). I have also tried to change/remove the global.json to no avail.

**Comment by davidfowl** [comment] 2016-06-26 15:37
That guy seems to be using resharper, are you also using resharper?

**Comment by igeligel** [comment] 2016-06-26 15:48
@davidfowl I have disabled resharper back then and it was not working either. 

Anyway: Reinstalling the sdk (Important!: [SDK Installer](https://www.microsoft.com/net/download#core)) and the the [.NET Core Tooling Preview 1 for Visual Studio 2015](https://go.microsoft.com/fwlink/?LinkId=798481) helped me. After that and with disabled resharper i was able to reference class libraries.

**Comment by thomasthiry** [comment] 2016-06-26 16:09
@davidfowl I have disabled resharper and now it works! Thanks a lot for the tip!

More precisely, disabling the features ASP.NET, ASP.NET MVC and ASP.NET Razor in resharper's options solved my problem.

**Comment by thomasthiry** [comment] 2016-06-27 19:40
The issue was fixed in EAP 2. They mention it here: https://youtrack.jetbrains.com/issue/RSRP-458862
I have installed this version and the issue is fixed now.

**Comment by Sharpiro** [comment] 2016-07-05 13:40
I do not use ReSharper..

I just pulled down a project and installed VS Update 3 and dotnet sdk 1.0 preview 2 tools.

The first time i opened the solution, the project would not build, and i had to right click one of the projects and click "restore", which then caused all the projects to restore packages and then were able to build successfully.

**Comment by SaiKrishnaTej23** [comment] 2016-08-23 06:05
I have the similar issue. 

using ASP.NetCore Template 1.0.0 as Startup Project and other class libraries.
i am able to reference the class libraries to the project but unable to use the namespaces

**Comment by leisenstein** [comment] 2016-09-12 01:51
I am having the same issue, but none of the comments seem to fix this for me.

**Comment by pgolebiowski** [comment] 2016-09-24 20:09
@larsfjerm I can't believe this change fixed it for me too! 😅

**Comment by danielwertheim** [comment] 2016-09-25 16:57
Not working for me. But producing a NuGet for it using `dotnet pack` then installing that works.

**Comment by sureba73** [comment] 2016-12-07 04:50
Just include target framework entry for .netcoreapp as below and try again. It will work.

  "frameworks": {
    "netstandard1.6.1": {
      "imports": "dnxcore50"
    },
    **"netcoreapp1.1": {
      "imports": "dnxcore50"
    }**
  },

**Comment by OzBob** [comment] 2016-12-22 04:18
I've simplified it to even can not add reference to  in a .Net4.6.1 Console App. 
Repro repo https://github.com/OzBob/corespike

Ref xproj line:
https://github.com/OzBob/corespike/blob/master/CoreSpikeReferences/461ConsoleApplication1/461ConsoleApplication1.csproj#L53

and in ref library:

`    "frameworks": {
      "net461": {},
      "netstandard1.6": {
       "imports": "dnxcore50"
       }
      }`

Any suggestions?

**Comment by aspnet-hello** [comment] 2017-12-30 23:58
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Closed** 2017-12-30 23:58 UTC
