### ISSUE TITLE
/samples/latest/HelloWeb does not run in docker

### ISSUE THREAD

**Issue by davidwincent** [aspnet/Home#937] opened 2015-09-19 22:49 UTC
Trying to get https://github.com/aspnet/Home/tree/dev/samples/latest/HelloWeb working in a docker image on Ubuntu 15.04

Did follow the instructions at https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md and when I come to this step it fails:
```
sudo docker run -it -p 5004:5004 aspnet-home-helloweb
```
=>
```
System.InvalidOperationException: Unable to load application or execute command 'project.json'. Available commands: web, kestrel.
  at Microsoft.Dnx.ApplicationHost.Program.ThrowEntryPointNotfoundException (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.Exception innerException) [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.String[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.Host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args, IRuntimeEnvironment env, System.Runtime.Versioning.FrameworkName targetFramework) [0x00000] in <filename unknown>:0 
```

**Comment by davidwincent** [comment] 2015-09-19 22:51
Related issue: https://github.com/aspnet/Home/issues/936

**Comment by ahmetalpbalkan** [comment] 2015-09-19 23:08
@davidwincent let's close this. #936 is pretty much the root cause and pinpoints the problem (it's not about docker image)

**Closed** 2015-09-23 18:27 UTC
Labels: duplicate
