### ISSUE TITLE
After VS CTP5 "Couldn't determine an appropriate version of runtime to run."

### ISSUE THREAD

**Issue by saxx** [aspnet/Home#292] opened 2015-01-26 19:04 UTC
I've been playing around with the latest dev-builds for a MVC web application (the latest `beta3-*` builds at the moment). I installed the CTP5 of Visual Studio, since then I've been unable to get my projects working again. Whenever I try to run an application using IIS express, I immediately get the following yellow screen of death exception:
```
[InvalidOperationException: Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9920856
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
```
Unfortunately the provided link only redirects to the ASP.NET website. Google does not return anything, but it seems that others [have this problem as well](https://github.com/aspnet/Mvc/issues/1869).

I run Windows 10 Preview (build 9926) and KRE-CLR-x86.1.0.0-beta3-10921.

**Comment by cherrydev** [comment] 2015-01-26 22:36
I'm having exactly the same problem and I can't determine a work-around that works using IIS Express. Using the "k web" run target still works for me, though.

**Comment by Boglen** [comment] 2015-01-27 08:14
I'm having the same problem too.
I think the problem is that kvm renamed to dotnetsdk.
All nightly assemblies have a beta4-* version, and some targeted to .net 4.6 (v4.0.10 references).
I'm try to install dotnetsdk. All is ok, but VS 2015 CTP5 want %userprofile%\.kre and packages named kre-*

problem is probably here:
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet

**Comment by Boglen** [comment] 2015-01-27 08:33
will be nice to get fixed aspnet tasks for VS15 CP5 ;-)

**Comment by davidfowl** [comment] 2015-01-27 08:35
Thats the problem using the bleeding edge builds. Unfortunately there's no easy work around right now as things have been renamed.

**Comment by saxx** [comment] 2015-01-27 08:49
OK, thanks for the update, @davidfowl. Good to know this is only a "temporary" issue with the current builds.

**Comment by ninety7** [comment] 2015-01-28 14:27
@Boglen How did you install dotnetsdk? I couldn't find an install script just like kvm/kre.

**Comment by jersiovic** [comment] 2015-01-29 17:49
Looking forward to hear this solved

**Comment by Boglen** [comment] 2015-01-30 08:17
@ninety7 yesterday they roll back the changes, as I understand

**Comment by Boglen** [comment] 2015-01-30 08:18
waiting while dotnetsdk -> kvm renamed

**Comment by Boglen** [comment] 2015-02-04 07:41
Found solution:

I've deleted kvm and reinstalled from dev branch, install latest version of kre (beta4-11019).
Then i create hardlink from new .k directory to .kre (mklink /j .kre .k), create subdir runtimes hardlink to packages, rename. Duplicate package kre-clr-win-x86.1.0.0-beta4-11019 to kre-clr-x86.1.0.0-beta4-11019 (duplicate, not rename) and most impartant: place in wwwroot folder of your project web.config file

<?xml version="1.0"?>
<configuration>

  <system.web>
    <compilation debug="true" targetFramework="4.5" />
    <httpRuntime targetFramework="4.5" />
  </system.web>

  <appSettings>
    
    
    <add key="K_DETAILED_ERRORS" value="true" />
    
    <add key="bootstrapper-version" value="1.0.0-beta4-10999" />
    <add key="kre-version" value="1.0.0-beta4-11019" />
    <add key="kre-clr" value="CLR" />
    
  </appSettings>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>

and debug in IISExpress work now.

**Comment by Boglen** [comment] 2015-02-04 07:52
Next problem is that VS15 CTP5 with last kre build, moved from .kre to .k. and renamed from kre-clr-x86.1.0.0-* kre-clr-win-x86.1.0.0-* :-) won't publish to filesystem:

Cannot find KRE package entityframework.commands in the folder: 

Cannot find KRE package entityframework.commands in the folder: %userprofile%\.kre\packages
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets(108,5): Error : The ProjectK Runtime package needs to be installed. See output window for more details.

**Comment by shailensukul** [comment] 2015-02-07 05:24
I have the same issue but am unclear how to move forward.
I run KRE version KRE-CLR-x86.1.0.0-beta2

This was working until I upgraded the KRE version to beta4 .. I have reinstalled KRE and reset the Visual Studio installation but am still getting the  error below. Am at a loss as to how to proceed.. any feedback will be appreciated.

```
Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. 

Stack Trace: 


[InvalidOperationException: Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +506

[HttpException (0x80004005): Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9931632
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +191
```

**Comment by davidfowl** [comment] 2015-02-07 07:26
To make it all work go back to beta2, visual studio ctp5 won't work with anything newer. There were a bunch of things that got renamed that will cause grief. 

To go back, just set the default ailias back to beta2, `kvm alias default 1.0.0-beta2`.

**Comment by shailensukul** [comment] 2015-02-07 15:06
Thanks for the reply @davidfowl  
It helped me understand my issue a little better.
Unfortunately I am using  beta4 dlls in my project which leaves me in a very unpleasant state until this gets resolved. Fingers crossed we gets a fixed drop soon.

**Comment by Boglen** [comment] 2015-02-08 17:51
Beta4 work fine with ctp5. Create web.config in wwwroot, copy kre-clr-win* in kre-clr* and make hardline from runtimes to packages

**Comment by cherrydev** [comment] 2015-02-11 20:26
@Boglen thanks for your reassurance that we can get it working, but it would be excellent if you could please be more specific about what people need to do, for example:
* what should be the contents of web.config?
* copy kre-clr-win* to where?
* I don't understand what you mean by "hardline from runtimes to packages".

Thanks!

**Comment by Boglen** [comment] 2015-02-12 04:31
Open CMD.
cd %userprofile%
mklink /J .kre .k

then open c:\%userprofile%\.k\runtimes folder. Create duplicate of "kre-clr-win-x86.1.0.0-beta4-11037" 
 and rename to "kre-clr-x86.1.0.0-beta4-11037".
Copy c:\%userprofile%\.k\runtimes
To c:\%userprofile%\.k\packages
Open VS 2015 CTP5, open your project and define Target KRE version in properties to kre-clr-x86.1.0.0-beta4-11037.

Then open "wwwroot" folder in your project, create web.config file:

<?xml version="1.0"?>
<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.5" />
    <httpRuntime targetFramework="4.5" />
  </system.web>
  <appSettings>
    <add key="K_DETAILED_ERRORS" value="true" />
    <add key="bootstrapper-version" value="1.0.0-beta4-11005" />
    <add key="kre-version" value="1.0.0-beta4-11037" />
    <add key="kre-clr" value="CLR" />
  </appSettings>
</configuration>

Profit! 
bootstrapper-version - version of AspNet.Loader.dll

**Comment by Ciantic** [comment] 2015-02-21 19:54
@Boglen I've done the steps. Magical version numbers at the time of writing are: 1.0.0-beta4-11117 and 1.0.0-beta4-11122 for the AspNet.Loader.dll.

Problem is the Visual Studio says in the Solution Explorer: References (Errors - see error list) in error list there is "Illegal characters in path."

I've deleted .kpm/packages it didn't hlep.

**Comment by Ciantic** [comment] 2015-02-23 11:44
I got a new version using "kvm upgrade" yesterday, "11128" it works with the instructions above. What's more, I also got the Mvc debugging to work with this version.

**Comment by Boglen** [comment] 2015-02-24 06:17
@Ciantic yep. All you need to do - just rename the folders.  I think that CTP6 will coming soon and there will be corrected path

**Comment by davidfowl** [comment] 2015-02-24 06:20
CTP6 came out today. Get it now.

**Closed by davidfowl** 2015-02-24 06:20 UTC

**Comment by tugberkugurlu** [comment] 2015-04-11 14:31
I am getting same error saying that ***Couldn't determine an appropriate version of runtime to run*** when I try to execute iisexpress.exe. The command I ran:

> "C:\Program Files\IIS Express\iisexpress.exe" /path:"D:\github\confidence\artifacts\apps\ConfyConf.Client.Web\wwwroot" /port:9090 /clr:v4.0

**wwwroot** folder I am targeting here is created by `dnu publish` and web.config is:

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
		<appSettings>
			<add key="bootstrapper-version" value="1.0.0-beta4-11526" />
			<add key="runtime-path" value="..\approot\packages" />
			<add key="dnx-version" value="" />
			<add key="dnx-clr" value="" />
			<add key="dnx-app-base" value="..\approot\src\ConfyConf.Client.Web" />
		</appSettings>
	</configuration>

I am also getting the below iisexpress.exe output:

![image](https://cloud.githubusercontent.com/assets/328122/7101727/9ae2a57a-e05f-11e4-8930-8500cf7136dd.png)

I added the below `system.web` node to web.config but it didn't change anything:

		<system.web>
			<compilation debug="false" targetFramework="4.5.1" />
			<httpRuntime targetFramework="4.5.1" />
		</system.web>

**Comment by flyandi** [comment] 2015-07-15 20:02
I have the same issue as tugb

**Comment by GuardRex** [comment] 2015-07-15 21:52
@davidfowl suggested to me in [Home #452 (comment)](https://github.com/aspnet/Home/issues/452#issuecomment-92991558) to try `dnu publish --runtime active` to populate the `dnx-version` and `dnx-clr` of the generated `Web.config`. Does that work for you?
