### ISSUE TITLE
dnu no longer an executable

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#679] opened 2015-06-17 11:03 UTC
When updating to the latest DNX Mono runtime `dnx-mono.1.0.0-beta6-12085`, I get this error when using `dnu`:
```
-bash: /Users/henkmollema/.dnx/runtimes/dnx-mono.1.0.0-beta6-12085/bin/dnu: Permission denied
```

When looking at the `dnu` file in the `bin` folder I noticed that it is no longer an executable type, just a text file. It used to be an executable in earlier versions (beta4 for example).

**Comment by Eilon** [comment] 2015-06-17 17:21
@dougbu is this what you were just telling me about?

**Comment by dougbu** [comment] 2015-06-17 17:33
Yup. I'm working on the borked `dnvm.sh`.

**Comment by dougbu** [comment] 2015-06-17 18:10
Closing as dupe of aspnet/dnx#2081 though fix is primarily in aspnet/dnvm

**Closed by dougbu** 2015-06-17 18:10 UTC
