### ISSUE TITLE
[aspnet/CORS] No CORS headers sent if Exception is thrown

### ISSUE THREAD

**Issue by Lavinski** [aspnet/Home#3220] opened 2018-06-12 22:02 UTC
Normally headers are added however if a controller throws an exception then CORS headers not be present.

All matching responses should have CORS headers added. This problem affects the use of middleware (including the UseExceptionHandler middleware).

**Comment by Tratcher** [comment] 2018-06-12 22:13
Duplicate of https://github.com/aspnet/Home/issues/2378

**Closed by Tratcher** 2018-06-12 22:13 UTC
