### ISSUE TITLE
many confuse about asp.net core 2 

### ISSUE THREAD

**Issue by sunn789** [aspnet/Home#2260] opened 2017-10-27 17:55 UTC
first of all I install vs 15.4 ent and i had the same problem in 15.3 and work with MVC core 2 for create my web projects.
If i create relation in Class as a code first for create database and make relations, in controllers it's not good, it is the same as this:
```c#
ViewData["CustomerTypeId"] = new SelectList(_customerTypeRepository.GetAll(), "Id", "Id");
ViewData["CityId"] = new SelectList(_cityRepository.GetAll(), "Id", "Id);
```

in MVC 5 it was 

```
ViewData["CustomerTypeId"] = new SelectList(_customerTypeRepository.GetAll(), "Id", "Name");
ViewData["CityId"] = new SelectList(_cityRepository.GetAll(), "Id", "Name");
```

and the same in Index view on scaffold 
```html
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerType)
        </th>
```

in MVC 5 it was 

```
      <th>
            @Html.DisplayNameFor(model => model.City.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerType.Name)
        </th>
```

also in EF if I add migration and update-database with any relation and FK it's work nice and if I add new relation in my code first class, and want update-database got arrore that : I have problem in parent_table and child-table_id problem if i remove database and remove migration and add init migration and update_database it work nice .
thanks

**Comment by kshyju** [comment] 2017-11-21 00:09
What you mean by **"in controllers it's not good, "** What is your actual issue/question. Sorry ! I am having a hard time understanding your post.

**Comment by Eilon** [comment] 2018-01-09 23:55
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2018-01-09 23:55 UTC
