### ISSUE TITLE
"dnvm upgrade" does not work on OS X Yosemite 10.10.2

### ISSUE THREAD

**Issue by jensg** [aspnet/Home#485] opened 2015-04-25 20:00 UTC
When I execute `dnvm upgrade` I get the following:
sh-3.2# dnvm upgrade
Determining latest version
Error: Could not find latest version from feed https://nuget.org/api/v2

**Debug or Extra information:**

$DNX_ACTIVE_FEED="https://nuget.org/api/v2"
$_DNVM_RUNTIME_PACKAGE_NAME="dnx"
$platform="mono"
local url="$DNX_ACTIVE_FEED/GetUpdates()?packageIds=%27$_DNVM_RUNTIME_PACKAGE_NAME-$platform%27&versions=%270.0%27&includePrerelease=true&includeAllVersions=false"

The following URL gives me the following result:
https://www.nuget.org/api/v2/GetUpdates()?packageIds=%27dnx-mono%27&versions=%270.0%27&includePrerelease=true&includeAllVersions=false

    <?xml version="1.0" encoding="utf-8"?><feed xml:base="https://www.nuget.org/api/v2/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><id>https://www.nuget.org/api/v2/GetUpdates</id><title type="text">GetUpdates</title><updated>2015-04-25T19:56:37Z</updated><link rel="self" title="GetUpdates" href="GetUpdates" /><author><name /></author></feed>

**Comment by BrennanConroy** [comment] 2015-04-25 20:08
Use MyGet for getting dnx

**Comment by jrock2004** [comment] 2015-04-25 20:21
How would I do that? Could you give command or do we need to add another source?

**Comment by davidfowl** [comment] 2015-04-25 20:25
`dnvm upgrade -u`

**Comment by jensg** [comment] 2015-04-26 10:36
Still had some issues installing it but I could solve them:
`dnvm upgrade -u` I got errors running this and couldn't run it again without errors (Unfortunately I don't have the errors anymore).
When I entered `dnvm list` I had one DNX installed but it wasn't active and I couldn't activate it. I had to reinstall it by running: `dnvm install -f -u 1.0.0-beta5-11611`

**Comment by jrock2004** [comment] 2015-04-26 12:38
Dnvm upgrade -u worked for me

**Comment by glennc** [comment] 2015-04-27 23:40
Closing this one, since it seems to be resolved. @jensg if you get a reproduction of those errors let us know :).

**Closed by glennc** 2015-04-27 23:40 UTC
