### ISSUE TITLE
URL"#"后面的参数不能取，为什么

### ISSUE THREAD

**Issue by netnr** [aspnet/Home#2307] opened 2017-12-14 07:28 UTC
`http://localhost:60259/joke?#access_token=9609835A25F2010C593706D300BB2C79&expires_in=7776000`

上面这个请求，在后台（非页面，页面`location.hash`能取）`Request`取`#`后面的值，没有，为什么要忽略`#`后面的参数

**Comment by Tratcher** [comment] 2017-12-14 16:27
# refers to the fragment portion of a url and is only intended for local usage such as links within a page that are processed by the client without sending anything to the server. HTTP requires that requests do not send # fragments to the server. When used with an access_token it means you are expected to have client code that processes the value.

**Comment by JunTaoLuo** [comment] 2017-12-14 19:23
@Tratcher I think the question is why the arguments after `#` are not passed. Is the `expires_in` argument parsed in this case? Arguments must precede fragments no?

**Comment by Tratcher** [comment] 2017-12-14 19:26
Right. They're using the wrong auth flow, one designed for SPA apps that assumes the client will handle the parameters.

**Comment by Eilon** [comment] 2018-01-09 23:59
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2018-01-09 23:59 UTC
