### ISSUE TITLE
Unable to load DLL 'libuv': The specified module could not be found - (kestrel) Windows IOT

### ISSUE THREAD

**Issue by matizk144** [aspnet/Home#1111] opened 2015-11-22 11:51 UTC
Hi!
I just trying to run basic asp.net project (Hello world) on my RP2, but unfortunatelly always I received error:

```
.\web : System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    + CategoryInfo          : NotSpecified: (System.DllNotFo...LT: 0x8007007E):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNet.Server.Kestr
el.Networking.Libuv.loop_size()
   at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)
```

The problem not appear on my desktop computer for x86 & x64 architectures.
I checked packages and all looks fine, libuv.dll exists.
Btw, when I try run launch server in IOT using weblistener, server starts.

**Comment by moozzyk** [comment] 2015-11-22 20:47
You need to publish for win10-arm runtime (`--runtime` option) - bug https://github.com/aspnet/KestrelHttpServer/issues/340

**Comment by Eilon** [comment] 2015-11-22 21:14
@moozzyk close this?

**Comment by matizk144** [comment] 2015-11-22 22:16
Always I restore / publish with runtime option. I checked again and doesn't work. Btw. in published package "Microsoft.AspNet.Server.Kestrel" I have folder runtime:
To better understand I use path:
In location:
\\10.0.1.61\c$\compiled\approot\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc1-final\runtimes
I have folders: osx, win7-x64, win7-x86, win10-arm, which all include libuv.(in subfolder native)
Path example:
\\10.0.1.61\c$\compiled\approot\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc1-final\runtimes\win10-arm\native\libuv.dll

So, on first looks, that required dlls exists, but something is wrong to load dll. I tryied to rename folder win10-arm to win7-arm, but I have the same result.

**Comment by meriturva** [comment] 2015-11-23 14:03
The same here.....i think is it related to: https://github.com/aspnet/KestrelHttpServer/issues/216

**Comment by moozzyk** [comment] 2015-11-24 07:57
This is a bug indeed. I am not sure if this is a regression or I tried a slightly different scenario (probably the latter) because I did run Kestrel on a R-Pi2 to verify https://github.com/aspnet/dnx/issues/3095.
FWIW 
  - publishing with `--runtime` does not include win10 specific arm dlls because the application is published for win7-arm. I opened a bug for this in the dnx repo: https://github.com/aspnet/dnx/issues/3197
  - publishing with `--framework` is completely broken because the application is published for `win7-x86` and `win7-x64` even though my original app was only restored for `win10-arm`. For this I [commented](https://github.com/aspnet/dnx/issues/3183#issuecomment-159185658) on a bug we already had

I think for now the problem could be worked around adding `{APPFOLDER}\approot\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc2-15950\runtimes\win10-arm\native` to the `%PATH%`.

**Comment by matizk144** [comment] 2015-11-24 08:28
I resolved problem, copying libuv.dll to folder, where Microsoft.AspNet.Server.Kestrel exist. But unfortunatelly I observed, that in published package, published runtime (dnx) still use packages from C:\Users\[user\.dnx\packages.

**Closed** 2015-12-15 18:31 UTC

**Comment by MelbourneDeveloper** [comment] 2016-11-22 00:43
I'm getting this error as well. I have all the latest NuGet packages for ASP .NET Core as of right now

**Comment by moozzyk** [comment] 2016-11-22 00:52
You can get this error since this applies to win10-arm and currently there is no arm runtime available. See also: https://github.com/aspnet/KestrelHttpServer/issues/216#issuecomment-262114923
