### ISSUE TITLE
Custom Web.config - aspNetCore section gets overwritten in Debug and Release mode

### ISSUE THREAD

**Issue by rockerinthelocker** [aspnet/Home#2993] opened 2018-03-22 22:53 UTC
After upgrading to Visual Studio 15.7 Preview 2 (added ANCM InProcess support for IIS Express), the **aspNetCore** section of a custom Web.config added to the project gets overwritten when starting IIS Express in Debug mode via Visual Studio UI. If **hostingModel="InProcess"** exists, this attribute gets removed so the application won't run in-process. Also, **startupTimeLimit="3600"** and **requestTimeout="23:00:00"** are added. Finally, environment variables **ASPNETCORE_HTTPS_PORT** and **ASPNETCORE_ENVIRONMENT** are added as well. Of course, deploying such a messed up Web.config file to the production server doesn't work out well.

**Comment by Eilon** [comment] 2018-03-22 23:32
@shirhatti / @jkotalik / @muratg - where should this issue get routed to?

**Comment by shirhatti** [comment] 2018-03-22 23:34
@BillHiebert

**Comment by rockerinthelocker** [comment] 2018-03-23 01:45
@muratg , Just checked and happens in release mode as well. Only publish is not affected.

**Comment by muratg** [comment] 2018-03-23 17:49
Thanks @rockerinthelocker, yeah that's a little less surprising :) 

@BillHiebert where is the best place to track this issue?

**Comment by postie77** [comment] 2018-03-27 02:54
Upgraded to Visual Studio 15.6.4 yesterday and can confirm it is also happening on that version.

**Comment by BillHiebert** [comment] 2018-04-10 16:34
@postie77 - are you running against IIS or IIS Express? if IIS this is the expected behavior, though we are investigating trying to improve this.  For IIS Express, if you remove the ANCM information from web.config, VS will write it into the applicationhost.config file that resides in the <solutionfolder>\.vs\config. The timeouts are there to prevent ANCM from terminating the process while you are stepping through code in the debugger. The environment variables are added to support IIS where it is difficult to set environment variables on the W3WP.exe  process.

**Comment by masterjs** [comment] 2018-04-10 19:14
@BillHiebert We're also seeing this on our side. We are often deploying (using publish - right click on the web project) on our local IIS. This then "transforms" our web.config with theses unwanted values. The devs usually forgets them and they get checked-in, then it moves "silently" into the other environments. Really annoying. Using VS 15.6.5.

**Comment by yosbeleg89** [comment] 2018-05-14 20:29
I think this is related and it seems to be fixed in the latest release of VS
https://developercommunity.visualstudio.com/content/problem/220371/webconfig-modified-startuptimelimit3600-requesttim.html

**Comment by Eilon** [comment] 2018-07-13 23:51
Closing because it appears this issue is fixed. If anyone is still running into this, please let us know. Thanks!

**Closed by Eilon** 2018-07-13 23:51 UTC

**Comment by dmitryshunkov** [comment] 2018-11-15 16:05
After upgrading to Visual Studio 15.9.0 the issue returned. After IIS Express start web.config gets overwritten with added `<environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44350" />` line. If this matters, I have next configuration in launchSettings.json:

````
"iisSettings": {
  "windowsAuthentication": false,
  "anonymousAuthentication": true,
  "iisExpress": {
    "applicationUrl": "https://localhost:44350/",
    "sslPort": 44350
  }
}
````

**Comment by ChristopherL-STCU** [comment] 2018-12-19 16:41
Similar issue which has been happening for a bit of time now, so not sure exactly which version this started happening in. 

    <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="#{ASPNETCORE_ENVIRONMENT}"/>

Is being overwritten with:

    <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />

**Comment by dmitryshunkov** [comment] 2018-12-19 17:16
@ChristopherL-STCU, during investigation of other issue I stumbled on this [comment](https://github.com/aspnet/websdk/issues/115#issuecomment-321856226), according to it, web.config will be rewritten any time, where it is present and it is different from what ANCM module is generating during startup.  So, the possible solutions to keep web.config untouched by ANCM for now are:
 - remove ANCM information from web.config or completely remove it from project and don't use IIS Express for development (instead use kestrel, etc)
- or modify web.config to the state, that ANCM wants it to be and move your custom part to other file (for example transformation file) and apply it before your main replacement involved (Octopus variable substitution, I guess).
