### ISSUE TITLE
Health Checks

### ISSUE THREAD

**Issue by louislewis2** [aspnet/Home#2218] opened 2017-09-28 22:05 UTC
Hi, 

I am wondering what is happening / the current status of the health checks.
The code was here, then it moved to another repo. According to the docs,
we are meant to clone the repo, copy code into our projects to make use of it.

This is less than ideal, as a nuget package would most certainly be first prize.
Also no active development can be seen on that repository which is unnerving.
Is it perhaps that their is no active development because its already perfect? If so,
then why cant a nuget package be released, even if it was a preview release?

Also if it is part of Asp.Net Core, why does the repo not live here with all the other ones?

The roadmap mentions this as part of 2.0 if I am not mistaken, so just wondering about that too. If it was missed and is going to form part of the 2.1 release, I am thinking that at least some work would have been on it by now, even if it was bringing the projects up to date with the latest released bits, the current host dependency is sitting at 1.0.2. There is also not much love given to pull requests, that do not seem all that complicated to provide an accept / reject answer on, I can of course be wrong. Its just how it looks when looking at the repo.

Just a few questions for those who cannot copy source code of what may or may not be what is actually going to land. One can work with preview packages and feel slightly better about it, I think. So any insight or feedback will be greatly appreciated.

**Comment by Tratcher** [comment] 2017-09-29 16:07
@anurse

**Comment by anurse** [comment] 2017-09-29 16:33
We are looking at health checks in 2.1, in fact I've started work on it this week 😄. The [code you referred to](https://github.com/dotnet-architecture/HealthChecks) was an early exploration of the idea, but at the time we weren't ready to ship it as a product (which is why it wasn't part of the 'aspnet' GitHub organization).

cc @DamianEdwards @glennc

**Comment by louislewis2** [comment] 2017-09-29 17:19
That is fantastic news and thanks for clearing things up.
Cant wait to play with it 😄 . If possible ping when the repo goes up and when bits are flowing in, will be great to follow and get hands on it soon.

**Comment by anurse** [comment] 2017-09-29 19:05
I'll try to remember to ping this thread when there's a repo! We're definitely looking for plenty of feedback in this area :).

**Comment by mpoettgen** [comment] 2018-02-12 10:43
@davidfowl, @Eilon, does unassigning @anurse mean that Health Checks are not considered for 2.1 anymore? It wasn't mentioned in the roadmap announcements either. Would you consider doing health checks out of band and/or as a community effort? Thanks for the update.

**Comment by Eilon** [comment] 2018-02-12 18:27
@mpoettgen I've assigned this to @glennc who I'm hoping can share some info on this.

**Comment by glennc** [comment] 2018-02-14 18:49
HealthChecks just missed out on being included in 2.1. We still hope to do something here, but it didn't quite make it above the cut line. The problem isn't really the work that's required, but the design and overall experience. HealthChecks may become part of a larger diagnostics and monitoring effort that we start work on, so it is more about fitting it in with everything rather than getting people to actually write code.

**Comment by louislewis2** [comment] 2018-02-14 19:00
Ouch! Thanks for the update however.

**Comment by mpoettgen** [comment] 2018-02-14 22:16
@glennc, thanks for the update. However I don't really understand the reasoning about the larger effort. Health checks are an important part in enterprise operations to support monitoring, SLA tracking, load balancing, judging Docker container health and whatnot. All it takes is a simple endpoint that when pinged responds with a proper message as long as everything is in order. Health checks are about the health of an application, even if it is not doing anything, to ensure that it is ready when it is supposed to do something. Health checks are not supposed to provide any details about the application to an outsider. Diagnostics are providing details about what is happening while the application is doing something. That's important, but a separate concern. Monitoring is on the other end of health checks and will usually be performed by a monitoring solution, load balancer, orchestrator or other external tool. So it's an entirely separate concern as well. What keeps you from cleaning things up a bit, if necessary, and giving it to the people? There is even documentation on docs.microsoft.com explaining how to use it, but the hardest part is installing it, because you've never released NuGet packages.

**Comment by glennc** [comment] 2018-02-14 23:33
Yeah, it's was super painful for us. Damian agonized over it, but I think we will get a much better e2e then what we first envisioned by leaving it for a little while.

**Comment by aspnet-hello** [comment] 2018-07-11 21:14
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2018-07-11 21:14 UTC
