### ISSUE TITLE
ArgumentException: Specified value has invalid Control characters.

### ISSUE THREAD

**Issue by GermanKuber** [aspnet/Home#3039] opened 2018-04-09 19:06 UTC
Hello I am using .net core last version and I am trying to download a file through Http Request.
But I receive every time the same error :

> {System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at System.Net.HttpValidationHelpers.CheckBadHeaderValueChars(String value)
   at System.Net.WebHeaderCollection.Set(String name, String value)
   at System.Collections.Specialized.NameValueCollection.set_Item(String name, String value)
   at System.Net.HttpWebResponse.get_Headers()
   at RestSharp.Http.ExtractResponseData(HttpResponse response, HttpWebResponse webResponse)
   at RestSharp.Http.<>c__DisplayClass20_0.<ResponseCallback>b__0(HttpWebResponse webResponse)
   at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
   at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback)}

In my response I have the next parameter in the header, which I suppose that produce the error:

![image](https://user-images.githubusercontent.com/12403766/38517145-60851cbe-3c0f-11e8-8e61-d13c814ea0cc.png)

Specifically this line:
originalfilename: ANALISIS DE ADJUDICACIÒ�SN CROMATOGRAFOS NEUQUEN.docx.xlsx

**Comment by Eilon** [comment] 2018-04-09 20:11
@Tratcher - is this expected behavior for this header?

**Comment by Tratcher** [comment] 2018-04-09 22:27
Yes, the � is a big red flag, and the Ò woudln't be allowed in many stacks either.

**Comment by Eilon** [comment] 2018-07-10 15:51
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

**Closed by Eilon** 2018-07-10 15:51 UTC
