### ISSUE TITLE
dotnet SomeAssembly.dll not loading appsettings.json

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#2852] opened 2018-02-06 00:30 UTC
_From @giridharprakash on February 2, 2018 4:46_

## Steps to reproduce
create new dotnet core web api project
Get some configuration from appsettings.json in Startup.cs like eg connection string
dotnet publish -c Release
Now go to publish directory and run dotnet Assembly.dll

## Expected  behavior
While debugging in visual studio everything working fine
but when i run from command line then it's not loading appsettings.json

## Actual behavior
In startup.cs connection string is coming as null
var connectionString = Configuration["AppSettings:ConnectionString"];

## Environment data
`dotnet --info` output:
 dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

_Copied from original issue: dotnet/cli#8523_

**Comment by davidfowl** [comment] 2018-02-06 05:05
@giridharprakash you need to run the application from the correct folder. By default, the content root (the root path where config files are searched) is the current working directory.

**Comment by fritogotlayed** [comment] 2018-03-10 04:17
I would love to have a fix for this as well. Even if it's just an additional command line switch for now. My use case is a `Makefile` where I'd like to be able to run the app via make and have it pick up the setting appropriately.

FWIW the code here is my "example": https://github.com/fritogotlayed/corp-hq/blob/mongo-demo/Makefile#L17-L19

**Comment by dallancarr** [comment] 2018-03-10 10:52
@fritogotlayed . Imho. You shouldnt access the Debug folder in that way for production purposes. The 

> dotnet publish 

output should be referenced

**Comment by fritogotlayed** [comment] 2018-03-10 16:00
@dallancarr That Makefile reference is for local dev only. Production is done through a docker file. https://github.com/fritogotlayed/corp-hq/blob/mongo-demo/app/api/Dockerfile . The `dotnet publish` can be seen on line 12 :-). Definitely thanks for the tip though!

**Comment by fritogotlayed** [comment] 2018-03-10 16:13
For anyone else that stumbles across this thread I'll admit I am an idiot. I missed the `-p` flag when I was reading the docs on [`dotnet run`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore2x). I'll update my previous comment link so the code doesn't change when I amend my branch.

**Comment by Eilon** [comment] 2018-03-12 18:27
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

**Closed by Eilon** 2018-03-12 18:27 UTC

**Comment by seaside2** [comment] 2018-07-24 06:49
take a look at:
https://stackoverflow.com/questions/48429268/custom-keys-in-appsettings-json-not-working-in-asp-net-core-2-0/51376132#51376132

**Comment by lkts** [comment] 2018-09-25 07:57
I have just hit this during my Docker workflow for new application. I see this is by design, but in my opinion it is pretty unintuitive behavior. Can it be improved ?
