### ISSUE TITLE
Cannot add project reference if the Assembly Name is different from the Project name. Error NU1001

### ISSUE THREAD

**Issue by NJKA001** [aspnet/Home#1518] opened 2016-05-29 15:19 UTC
Notes: The project type and framework type probably don't matter but just in case. I'm adding the specifics.

Create a new Asp.Net Core Web Application (.NET Framework). with Target Framework 4.5.1 in VS (2015 here)
Then add a standard .Net Class Library project to the solution. (using default name ClassLlibrary1)
Add a project refrerence to ClassLibrary1 to the ASP.Net WebApplication1 project.
All is good.
Now remove the reference.
Open the project properties for the ClassLibrary1 project and now and change Assembly Name from ClassLibrary1 to say 'MyCompany.ClassLibrary1"
Now try and reference the ClassLibrary1 project again.
This time you will get a Package restore failed. Error code NU1001. Which tells you absolutly nothing about what the issue is or might be!!! (typical nuget).

Conclusion you cannot add a Project Reference if the AssemblyName is different from the Project name. This is very surely a very common. I.e. we always drop our company name from the project name.

Thanks

**Comment by davidfowl** [comment] 2016-05-29 17:41
Duplicate of https://github.com/aspnet/Tooling/issues/527

**Comment by aspnet-hello** [comment] 2017-12-30 23:57
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2017-12-30 23:57 UTC
