### ISSUE TITLE
Certain Sequence of Text/HTML on Razor Page Results in Error "rzc generate exited with code 1" During Build

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#3294] opened 2018-07-04 02:37 UTC
_From @robinwilson16 on July 3, 2018 19:3_

I have discovered a strange bug where certain text and HTML I add to a Razor page results in the following error and the project failing to build and this did not occur on 2.0 as I am migrating the existing pages:
```
rzc generate exited with code 1.
WebApplication1	
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	121	
```

I can make the error go away by just changing the formatting slightly such as removing some of the blank line breaks, removing the emoticon or removing the img tag but either way the syntax is valid.
Also until I get rid of the error I cannot create any new razor pages either as get the same error.

I did wonder if there was some special character but as changing any bits of the text cause it to work again it seems to just not like this exact sequence of text.

I can replicate by creating a new .NET Core Web Application in VS.NET (latest build) and pasting the following into one of the Razor pages exactly as is:
```
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <img src="~/images/TroubleGettingFinanceWeCanHelp.jpg" class="img-fluid mx-auto d-block" alt="Trouble getting finance? We can help">
        </div>
        <div class="col-sm-8">
            <p>Metro Centre Auto World is a family owned and run business.</p>

            <p>We pride ourselves on the great service we provide to all of our customers.</p>

            <p>Been turned down for finance? We can help with finance options tailored to suit your needs.</p>

            <p>We understand that buying a car can be a daunting prospect, so we strive to make the buying process as simple and hassle-free as possible.</p>

            <p>But don't just take our word for it, <a href="https://www.autotrader.co.uk/services/car-dealers/uk/north-east/tyne-and-wear/gateshead/mainline-uk-gateshead-dpp-27856/reviews/true" target="_blank" rel="noopener">see what some of our customers have to say about us...</a></p>

            <a class="btn btn-light" href="https://www.autotrader.co.uk/services/car-dealers/uk/north-east/tyne-and-wear/gateshead/mainline-uk-gateshead-dpp-27856/reviews/true" target="_blank" rel="noopener">
                💬 See what people are saying
            </a>
        </div>
    </div>
</div>
```
I just need to remove a line break between any of the sets of P tags and the build is successful.
The page did have more content on it but I reduced it down to find which bit was triggering the error.

_Copied from original issue: dotnet/corefx#30816_

**Comment by robinwilson16** [comment] 2018-07-04 07:40
Hello @karelz 
Is it possible to tell me why this was closed as surely this is some sort of bug in the compiler/build if it crashes with this exact text, yet if I take out the img tag or one of the P tags or adjust spacing then it compiles correctly.
It makes no sense for it to behave this way and in the layest build of Visual Studio (15.7.4) I can crash any new/existing .NET Core 2.1 project if I paste the exact text into a razor page then just adjust it slightly and it is fine. Also .NET Core 2.0 has no problem with the text, only 2.1.
I did waste a few hours troubleshooting what was wrong until I worked out the cause.

Thanks
Robin

**Comment by karelz** [comment] 2018-07-05 02:01
@robinwilson16 it was not closed.
I think the GitHub UI is misleading you - check top of the page with green "Open" badge on the left, associated with this specific issue. The "Closed" badge above your last comment on the right side is status of your original issue in CoreFX, which was moved to the right repo (ASP.NET) and therefore closed in CoreFX (which is about BCL, not about Razor, ASP.NET or anything like that - see [CoreFX main page](https://github.com/dotnet/corefx#net-core-libraries-corefx)).
Your issue has been routed to the right place where it can get better attention from experts.

**Comment by pranavkm** [comment] 2018-07-05 17:58
cc @NTaylorMullen

**Comment by robinwilson16** [comment] 2018-07-08 12:40
Hello Karel

Sorry for posting in the wrong place and yes it did look closed so sorry for being confused.

It is a strange issue where only a certain sequence of text/html seems to trigger the compiler crash.

Thanks for clarifying.

Robin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NTaylorMullen** [comment] 2018-07-11 17:49
This issue was moved to aspnet/Razor#2470

**Closed by NTaylorMullen** 2018-07-11 17:49 UTC
Labels: 2 - Working, investigate
