### ISSUE TITLE
IXmlRepository contract to support removing elements

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2320] opened 2018-01-01 06:57 UTC
_From @kosa-gyula-77 on Thursday, December 28, 2017 6:55:07 AM_

Currently in version 2.0.1 _IXmlRepository_ implementers has to parse _XElement_ and determine its expiration date in order to remove expired elements from the underlying storage. Elements otherwise just get added but not removed.

**Proposal:**

IXmlRepository - or a new interface - exposes an additional method that allows the _XmlKeyManager_ to make regular house cleaning by removing expired and/or revoked elements, e.g.:

`void RemoveElement(string friendlyName);`

            
_Copied from original issue: aspnet/DataProtection#293_

**Comment by blowdart** [comment] 2018-01-02 20:03
The reason we don't delete is so that any persisted data that has been protected with old keys can still be decrypted. This works much like X509Certificates, where you keep the expired certificates around to decrypt material, but they can't be used to encrypt new material. So, such an API would go against this. 

Closing as by design.

**Closed by blowdart** 2018-01-02 20:03 UTC
Labels: repo:DataProtection
