### ISSUE TITLE
Could not load type 'Microsoft.AspNet.Builder.RequestDelegate' from assembly 'Microsoft.AspNet.Http.Abstractions'

### ISSUE THREAD

**Issue by joshcomley** [aspnet/Home#1171] opened 2015-12-11 16:51 UTC
Hi, this is the same as [this closed issue](https://github.com/aspnet/Home/issues/1138#event-477357561), but my `projects.json` is as follows:

```
{
  "userSecretsId": "aspnet5-DayZero.Authentication.OpenIddict.FrontEnd-b0f1ba04-75c2-4d15-b21c-811b3e57c3f7",
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-*",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-*",
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-*",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-*",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-*",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-*",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-*",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-*",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-*",
    "Microsoft.Extensions.Logging": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-*",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-*"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}
```

My references all seem to be correct:

![References](http://i.imgur.com/D5RDBEM.png)

I just created a new `ASP.NET 5` MVC project with Individual Accounts.

Any thoughts?

**Comment by davidfowl** [comment] 2015-12-11 17:12
> My references all seem to be correct:

Not really, application insights is RC1 and the rest of your references are RC2. That's enough to cause problems.

**Comment by joshcomley** [comment] 2015-12-11 17:27
Ah, you are right! I scoured but missed that somehow. I have removed all references to Application Insights, but now am left with a load of Razor compilation errors preceded by this: 

'System.DllNotFoundException' in Microsoft.AspNet.Server.Kestrel.dll

Additional information: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by Eilon** [comment] 2015-12-12 05:15
Hmm what OS is this? Are you publishing from Windows to a Linux machine or something?

**Comment by takazm** [comment] 2015-12-17 20:24
I am having the same issue

**Comment by takazm** [comment] 2015-12-17 20:43
Part of my project.json as as follows:


 "dependencies": {
        "System.Net.Primitives": "4.0.11-rc2-*",
        "Microsoft.AspNet.Mvc": "6.0.0-rc2-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-rc2-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-rc2-*",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc2-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-rc2-*",
        "Microsoft.AspNet.Identity":"3.0.0-rc2-*",
        "Microsoft.AspNet.Cors": "6.0.0-rc2-*",
        "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-*",
        "Microsoft.Extensions.DependencyInjection": "1.0.0-rc2-*",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc2-*",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-rc2-*",
        "Microsoft.AspNet.Authentication.Google": "1.0.0-rc2-*",
        "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-rc2-*",
        "Microsoft.AspNet.Authentication.Twitter": "1.0.0-rc2-*",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc2-*",
        "Microsoft.AspNet.Http.Abstractions": "1.0.0-rc2-*",
        "Microsoft.AspNet.Http": "1.0.0-rc2-*",
        "Microsoft.AspNet.Http.Extensions": "1.0.0-rc2-*",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc2-*",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-*",
        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-*",
        "EntityFramework.Core": "7.0.0-rc2-*",
        "EntityFramework.Commands": "7.0.0-rc2-*",
        "EntityFramework.Relational": "7.0.0-rc2-*",
        "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc2-*",
        "Annotations.Lease.Service": "1.0.0-*",
        "Annotations.Lease.Entities": "1.0.0-*",
        "Annotations.Lease.DataAccess": "1.0.0-*",
        "Swashbuckle": "6.0.0-*",
        "System.Xml.XPath": "4.0.1-rc2-*"
    },

    "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5888",
        "ef": "EntityFramework.Commands"
    },

    "frameworks": {
        "dnxcore50": { }
    },

**Comment by takazm** [comment] 2015-12-17 20:46
The above references all have an asterisk at the end just before the closing quotation mark. Looks like the editor removed them after pasting.

**Comment by pranavkm** [comment] 2015-12-17 23:25
Similar to David's comment: https://github.com/aspnet/Home/issues/1171#issuecomment-163993706. `Swashbuckle on NuGet.org currently targets rc1 packages. You shouldn't mix and match RC1 and RC2 references.

**Comment by takazm** [comment] 2015-12-18 06:28
Thanks. That was the cause of the problem. I managed to download the source for Swashbuckle report and updated the ref to MVC rc2 and it worked

**Comment by moozzyk** [comment] 2015-12-18 21:51
`Additional information: Unable to load DLL 'libc': The specified module could not be found. (Exception     from HRESULT: 0x8007007E)`

This is a benign bug in Kestrel - when running on desktop Clr we call uname and catch the first chance exception.

**Comment by moozzyk** [comment] 2015-12-21 18:30
`Unable to load DLL 'libc'` on Windows fixed in https://github.com/aspnet/KestrelHttpServer/commit/aaf84afaffc2661337bbafd7f8501680513940b2

**Comment by aspnet-hello** [comment] 2017-12-31 20:21
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2017-12-31 20:21 UTC
