### ISSUE TITLE
CORS issue whe sending only a file from Js.

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#3238] opened 2018-06-18 15:36 UTC
_From @ManuelDev1810 on June 18, 2018 12:22_

Have one of you guys have problem about sending files with asp.net core 2.0 or 2.1, I mean i did it great with razor and all were fine, but now I am sending a file with js,   and I don't why throw that is not allowed CORS... I don't know why because all the other actions works fine with the  cors defined.

Configure Services

`
    services.AddCors(options => {
                options.AddPolicy("AllowAllOrigin", builder =>
                builder.WithOrigins("http://localhost:3000")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials()
                );
            });
`

Configure

`app.UseCors("AllowAllOrigin");`

Action

        [EnableCors("AllowAllOrigin")]
        [Route("img")]
        [HttpPost]
        public async Task<IActionResult> CreateImg(IFormFile file)
        {
            if (file.Length != 0)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                return Ok(file);
            }
            return BadRequest();
        }

`
I get the file, but when goes to use the  

`
 using (var stream = new FileStream(path, FileMode.Create))
      {
                    await file.CopyToAsync(stream);
     }
`
 throw not allowed CORS
Sorry it is kind of big
All the others action works fine with the cors defined, but i dont get why with the file throw me not allowed by CORS

`
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 500.
`

JS

 let file = this.logo.files[0]
        let data = new FormData()
        data.append('file', file)
        let img = {
            method: 'POST',
            body: data
        }
        await fetch('https://localhost:44365//api/home', img);

How i told you, i get the file in the action, but when goes to
`
 using (var stream = new FileStream(path, FileMode.Create))
      {
                    await file.CopyToAsync(stream);
     }
`
Throw the exception.

--------------

I really don't why because all the other actions works fine with the  cors defined.

_Copied from original issue: dotnet/corefx#30486_

**Comment by Tratcher** [comment] 2018-06-18 15:38
Duplicate of https://github.com/aspnet/Home/issues/3236

**Closed by Tratcher** 2018-06-18 15:38 UTC

**Comment by ManuelDev1810** [comment] 2018-06-18 18:42
Yeah sorry, it is a duplicate, I did it unintentionally.  But can you guys please tell me what is the that i have ?

**Comment by ManuelDev1810** [comment] 2018-06-20 08:44
The problem was that I didn't have the Img folder...  wwwroot/Img
