### ISSUE TITLE
Site being served over HTTP on IIS despite HSTS and redirects enabled

### ISSUE THREAD

**Issue by svallis** [aspnet/Home#3207] opened 2018-06-07 15:21 UTC
I hope I'm not missing something simple here, but if I deploy a brand new `dotnet new razor` site using 2.1.0 to our IIS hosting platform, pages can still be requested over HTTP. I have verified that the hosting environment is `Production`, and yet despite the `app.UseHsts();` and `app.UseHttpsRedirection();` insecure requests seem to still work under some circumstances.

Using Chrome, if I open a new tab and type the bare host/domain, I see a `307 Internal Redirect` in the logs that gives a non-authoritative reason of HSTS, which is what I expect to see. However, if I open a new incognito tab and prefix the host/domain with `http://` then the site loads with a `200 OK` on an insecure connection.

Am I missing something obvious here and this is working as intended? I expected that it would be impossible to request an unencrypted version of any pages. I should note that in a development environment I cannot reproduce this behaviour, even though `app.UseHsts();` is not called all insecure requests seem to be redirected.

**Comment by Tratcher** [comment] 2018-06-07 16:07
Duplicate of https://github.com/aspnet/Home/issues/3176

**Closed by Tratcher** 2018-06-07 16:07 UTC
