### ISSUE TITLE
Post build is not executing.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#432] opened 2015-04-02 20:08 UTC
in project.json I have:

```
    "scripts": {
        "postrestore": [ "npm install", "bower install" ],
        "postbuild": "brunch build" // also tried ["brunch build"] as an array.

    }
```

if I do in powershell brunch build, everything works as expected (and files get into wwwroot), but If I change some source files, or do an explicit build, the brunch build is not executed. What am I missing? I'm using CTP6.

**Comment by davidfowl** [comment] 2015-04-02 20:16
Yes this is confusing behavior. In visual studio design time builds don't trigger those events. The idea was to to a quick spell check within VS and not tie arbitrarily slow build events that can slow down the edit refresh experience.

We'll need to find a middle ground here, we don't have a good one today. To run that postbuild step, go into the project properties -> Build tab -> Produce outputs on build.

**Comment by Bartmax** [comment] 2015-04-02 20:59
I see what you are saying here. Changing the `produce outputs on build` works but looks like it does more stuff than needed and I see why a middle ground is desired. 
I'm pretty sure you already have some ideas to handle this, but I want to drop my 2cents just in case.

The most common scenario that I can think of as it is likely to be used is when cloning/downloading a project and open it for first time. (On pack is the other but we have "prepack" and "postpack" already.)

While roslyn watch for server source files, I think task runners should be the ones watching for client source file.

I think what would be ideal, is to say something like :
"sync this (optional) process/command with my application while on debug."

When the application is run/launch [in debug mode], if process/command is running, do nothing. else run the process/command. [Note: This can be a taskRunner watch or a taskRunner build, or something else, not strictly a watch command].

run application means, "debug",  "view in browser", "k web" (or kestrel or whatever serves the app). 
Maybe when Startup.cs code is executed ?? (this doesn't sounds good).

how? "onrun" inside "scripts" sounds perfect :D

Task runners also have the option to start the web servers, but that I can not imagine how will work with attached debug and other scenarios.

**Comment by stajs** [comment] 2015-11-25 10:09
Any update on the "middle ground" for this?

I'm using `dnx46 1.0.0-rc1-final` and I want to hook in to the `prebuild` so I can generate `.cs` files ([bridging SpecFlow until DNX is supported](https://github.com/stajs/SpecFlow.Dnx)).

Since I had already created a smaller reproduction of the problem, I might as well post it here for your consideration.

- [`DnxPrebuild.Library`]
(https://github.com/stajs/DnxPrebuild.Library) - A [simple console app](https://github.com/stajs/DnxPrebuild.Library/blob/master/src/DnxPrebuild.Library.ConsoleApp/Program.cs) that appends the current time to a log file.
- [`DnxPrebuild.Host`](https://github.com/stajs/DnxPrebuild.Host) - An even simpler console app that references `DnxPrebuild.Library.ConsoleApp.dll`.

Host `project.json`:
```
"commands": {
	"prebuild-host": "DnxPrebuild.Host.ConsoleApp",
	"prebuild-library": "DnxPrebuild.Library.ConsoleApp"
},

"scripts": {
	"prebuild": [ "dnx prebuild-library" ]
}
```

When building from the command line, the `prebuild` script is run:

![image](https://cloud.githubusercontent.com/assets/2253814/11394208/8a65497e-93c8-11e5-857b-5f6ee2a87283.png)

From inside Visual Studio 2015, a Build or Rebuild doesn't run the script:

![image](https://cloud.githubusercontent.com/assets/2253814/11394264/dd483a3e-93c8-11e5-8ab5-a9f9f19d6438.png)

... unless (as @davidfowl points out) you produce outputs:

![image](https://cloud.githubusercontent.com/assets/2253814/11394282/f096a800-93c8-11e5-8b62-03d80cfb1b0e.png)

![image](https://cloud.githubusercontent.com/assets/2253814/11394338/4471d1a2-93c9-11e5-94d1-ac2744f77d84.png)

I guess the difference is VS now pipes the build through `dnu`.

**Comment by johnnyreilly** [comment] 2016-01-08 12:37
I've just found this - it's a shame it's not better documented (I'll try and raise a docs PR).

By the way, in my own usage I've noticed the `prebuild` event being raised twice when I build in VS.  Is that right?

**Comment by moozzyk** [comment] 2016-01-08 17:34
@johnnyreilly - prebuild and postbuild scripts are run for each configuration and each target framework. If you are building just Debug for both dnxcore50 and dnx451 than prebuild script will be invoked twice. 
In the pre/post build script command the following build parameters are expanded: 
`%build:Configuration%` `%build:TargetFramework%`.

You can find some information on this in this [announcement](http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx) - in the Running scripts before and after building and creating packages section.

**Comment by johnnyreilly** [comment] 2016-01-08 18:34
Thanks for the clarification - that makes sense.

**Closed** 2017-02-19 08:53 UTC
