### ISSUE TITLE
System.NullReferenceException on Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Query

### ISSUE THREAD

**Issue by MatthewLymer** [aspnet/Home#3219] opened 2018-06-12 21:19 UTC
Operating System: Ubuntu 16.04

dotnet --info

    Host (useful for support):
      Version: 2.1.0
      Commit:  caa7b7e2ba

    .NET Core SDKs installed:
      No SDKs were found.

    .NET Core runtimes installed:
      Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

    To install additional .NET Core runtimes or SDKs:
      https://aka.ms/dotnet-download

Dependencies:

    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="JetBrains.Annotations" Version="11.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Redis" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Net.Http.Server" Version="1.1.2" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="1.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="7.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.2" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.0" />

Exception:

    System.NullReferenceException

Stack Trace:

	   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Query()
	   at Microsoft.AspNetCore.Mvc.ModelBinding.QueryStringValueProviderFactory.CreateValueProviderAsync(ValueProviderFactoryContext context)
	   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList``1 factories)
	   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ControllerContext controllerContext)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind0>d.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
	   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
	   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
	   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
	   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()

**Comment by Tratcher** [comment] 2018-06-12 21:27
Request url? Route definitions? Action signature?

**Comment by MatthewLymer** [comment] 2018-06-12 21:39
[HttpPost]
        [Route("Search")]
        public async Task<IActionResult> PostAsync([FromBody] SearchRequest request)
        {
        }

    public sealed class SearchRequest
    {
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; } 

        [JsonProperty(PropertyName = "SessionId")]
        public string SessionId { get; set; }

        [JsonProperty(PropertyName = "Tags")]
        public IDictionary<string,string> Tags { get; set; }

        [JsonProperty(PropertyName = "SearchField")]
        public string Search { get; set; }
    }

The request was a `POST /search HTTP/1.1`.

**Comment by Tratcher** [comment] 2018-06-12 21:46
Side note: symptoms like this are most commonly caused by concurrently accessing the HttpContext on multiple threads. I don't see any other obvious signs of that in the call stack or code, but keep an eye out for it.

How consistent is the error? Every request?

**Comment by MatthewLymer** [comment] 2018-06-12 21:50
In ~54,000 requests, it has happened ~20 times.

It looks to coincide to including authorization to my API, so I'll try and deduce from that whether it is related.  I'm implementing `AuthenticationHandler<T>` and it's using `Request.Headers` and `Response.Headers`, not the query string specifically though.

**Comment by MatthewLymer** [comment] 2018-06-12 22:22
I did a redeploy without authentication middleware and the issue disappeared.

**Comment by Eilon** [comment] 2018-07-11 16:31
@MatthewLymer were you able to make any progress on this? Do you have any new information?

What @Tratcher said is pretty much always the case: some code somewhere is incorrectly holding onto an HttpContext and using it from the wrong thread or concurrently, neither of which is supported.

**Comment by Eilon** [comment] 2018-07-13 16:38
Previous report that ended up with no firm conclusion: https://github.com/aspnet/Home/issues/2806

**Comment by allevyMS** [comment] 2018-07-13 18:10
I am also hitting this issue, I access the HttpContext in my authorization handlers, in an action filter OnActionExecuted and in the controller method itself. I am not using the HttpContextAccessor. I assume my usage should not be concurrent?

**Comment by Eilon** [comment] 2018-07-13 18:15
@allevyMS - can you share some relevant snippets of your code so we can take a look? Unfortunately with these kinds of issues it's really hard to diagnose without the details.

**Comment by srmorin** [comment] 2018-07-13 18:59
We see this issue too.  For us, it occurs infrequently but when it does, it always occurs in the middleware processing when trying to set the user from the claims principal in the request:

"message": "Object reference not set to an instance of an object.",
"stackTrace": " 
   at Microsoft.AspNetCore.Http.DefaultHttpContext.set_User(ClaimsPrincipal value)\n 
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n 
   at Common.Logging.Middleware.ManageLoggingContext.Invoke(HttpContext context)\n

**Comment by Eilon** [comment] 2018-07-13 20:54
@srmorin does any other code in your app hold onto the HttpContext (or related object) and potentially access it from another thread?

**Comment by srmorin** [comment] 2018-07-16 14:07
Yes.  We use some information from the HttpContext in our log messages, and we get this in the Invoke method in the AspDotNet core middleware.

________________________________

**Comment by davidfowl** [comment] 2018-07-16 15:20
Can you be more specific? Are you storing the http context somewhere?

**Comment by srmorin** [comment] 2018-07-16 15:42
Yes, we store specific information from the HttpContext into a separate data structure that is used when the request is complete.  We primarily pull this information from the Request property and store it in a separate structure and call Invoke().  At the conclusion of the call, we write out this information by calling the API to our logging infrastructure.


________________________________

**Comment by Tratcher** [comment] 2018-07-16 15:52
Can you share that method? It's possible you're capturing something that's not safe to access after the request completes.

**Comment by allevyMS** [comment] 2018-07-17 22:11
@Tratcher question, does the httpcontext need to be modified in a separate thread or simply accessed for this error to appear? If I have the httpcontext already available through one of the various context objects in asp net core, is it safe to use it? Should this issue only appear when using the HttpContextAccessor?

**Comment by davidfowl** [comment] 2018-07-18 03:34
It’s likely a problem caused by accessing the HttpContext in telemetry initlializers. It’s pretty fundamentally broken as those run when the App insights pipeline writes any data (from any thread). The “fix” that the app insights team have used in the past is to lock on the http context object. When trying to access it inside of the telemetry initializer.

**Comment by allevyMS** [comment] 2018-07-18 17:17
This is the entire Initialize snippet:

        public void Initialize(ITelemetry telemetry)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            var headers = httpContext?.Request?.Headers;

            if (headers == null)
            {
                return;
            }

            if (headers.ContainsKey(_client_ip_header))
            {
                var headerValue = headers[_client_ip_header];
                if (!string.IsNullOrWhiteSpace(headerValue))
                {
                    telemetry.Context.Location.Ip = headerValue;
                }
            }
        }

**Comment by allevyMS** [comment] 2018-07-18 17:38
I really appreciate the input here @davidfowl 

So this is a plausible cause if I understand you correctly:

The initialize may happen on multiple threads, if it happens after an outbound call (which happens as part of handling the request - which we have many) we may hit this null reference exception?

What is the significance of the outbound call that breaks it?

**Comment by davidfowl** [comment] 2018-07-18 19:33
> The initialize may happen on multiple threads, if it happens after an outbound call (which happens as part of handling the request - which we have many) we may hit this null reference exception?

That's correct.

> What is the significance of the outbound call that breaks it?

The thread you return to is a random thread pool thread. 

Here's the type of code that would cause that:

```C#
using Microsoft.Extensions.Logging;

namespace Talk1Samples
{
    public class ParallelAccessController : Controller
    {
        private readonly ILogger<ParallelAccessController> _logger;

        public ParallelAccessController(ILogger<ParallelAccessController> logger)
        {
            _logger = logger;
        }

        [Route("/parallel")]
        public async Task<string> ParallelAccess()
        {
            var task1 = GetAsync("www.google.com");
            var task2 = GetAsync("www.bing.com");

            await Task.WhenAll(task1, task2);

            return "Hello World";
        }

        private async Task GetAsync(string url)
        {
            try
            {
                _logger.LogInformation("Before {url}:{contenttype}", url, Request.ContentType);

                await Task.Delay(100);
            }
            finally
            {
                _logger.LogInformation("After {url}:{contenttype}", url, Request.ContentType);
            }
        }
    }
}
```

PS: We gave a talk on this at NDC London https://vimeo.com/254635669. It shows this specific example and how it can crash and burn 😄.

**Comment by MatthewLymer** [comment] 2018-07-19 14:04
@Eilon 
I updated my code to pass in a `NullLoggerFactory.Instance` to the `AuthenticationHandler` constructor, this resolved the problem for me.  I looked at my logger providers, but I don't see any of them using `IHttpContextAccessor`, though they're 3rd party providers, so I can't be certain.

**Comment by allevyMS** [comment] 2018-07-23 23:20
@davidfowl Disabling the App Insights instrumentation (and thus the use of httpcontext accessor from the ITelemetryInitializer) solved the null reference. Thank you!

**Comment by Eilon** [comment] 2018-08-28 22:31
Closing because it does not appear there is any further action required for ASP.NET Core.

**Closed by Eilon** 2018-08-28 22:31 UTC

**Comment by davidfowl** [comment] 2022-06-05 20:25
This is a dupe of https://github.com/microsoft/ApplicationInsights-dotnet/issues/1524. See if [this guide](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1524#issuecomment-1146848272) helps to capture a process dump.
