### ISSUE TITLE
Slow response time (~6s) for post requests with empty body

### ISSUE THREAD

**Issue by omerlh** [aspnet/Home#2878] opened 2018-02-15 07:08 UTC
While working on .NET Core ASP.Net web API project, I've noticed that sending a specific request will always result in 418 timeout response after ~6s. This is the request:
```
POST /api/values HTTP/1.1
Accept: */*
Proxy-Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Host: localhost:5000
```
And this is the response:
```
HTTP/1.1 408 Request Timeout
Connection: close
Date: Tue, 13 Feb 2018 18:46:59 GMT
Server: Kestrel
Content-Length: 0
```
I was able to reproduce it on empty web API generated with the CLI using:
```
dotnet new webapi
```
I've also created [sample repo](https://github.com/omerlh/dotnet-webapi-demo) using this CLI command with docker image to make it easy to reproduce the issue. Just clone the repo, and run:
```
docker build -t demo .
docker run -it -p 5000:80 demo
```
And than use curl to send this request to `http://localhost:5000`.

**Comment by halter73** [comment] 2018-02-15 19:46
Can you show us the curl command you used to send the request. It looks like the POST request is missing a body. My guess is there is a timeout reading the body. It makes sense that it would take ~6s to timeout since Kestrel doesn't enforce its default 240 bytes/second [MinRequestBodyDataRate](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.minrequestbodydatarate?view=aspnetcore-2.0) until a 5 second grace period completes.


If you collect information-level logs, I expect you'll see a message like "Connection id {ConnectionId}, Request id {TraceIdentifier}: the request timed out because it was not sent by the client at a minimum of 240 bytes/second."

**Comment by omerlh** [comment] 2018-02-18 04:34
Yep, I'm sending the request with an empty body. When sending the same request with an empty body, without `Transfer-Encoding: chunked`, it does not reproduce. Also adding `Content-Length` does not have a similar effect. 
I've suspected this is some sort of timeout, but I still think it might be worth fixing it.

**Comment by Eilon** [comment] 2018-02-18 23:35
If the request is chunked or no content-length, this sounds exactly like what @halter73 is saying. Kestrel is waiting for the body, but the body isn't being sent.

If you can share exact steps to reproduce this problem we can dig in further.

**Comment by omerlh** [comment] 2018-02-19 05:47
Yes, that what I've suspected happens. To reproduce, you can follow the steps I've specified in the issue - clone the repo, build and run the docker image. Then use any tool to send the HTTP request (I've used Zaproxy/JMeter to test it). If you need further help reproducing it, let me know and I'll share more info.

**Comment by Eilon** [comment] 2018-02-20 18:16
If it's just Kestrel's timeout, then this is by-design behavior, so closing this issue.

**Closed by Eilon** 2018-02-20 18:16 UTC
