### ISSUE TITLE
Nugget Package Restore failed in Build

### ISSUE THREAD

**Issue by ranouf** [aspnet/Home#2163] opened 2017-08-24 20:55 UTC
Hi, 

I have a VSTS where a User a Build Definition.
Before, with Asp.Net Core 1.0, the step "Nugget Restore" worked correctly.
But now with Asp.Net Core 2.0, it failed:
Here is the log:
```
2017-08-24T20:44:52.7915569Z Errors in d:\a\1\s\MyAppBackend.Core\MyAppBackend.Core.csproj
2017-08-24T20:44:52.7925572Z     Package Microsoft.Extensions.Options 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Options 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     Package Microsoft.EntityFrameworkCore 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     One or more packages are incompatible with .NETCoreApp,Version=v2.0.
2017-08-24T20:44:52.7925572Z 
2017-08-24T20:44:52.7925572Z Errors in d:\a\1\s\MyAppBackend.Infrastructure\MyAppBackend.Infrastructure.csproj
2017-08-24T20:44:52.7925572Z     Package Microsoft.EntityFrameworkCore 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     Package Microsoft.EntityFrameworkCore.Tools 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.Tools 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     Package Microsoft.Extensions.Localization 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Localization 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     Package Microsoft.Extensions.Options 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Options 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     Package Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7925572Z     One or more packages are incompatible with .NETCoreApp,Version=v2.0.
2017-08-24T20:44:52.7925572Z 
2017-08-24T20:44:52.7925572Z Errors in d:\a\1\s\MyAppBackend.Api\MyAppBackend.Api.csproj
2017-08-24T20:44:52.7935568Z     Package AutoMapper.Extensions.Microsoft.DependencyInjection 3.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package AutoMapper.Extensions.Microsoft.DependencyInjection 3.0.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.Mvc 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Mvc 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.Extensions.Logging.Debug 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging.Debug 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.Authentication.JwtBearer 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Authentication.JwtBearer 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.Extensions.Options 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Options 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.StaticFiles 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.StaticFiles 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.Rewrite 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Rewrite 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.EntityFrameworkCore 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.Extensions.Localization 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Localization 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.EntityFrameworkCore.Tools 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.Tools 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     One or more packages are incompatible with .NETCoreApp,Version=v2.0.
2017-08-24T20:44:52.7935568Z 
2017-08-24T20:44:52.7935568Z Errors in d:\a\1\s\MyAppBackend.Tests\MyAppBackend.Tests.csproj
2017-08-24T20:44:52.7935568Z     Package Microsoft.Extensions.Configuration 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.EntityFrameworkCore.InMemory 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.InMemory 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.TestHost 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.TestHost 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package AutoMapper.Extensions.Microsoft.DependencyInjection 3.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package AutoMapper.Extensions.Microsoft.DependencyInjection 3.0.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.Authentication.JwtBearer 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Authentication.JwtBearer 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.Mvc 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Mvc 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.Rewrite 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Rewrite 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.AspNetCore.StaticFiles 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.StaticFiles 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.EntityFrameworkCore 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.Extensions.Logging.Debug 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging.Debug 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7935568Z     Package Microsoft.Extensions.Options 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Options 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7945571Z     Package Microsoft.EntityFrameworkCore.Tools 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.Tools 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7945571Z     Package Microsoft.Extensions.Localization 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Localization 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7945571Z     Package Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T20:44:52.7945571Z     One or more packages are incompatible with .NETCoreApp,Version=v2.0.
2017-08-24T20:44:52.7945571Z 
```

It s hard to believe that EF Core 2.0 is not compatible to .Net Core 2.0 ...
`Package Microsoft.EntityFrameworkCore 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)`

My guess, there is something missing in my azure server configuration.

What do you suggest to fix the problem?

**Comment by nukefusion** [comment] 2017-10-06 08:31
When building for core 2.0 ensure you are using nuget >=4.3.0.

**Comment by Eilon** [comment] 2018-07-10 17:00
Hi. We're closing this issue as we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by Eilon** 2018-07-10 17:00 UTC
