### ISSUE TITLE
Drastic network io performance degradation in Docker

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Home#3371] opened 2018-07-30 17:00 UTC
_From @itrofimow on July 16, 2018 15:10_

Hi.

We've dockerized one of our apps recently and everything seemed to be fine except we just couldn't make it pass load test. Symptoms seem pretty strange to me, later about them. However after 'full desperado mode' took over we tried to run it on host machine with just dotnet binaries (no dotnet installed) and test passed with ease.

The app itself is simple fully async .NetCore 2.1.0 CRUD Web Api with network related work mostly - it communicates with mongodb, rabbitmq and a couple of WCF services and that's it.

So symptoms that are 100% reproducible under load: 
any request takes enormous amount of time to complete, as simple as this controller is:
```
        [HttpGet]
        [Route("test2")]
        public async Task<string> Test2()
        {
            return "Ok";
        }
``` 
after hitting some load rate(~50% ) the time for completion grows linearly and shortly after takes >1m so 504 from Nginx. However our logging shows that processing of the whole request pipeline takes ~3ms, so we inspected what actually happens with tcpdump:
0.00 - packet with that Get received
~2.00 - processing started (according to app logs)
~2.00 - processing finished (according to app logs)
~4.00 - packet with 'Ok' sent.
(these timings are just after completion time starts to grow up)
So we thought this is Kestrel related and these 2s + 2s are wasted somewhere in there, but second test contoller came in:
```
        private readonly HttpClient _client = new HttpClient();

        [HttpGet]
        public async Task<string> Test()
        {
            _logger.LogInformation("starting test async io");
            var response = await _client.GetAsync("http://<some intranet url that just returns static ~40 bytes string in no time>");
            var result = await response.Content.ReadAsStringAsync();
            _logger.LogInformation("finished test async io");

            return result;
        }
```
and there's ~2s between first and second log entries(and it behaves same as in test 1 - delay before and after processing). Tcpdump shows that response from url comes almost immediately after request packet has been sent, as expected.

There's absolutely no ThreadPool starvation, as number of threads is ~50 and minThreads is set to (1024, 1024) anyways. 
I believe there's no network issues neither with host or container itself.

What we tried:
1. We tried .netCore 2.0.0, .netCore 2.1.0, .netCore 2.1.0 with UseLibuv
2. Alpine, Debian and Ubuntu base images
3. --net=host
4. perfcollect, but couldnt figure out the bottleneck

Host os information:
```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```
```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
Stepping:              1
CPU MHz:               2593.993
BogoMIPS:              5187.98
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm rdseed adx smap xsaveopt arat
```
Docker info:
```
sudo docker info
Containers: xxx
 Running: xxx
 Paused: xxx
 Stopped: xxx
Images: xxx
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796GiB
Name: xxxxxxxx
ID: 7IDX:SAWS:SUKX:MJW5:RNDJ:TVCR:PZ2S:V2GB:KWPF:ZEGU:MLPV:KU6C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTPS Proxy: xxxxxxxx
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
Dockerfile:
```
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR src

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY src ./

RUN dotnet restore xxx.sln -s https://api.nuget.org/v3/index.json --packages /nuget/packages

RUN dotnet build xxx.sln -c Release --no-restore

RUN dotnet publish xxx.Web -c Release -o ../published/Web --no-restore

FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

FROM base AS production
WORKDIR /app
COPY --from=build-env ./src/published/Web ./

RUN  apt-get update -y && \
     apt-get upgrade -y && \
     apt-get dist-upgrade -y && \
	 apt-get install -y net-tools && \
	 apt-get install -y procps && \
	 apt-get install -y tcpdump

ENTRYPOINT ["dotnet", "xxx.Web.dll"]
```
I can provide any necessary debug information/traces/dumps

P.S. Again i'd like to point out that it's not just some 'user code' failing, everything is ok on the host machine, but **not** in docker.

_Copied from original issue: dotnet/corefx#31094_

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @karelz on July 16, 2018 18:26_

Are you able to reproduce the problem without ASP.NET? Just console app, using `HttpClient`?
That will help us narrow down if the problem is in HttpClient or in the server (or combo).

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @karelz on July 16, 2018 18:27_

Also, do you have a simple isolated repro that anyone can run anywhere?

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @itrofimow on July 18, 2018 8:42_

I am not able to reproduce it without load, so i don't quite get how one could repro it without ASP.NET. Moreover, i feel like it's not HttpClient related - it's usage was just for confirmation of issue not being related to just Kestrel(however it might be combo).

Well, i dont have repro for now - i believe it would take like a couple of days to build it. So i guess we should come back to this after repro is ready, right?

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @karelz on July 18, 2018 9:11_

You can generate load from Main (e.g. kick off 1000 threads doing the same thing in a loop), you don't need ASP.NET server for it.
Without repro / perf investigation it is not actionable. Let's close it for now. Once you have more, we can reopen.

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @itrofimow on July 23, 2018 14:4_

Hi. I've built a repro finally, how do i share it with you? Mind if i send it via email?

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @itrofimow on July 24, 2018 15:48_

@karelz

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @danmosemsft on July 24, 2018 16:36_

cc @davidsh since @karelz is out.

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @davidsh on July 24, 2018 16:51_

>Hi. I've built a repro finally, how do i share it with you? Mind if i send it via email?

@itrofimow 

Can you share the repro via Gist or a small repo under your GitHub account?

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @itrofimow on July 24, 2018 19:33_

Ok, if Github repo is more suitable for you i'll do it that way as soon as i get back to work.

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @itrofimow on July 25, 2018 11:9_

Well it's ready.
https://github.com/itrofimow/PerformanceDegradationRepro
Feel free to contact me if there would be any issues with setup or smth - i am eager to help

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @itrofimow on July 30, 2018 8:29_

@davidsh Hi. Could you take a look on this?

If setup seems cumbersome or you wouldn't be able to reproduce the issue i might build it up on Azure and give these vm-s away

**Comment by Tratcher** [comment] 2018-07-30 17:00
_From @davidsh on July 30, 2018 16:45_

cc: @Tratcher This repro involves a lot of ASP.NET code. Perhaps this issue should be investigated there.

**Comment by Tratcher** [comment] 2018-07-30 17:01
@sebastienros can you make some initial suggestions?

**Comment by sebastienros** [comment] 2018-07-30 17:57
There is an obvious mistake that could explain this, https://github.com/itrofimow/PerformanceDegradationRepro/blob/master/ProjectUnderInvestigation/src/GithubIssueRepro.Web/Controllers/TestController.cs#L14

`HttpClient` instances need to be reuse. So either declare this one as `static` or use `HttpClientFactory` which is new in 2.1.

I'll wait for you to try this before continuing the investigation.

**Comment by itrofimow** [comment] 2018-07-30 18:02
Yea, i know about that - this method as well as the whole controller was implemented just for testing purposes, its not under any load aside me curl-ing it like once in 30 secs or so.

**Comment by sebastienros** [comment] 2018-07-30 18:07
Thanks. Next in line then, you are using `FROM microsoft/dotnet:2.1-sdk` which will actually resolve `2.1.1`. I know the corefx team has flagged a perf issue on this specific release for Linux and has recommended users to go back to 2.1. Could you try by specifying `2.1.0` explicitly ?

**Comment by itrofimow** [comment] 2018-07-30 18:13
Hm, i didnt know about that.
However, as i mentioned in the issue, 
1. everything seems ok on bare linux
2. We tried 2.0 as well as running on Ubuntu 16.04 base image with just binaries from here https://www.microsoft.com/net/download copied inside container (and this is as close to our linux setup as we could get) - same story.

I definitely can try what you suggested and i will tomorrow, but i feel like it's not the case

**Comment by itrofimow** [comment] 2018-07-31 13:57
I checked what version of sdk is resolved via FROM microsoft/dotnet:2.1-sdk with ```dotnet --version``` and it's 2.1.302 actually

**Comment by sebastienros** [comment] 2018-07-31 17:17
Exactly:
- 2.1.302 sdk comes with runtime 2.1.2
- 2.1.301 sdk comes with runtime 2.1.1
- 2.1.300 sdk comes with runtime 2.1.0

So what I am asking is that you to try using `microsoft/dotnet:2.1.300-sdk` in your docker file, just to eliminate a known issue with the `2.1.1` and greater runtime

**Comment by itrofimow** [comment] 2018-08-02 04:59
I finally managed to try it on Azure, and, well, i couldn't reproduce it even at significantly higher load.
So this can be closed and i am sorry for inconvenience :(

However it would be really nice of you if you could suggest what can be that much wrong with my docker setup, if it leads to such a noticeable performance degradation.

**Comment by sebastienros** [comment] 2018-08-02 16:44
What OSes did you try it on, both locally and on Azure? If they are not the same then it might be an explanation that would need to be checked.

**Comment by itrofimow** [comment] 2018-08-03 09:47
Both OS-es are Ubuntu 16.04
Docker version is 17.12.0-ce locally vs 18.03.1-ce on Azure
Hypervisors might be different, but i have no control over it

**Comment by itrofimow** [comment] 2018-08-11 15:45
I've investigated some more with perfcollect and noticed there is a LOT of finalized Sockets and NetworkStreams, so i took a closer look at my implementation of wcf calls and realized i create new client, which is inretered from System.ServiceModel.ClientBase<T> at every call. 

And as in this issue(https://github.com/dotnet/wcf/issues/2161) is explained wcf implementation in .net core uses underlying HttpClient, so i guess i am creating and disposing LOTS of HttpClients internally and that hurts performance, memory usage, network capabilities etc. so this might be the root case of my issues (however i still have no explanation of why everything is ok on bare Linux)

I replaced WCF calls with plain HttpClient usage and, well, everything is ok now.

**Comment by sebastienros** [comment] 2018-08-11 16:05
Thanks for letting us know about this. This is good to know for next time someone faces the same issue. And yes HttpClient usage seems to be the root of lots of memory concerns. Fortunately the new pattern in 2.1 will help resolve most of these.

**Closed by sebastienros** 2018-08-11 16:05 UTC
Labels: needs more info, tenet-performance

**Comment by yuuhhe** [comment] 2019-01-17 03:34
have same problem, any news ?

**Comment by itrofimow** [comment] 2019-01-17 03:56
We couldn't make it work and just abandoned further investigations. However we tend to believe this is wcf related.

I'd suggest following lldb part of this https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md as we didn't try it back then and `dumpheap` might point to the issue.
