### ISSUE TITLE
"web" profile does not read Environment Variables from launchSettings.json

### ISSUE THREAD

**Issue by kcd83** [aspnet/Home#1431] opened 2016-05-09 23:39 UTC
There seems to be something different about the "web" profile (loaded from the `project.json` "commands" maybe?) and the Environment Variables are not working correctly. 

If I add Environment Variables via the project Properties they get added to `launchSettings.json` and work as expected until I close Visual Studio. If reopen the project these are not read back, they do not show in the Properties UI nor are they applied when running the project.

![image](https://cloud.githubusercontent.com/assets/707312/15131119/64feffa2-16a1-11e6-931e-c4658f367050.png)

`launchSettings.json`

``` javascript
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:54929/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ServiceOptions:MongoConnection": "mongodb://10.0.0.50:27017",
        "Hosting:Environment": "Development",
        "ServiceOptions:RabbitConnection": "amqp://10.0.0.50"
      }
    },
    "web": {
      "commandName": "web",
      "environmentVariables": {
        "ServiceOptions:MongoConnection": "mongodb://10.0.0.50:27017",
        "Hosting:Environment": "Development",
        "ServiceOptions:RabbitConnection": "amqp://10.0.0.50"
      }
    },
    "testing": {
      "commandName": "web",
      "environmentVariables": {
        "ServiceOptions:MongoConnection": "mongodb://10.0.0.50:27017",
        "Hosting:Environment": "Development",
        "ServiceOptions:RabbitConnection": "amqp://10.0.0.50"
      }
    }
  }
}
```

Interesting points:
- testing and IIS Express work as expected
- If I rename the "web" profile ("kestrel") it works as expected _however_ there will still be a "web" which still only shows `Hosting:Environment`

My thinking is there may be some merging of `project.json` commands with profiles that is misbehaving, just a guess, is it the "web" - "web" name clash?

Workaround is to simply rename the "web" profile to "kestrel" in `launchSettings.json`  and use that.

**Comment by Tratcher** [comment] 2016-05-13 23:27
Duplicate of https://github.com/aspnet/Tooling/issues/354, fixed in RC2.

**Comment by jcbikes** [comment] 2016-05-20 03:15
Actually, http://localhost:5000 seems to be hard coded in launchSettings.json now. Changing it, and then re-running has no effect.

**Comment by Tratcher** [comment] 2016-05-20 17:59
@jcbikes what do your modified launch settings look like? I suspect you're seeing a different issue: https://github.com/aspnet/Announcements/issues/174

**Comment by aspnet-hello** [comment] 2017-12-31 05:35
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2017-12-31 05:35 UTC
