### ISSUE TITLE
IHostedService can't be resolved

### ISSUE THREAD

**Issue by ygoe** [aspnet/Home#3374] opened 2018-08-01 08:16 UTC
Running a background service in an ASP.NET Core application requires registering it with the DI container as IHostedService. This ensures that the service is properly shut down when the host terminates.

While this works well for the service itself, it's absolutely unusable for dependency injection, which should be the main purpose of DI. When resolving a service, I need to ask for the interface type. When I have three background services, resolving IHostedService doesn't work because I can't specify which of the services I need. Resolving the implementation type doesn't work either because it won't find it.

    services.AddSingleton<IHostedService, MyService>();
    services.AddSingleton<IHostedService, MyOtherService>();

Registering the implementation type alone also doesn't work because the IHostedService methods StartAsync and StopAsync are no longer called.

    services.AddSingleton<MyService>();

The only thing that works is using a helper class and making two registrations, as described here: https://stackoverflow.com/a/51584615/143684

So I feel this DI use for IHostedService is broken design. Registering an implementation type by the IHostedService isn't dependency injection, it's misuse for a different purpose, which is not dependency resolving but host lifetime management. There should be another way to write this.

**Comment by Tratcher** [comment] 2018-08-01 13:34
Related discussion: https://github.com/aspnet/Hosting/issues/1489

**Comment by Eilon** [comment] 2018-08-01 18:57
@Tratcher should we move this to the Hosting repo?

**Comment by Tratcher** [comment] 2018-08-01 20:18
It's largely a duplicate of the linked issue.

**Comment by davidfowl** [comment] 2018-08-08 05:58
Closing as dupe

**Closed** 2018-08-08 05:58 UTC
