### ISSUE TITLE
publish asp.net core in IIS error 404

### ISSUE THREAD

**Issue by Alberttg77** [aspnet/Home#1809] opened 2016-11-04 13:37 UTC
Hi,
If deploy my aplication in IIS inside Default Web SIite I always get an 404 error when it tray to acces all css and js files.

![image](https://cloud.githubusercontent.com/assets/2923353/20007317/f17dda8a-a29b-11e6-970a-fa1d2b1e3637.png)

But if I deploy it in a new website only for this app it works fine.

Where's the problem?

**Comment by xtt129** [comment] 2016-11-14 17:06
It's about the relative path to the resource files in you html/cshtml file.

**Comment by pritambaldota** [comment] 2016-11-14 19:54
@Alberttg77 Did you deployed to a Default IIS Website or Under Application inside Default IIS Web site? Looking at the Network trace, it looks like you have deployed to Root of IIS website, but while accessing web resources you are using **/test/** after host name. 

Can you share the IIS directory structure of your app and master page or other view snippet where you references your CSS, JS and other assets?

**Comment by Alberttg77** [comment] 2016-11-15 06:40
hi again I'll to expose it better:

I've an web app calling CompassXdSS, i've deployed it in my server in C:\CompassXdSS

Now in IIS under the default web site i've created a new application
![image](https://cloud.githubusercontent.com/assets/2923353/20295547/f43148bc-ab05-11e6-8c0f-c97f3c59b455.png)

When I run it it's doesn't work, because is trying to get all the resources under http://localhost instead of http://localhost/CompassXdSS

![image](https://cloud.githubusercontent.com/assets/2923353/20295621/5d78d588-ab06-11e6-8c19-2f3a805071b2.png)

In order to make it work I've created a new web site, without any application inside, and it works:

![image](https://cloud.githubusercontent.com/assets/2923353/20295678/9c84ea64-ab06-11e6-84b5-42c4cdf163cd.png)

![image](https://cloud.githubusercontent.com/assets/2923353/20295700/c3eb0f16-ab06-11e6-959b-78769b9ea176.png)

Why is not working under default web site?

**Comment by pritambaldota** [comment] 2016-11-15 08:40
@Alberttg77 I think you are not deploying websites at correct location. I tried to deploy the sample website under Default Web Site/MyApp using Web Deploy Tool for IIS. By this way I can see the website without any issues. See the attached screen shot -

![image](https://cloud.githubusercontent.com/assets/6270238/20298410/9d222086-aaca-11e6-880b-a61a492a7862.png)

See my Application Structure in IIS -
![image](https://cloud.githubusercontent.com/assets/6270238/20298457/d2efe8d8-aaca-11e6-93ff-8ecd65aecce1.png)

I have created Web deploy Package from Visual Studio and Imported the same Package as Application into IIS default website. See the detailed steps below -
![image](https://cloud.githubusercontent.com/assets/6270238/20298626/bcab57b4-aacb-11e6-9412-6529c8b28a58.png)

![image](https://cloud.githubusercontent.com/assets/6270238/20298630/cb131b16-aacb-11e6-90f2-6a0be8b7ab17.png)

![image](https://cloud.githubusercontent.com/assets/6270238/20298636/d57eec4c-aacb-11e6-89d2-a9ee1b8091f8.png)

![image](https://cloud.githubusercontent.com/assets/6270238/20298639/da9fec76-aacb-11e6-9b2f-2c091a039db2.png)

![image](https://cloud.githubusercontent.com/assets/6270238/20298640/dfcdf008-aacb-11e6-9202-9188ee6a3a02.png)

![image](https://cloud.githubusercontent.com/assets/6270238/20298643/e3d74d34-aacb-11e6-8123-4bbd477cbb64.png)

![image](https://cloud.githubusercontent.com/assets/6270238/20298650/e9382b0e-aacb-11e6-9db5-39a93c47af91.png)

Hope this help.

**Comment by Alberttg77** [comment] 2016-11-15 09:47
@pritambaldota i've done this but now I'm getting a 500 internal server error
![image](https://cloud.githubusercontent.com/assets/2923353/20300760/dba251ea-ab20-11e6-9577-3e8e59a8ad0d.png)

**Comment by Tratcher** [comment] 2016-11-15 18:04
@Alberttg77 your app is crashing on startup. See the common errors section of this doc (https://docs.microsoft.com/en-us/aspnet/core/publishing/iis) for instructions to turn on logging.

**Comment by Alberttg77** [comment] 2016-11-16 09:30
hi @Tratcher I've solved the 500 error thanks
@pritambaldota the problem persists, when it loads the page It's allways refering to localhost without the app name
![image](https://cloud.githubusercontent.com/assets/2923353/20341717/a3722454-abe7-11e6-9c75-9a700f13b97a.png)

**Comment by pranaliSalwatkar** [comment] 2016-11-16 10:44
Try this [](http://stackoverflow.com/questions/9703090/http-404-page-not-found-in-web-api-hosted-in-iis-7-5). You need to modify web.config file.

**Comment by pranaliSalwatkar** [comment] 2016-11-16 10:45
Try the [link](http://stackoverflow.com/questions/9703090/http-404-page-not-found-in-web-api-hosted-in-iis-7-5). As suggest in this post, please update the web.config file to get access of files.

**Comment by Alberttg77** [comment] 2016-11-16 11:05
hi @pranaliSalwatkar I already have all the verbs in my web.config

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\CompassXdSS.exe" arguments="" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
        <directoryBrowse enabled="true" />
  </system.webServer>
</configuration>
`

**Comment by pritambaldota** [comment] 2016-11-17 00:46
@Alberttg77 You might not be deploying to correct app. Can you share your deployment steps and app sample?

**Comment by Alberttg77** [comment] 2016-11-17 06:06
@pritambaldota my deployment steps are the same as yours. Googling I've found some links talking about the same issuem but I'm not able to solve it in my case:
http://www.devsplanet.com/question/35550567
http://www.damirscorner.com/blog/posts/20160214-DeployingAspNetCoreRc1ApplicationToIis.html
http://stackoverflow.com/questions/36460967/asp-net-core-404-error-when-published-to-iis-7-5

**Comment by GuardRex** [comment] 2016-11-17 10:10
@Alberttg77 Can you put up a small GH repro that demos your static file serving problem? Since the app runs but static files are not served, this looks like a static file middleware issue or the static files are not being deployed with the app. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files

**Comment by timmy-wong** [comment] 2016-11-30 21:28
I'm having the same problem as Alberttg77.  I have a web api service that was built using .NET Core RC1.  It worked great.  In IIS, it was hosted as an application under "Default Web Site" along with other non-Core apps to the MyApp\wwwroot folder.

After upgrade to RTM, now, my app runs fine as a stand-alone app (c:\MyApp\MyApp.exe).  This would run on port 5000 and I can access it from my browser by (http://localhost:5000/MyApp).  

When hosting it in IIS, it would work if I create a web site for it (to exist alongside Default Web Site), using another port (81, for example).  Then, the web site would be pointed to c:\MyApp.  The, I can hit my app by using http://localhost:81/MyApp.  

However, my application needs to be hosted under Default Web Site as an application to run alongside other non-.NET Core applications (just like I had it when it was under RC1.)  So, when I create an application under Default Web Site named /MyApp and have it directed to folder c:\MyApp, and I access the site by hitting http://localhost/MyApp, I get a 404 error.  The app would seem like it was being accessed because the event log would register that the app was being accessed, but the resulting return code is 404.  

Any assistance would be greatly appreciated.  Thanks in advanced.

**Comment by GuardRex** [comment] 2016-11-30 22:04
@timmy-wong Is your Default Web Site an ASP.NET Core site with a `<handlers>` section in its `web.config`? If so, you shouldn't have the `<handlers>` section in the sub-app `web.config`.

The `<handlers>` section for `web.config` can only appear once for the root (parent) app, in this case your Default Web Site. As a sub-app (your `MyApp` app), you should only have the `<aspNetCore>` element in the sub-app's `web.config` file.

**Comment by timmy-wong** [comment] 2016-12-01 01:06
Hi @GuardRex.  Thanks for the reply!  Yes, I did explore the multiple handlers scenario.  The directory that the Default Web Site is mapped to didn't have a web.config, so I added one there so that I could move the <handlers> section to that level, and then leave the web.config for my subapp without a <handlers>.  That didn't work.  Because this sub-app was the only one on .NET Core (the other sub-apps are regular .NET apps running through the .NET 4.0 CLR), I removed the Default Web Site's web.config and left the <handlers> section only in my .NET Core web.config.

However I did find the issue to my problem after some more trial-and-error!  I still had some legacy RC1 code in my startup.cs where I had that RC1 work-around where my Configure method called the Configure1 method using the below line of code...

app.Map("/MyApplication", (app1) => this.Configure1(app1, env, loggerFactory));

This seemed to be the root cause for my IIS hosting issue after migrating to RTM.  Once I removed the Configure1 call and relocated that code to the Configure method, everything now works!  Phew! What a relief!

**Comment by GuardRex** [comment] 2016-12-01 01:08
> app.Map("/MyApplication", (app1) => this.Configure1(app1, env, loggerFactory));

Yes, right. I've seen the new guidance say that the prior workaround can be dropped now. Glad it had a happy ending. :smile:

**Comment by vincpa** [comment] 2017-04-07 10:55
@Alberttg77 I too was having the same problem. What I did was create a brand new app in Visual Studio, no custom code at all and deploy it to IIS. Worked first go.

Then I had to go back and figure out what the problem was in my app. Turned out I should have been using app.UseMvc() instead of app.UseMvcCore().

Try a new app without any changes and see how you go.

**Comment by harveytriana** [comment] 2017-10-04 02:58
A generic way to fix this is to use razor @Url.Content, por example:

 <link rel="icon" href="@Url.Content("~/favicon.ico?v=2")" />

**Comment by Eilon** [comment] 2018-04-03 16:08
Closing this issue because it isn't clear to me if there is an issue remaining. If you feel there's still an issue, please re-open this issue or log a new issue with complete details of the problem. Thanks!

**Closed by Eilon** 2018-04-03 16:08 UTC
