### ISSUE TITLE
Flaky test: TokensFiredForNewDirectoryContentsOnRename sometimes fails on Windows 10

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#3033] opened 2018-04-06 20:11 UTC
_From @jbagga on March 21, 2017 18:33_

[TokensFiredForNewDirectoryContentsOnRename](https://github.com/aspnet/FileSystem/blob/dev/test/Microsoft.Extensions.FileProviders.Physical.Tests/PhysicalFileProviderTests.cs#L1138) failed on the CI a few times in the past week.

cc @muratg 

_Copied from original issue: aspnet/FileSystem#263_

**Comment by Eilon** [comment] 2018-04-06 20:11
_From @ryanbrandenburg on April 6, 2018 18:15_

This is [still happening](http://aspnetci/viewLog.html?buildId=441190&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe#testNameId-7947063349423447523). Future instances of it can be seen [here](http://aspnetci/project.html?tab=testDetails&testNameId=-7947063349423447523&projectId=XPlat&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by natemcmaster** [comment] 2018-04-13 23:45
I'll take a look at this next week.

**Comment by natemcmaster** [comment] 2018-05-03 00:46
Hmm, I'm having trouble reproducing. I ran this test in a loop for a few hours and it didn't reproduce. I'm going to push some improvements to the assertions so we know which the many `Assert.True`'s is failing. It might be stress related, in which case, my awesome dev box is unlikely to find it unless I launch a few Electron apps.

**Comment by natemcmaster** [comment] 2018-05-08 23:12
I can't reproduce, and it hasn't failed on CI since at least Jan 23, 2018. Closing as no-repro.

**Closed by natemcmaster** 2018-05-08 23:12 UTC
Labels: repo:FileSystem, task
