### ISSUE TITLE
Response cahce does not work on Razor pages

### ISSUE THREAD

**Issue by cyrusel** [aspnet/Home#2176] opened 2017-09-01 08:11 UTC
I configured ResponseCache in configure and configure services sections and then put response cache attribute in a simple razor page before Page model class but it didn't work. Form method is "get" and no special feature has implemented to prevent response cache to work. 
Where should response cahce attribute be placed in razor pages? why it doesn't work? (asp.net core 2.0 final release)

Thanx

**Comment by Tratcher** [comment] 2017-09-01 12:16
Duplicate of https://github.com/aspnet/Mvc/issues/6747

**Closed by Tratcher** 2017-09-01 12:16 UTC
