### ISSUE TITLE
How to solve Update-Database issue when switching branch?

### ISSUE THREAD

**Issue by viveknuna** [aspnet/Home#2925] opened 2018-03-06 10:17 UTC
I have one entity which has a column as int in Branch **A**. Now I switch to a different Branch **B**. There I create a migration and change column to `varchar` and run `Update-Database`. Now If I switch to Branch **A** again. If I see in the code the column datatype is `int`, but in the database, its datatype is `varchar`. But I want its datatype to be `int`. I can not even remove this migration from Branch **A** because it was created in Branch **B**. I can see only one way to solve this issue is to delete the database and run `Update-Database`, But I will lose all data by doing this. Is there any better way to solve this issue.

I'm using entity framework core 2.0.1.

**Comment by ajcvickers** [comment] 2018-03-06 16:47
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/11164

**Closed by ajcvickers** 2018-03-06 16:47 UTC
