### ISSUE TITLE
Updating from ASP.NET Core 2.0 to 2.1 (net471) causes unstable Azure App Service

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Home#3389] opened 2018-08-06 11:55 UTC
I wasn't quite sure where to post this issue, so please feel free to move it to the correct area if this is not appropriate.

I have a production API application deployed to Azure App Services that has been stable and running without issue on ASP.NET Core 2.0.x with .NET Framework 4.7.1.

After updating the app to ASP.NET Core 2.1.2 (still with .NET Framework 4.7.1) and deploying to Azure things have become unstable. The application is running and is usable, however, CPU is spiking up and down and application response times are all over the charts. Reverting the update and re-deploying 2.0 causes things to go back to normal and stable.

Here are some charts from a period of this deployment:

**Application Response Times**

[![enter image description here][1]][1]

**CPU Percentage**

[![enter image description here][2]][2]

The only change in these deployments was updating the project libraries from 2.0 to 2.1 following the [migration from ASP.NET docs][3] and then reverting the upgrade back to 2.0. It should also be noted that these graphs show ASP.NET Core 2.1 in a period that is normally in low demand (middle of the night) and charts are usually at their lowest levels.

App Insights does not seem to point to a single endpoint as causing these issues. Distribution of slow/spiking response times seems uniform across the application.

I took a 5 minute performance profile from Kudu during the unstable 2.1 deployment. I am not really an expert at reading these things, but from one of the performance spikes I was able to see some significant sampling coming from `IISMiddleware` and `HostingApplication`.

![image](https://user-images.githubusercontent.com/1190944/43715043-20302406-994d-11e8-980c-bc1e65aa4c44.png)

I am not sure if this `.diagsession` file contains sensitive information or not, so I have not attached it publicly here. If someone from Microsoft would like me to send it over, please let me know and I will be glad to.

After trying to debug this more, I decided to deploy using `netcoreapp2.1` rather than `net471` to see of that would change anything. After deploying ASP.NET Core 2.1 with `netcoreapp2.1` things are now perfectly stable as was before with ASP.NET Core 2.0 and `net471`. So it would seem that the issue is only present when using `net471`.

  [1]: https://i.stack.imgur.com/OtO0v.png
  [2]: https://i.stack.imgur.com/OiYYZ.png
  [3]: https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1

**Comment by Tratcher** [comment] 2018-08-06 15:37
@halter73 @sebastienros

**Comment by halter73** [comment] 2018-08-06 18:36
Thanks for the report. This appears to be a duplicate of aspnet/KestrelHttpServer#2694 which we're currently looking into.

**Closed by halter73** 2018-08-06 18:36 UTC
