### ISSUE TITLE
Microsoft.AspNetCore.WebSockets System.NullReferenceException

### ISSUE THREAD

**Issue by n9** [aspnet/Home#2910] opened 2018-02-28 14:41 UTC
Sometimes, I get `System.NullReferenceException` in `Microsoft.AspNetCore.WebSockets`. It looks to me like a race condition. 

My code looks like:
```C#
while (!ct.IsCancellationRequested)
{
    var buffer = new byte[bufferSize];
    var result = await socket.ReceiveAsync(new ArraySegment<byte>(buffer), ct);
```
`ct` is `context.RequestAborted`

Call stack is:
```
Microsoft.AspNetCore.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate(System.ArraySegment<byte> payloadBuffer, System.Threading.CancellationToken cancellationToken) Line 651	C#	Symbols loaded.
[Resuming Async Method]		Annotated Frame
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#	Symbols loaded.
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result) Line 490	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result) Line 603	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask) Line 638	C#	Symbols loaded.
Microsoft.AspNetCore.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(int minimumRequiredBytes, System.Threading.CancellationToken cancellationToken, bool throwOnPrematureClosure) Line 1161	C#	Non-user code. Symbols loaded.
[Resuming Async Method]		Annotated Frame
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#	Symbols loaded.
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result) Line 490	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetResult(int result) Line 608	C#	Symbols loaded.
Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.ReadAsyncInternal(byte[] buffer, int offset, int count, System.Threading.CancellationToken cancellationToken) Line 127	C#	Non-user code. Symbols loaded.
[Resuming Async Method]		Annotated Frame
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#	Symbols loaded.
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#	Symbols loaded.
mscorlib.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result) Line 490	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetResult(int result) Line 608	C#	Symbols loaded.
Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(System.ArraySegment<byte> buffer, System.Threading.CancellationToken cancellationToken) Line 166	C#	Non-user code. Symbols loaded.
[Resuming Async Method]		Annotated Frame
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#	Symbols loaded.
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#	Symbols loaded.
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#	Symbols loaded.
Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.LoggingThreadPool.RunAction.AnonymousMethod__3_0(object o) Line 34	C#	Symbols loaded.
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#	Symbols loaded.
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#	Symbols loaded.
mscorlib.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 1252	C#	Symbols loaded.
mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#	Symbols loaded.
[Async Call]		Annotated Frame
[[my call above]]
```

In debugger, it looks like:
![image](https://user-images.githubusercontent.com/1651867/36793282-4dd38600-1c9d-11e8-94a5-2729c0a78cae.png)

It seems to me, that the function `ReceiveAsyncPrivate(System.ArraySegment<byte> payloadBuffer, System.Threading.CancellationToken cancellationToken)` is using `_receiveBuffer` after the cancellation was   requested.

**Comment by Tratcher** [comment] 2018-02-28 16:52
Closing this as a duplicate of https://github.com/dotnet/corefx/issues/26078

**Closed by Tratcher** 2018-02-28 16:52 UTC
