### ISSUE TITLE
ASP.Net Core runtime 2.1.3 throws FileLoadException

### ISSUE THREAD

**Issue by kjbartel** [aspnet/Home#3490] opened 2018-09-04 07:57 UTC
1. Description of the problem:
After installing the latest .Net Core SDK (2.1.401) ASP.Net Core apps targeting netocoreapp2.1 throw a FileLoadException when calling WebHost.Start() or WebHost.Run(). Previous packaged builds using a FDD fail to run if a new version of the runtime is installed.

2. Steps to reproduce
- Create a new ASP.Net Web Application targeting .Net Core and ASP.Net Core 2.1in VS
- Add a reference to the `Microsoft.AspNetCore.SignalR` nuget package. (Installed version 1.0.3 for me)
- Run / Debug
- Exception thrown: 
> Could not load file or assembly 'Microsoft.AspNetCore.Connections.Abstractions, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

3. The version of `Microsoft.AspNetCore.App`
2.1.1

4. The output of `dotnet --info`

> .NET` Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032
>
> Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\
>
> Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e
>
> .NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
>
> .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by SIkebe** [comment] 2018-09-04 08:05
See here
https://github.com/dotnet/core-setup/issues/4376

**Comment by kjbartel** [comment] 2018-09-04 08:13
A workaround for this issue:
- Specify the version of the `Microsoft.AspNetCore.App` in the `PackageReference`
- Add a runtimeconfig.template.json file:
`{
  "applyPatches": false,
  "rollForwardOnNoCandidateFx": 1
}`

**Comment by natemcmaster** [comment] 2018-09-05 21:12
Closing as a duplicate of https://github.com/dotnet/core-setup/issues/4512. It is fixed in 3.0 already. We are planning on taking a fix in 2.1.5.

**Closed by natemcmaster** 2018-09-05 21:12 UTC
Labels: external
