### ISSUE TITLE
Unable to install dnx (Join-Path $_ "runtimes" failed)

### ISSUE THREAD

**Issue by VeselovAndrey** [aspnet/Home#899] opened 2015-09-07 01:41 UTC
Unable to install dnx.
```
 Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
 At C:\Users\appveyor\.dnx\bin\dnvm.ps1:207 char:59
 + $RuntimeDirs = $RuntimeHomes | ForEach-Object { Join-Path $_ "runtimes" }
 +                                                           ~~
 + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
 + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 ``` 
Full log
https://ci.appveyor.com/project/VeselovAndrey/filewarehouse

**Comment by dougbu** [comment] 2015-09-07 02:47
/cc @BrennanConroy 

If `$env:DNX_HOME` and `$env:DNX_GLOBAL_HOME` aren't already defined, `$RuntimeHomes` is set to `;c:\ProgramData\Microsoft DNX`. With that, `dnvm.ps1` blows up at the line shown above. A `$env:DNX_HOME` value wasn't previously required and only a few commands set it.

Side question: When is `[Environment]::ExpandEnvironmentVariables($_)` required?

**Comment by Daniel15** [comment] 2015-09-07 04:16
As a sidenote, if you select "Visual Studio 2015" for AppVeyor's "Operating system" setting, DNVM will be preinstalled and you can  just do:
```
dnvm update-self
dnvm install 1.0.0-beta7
```

**Comment by VeselovAndrey** [comment] 2015-09-07 04:29
@dougbu Looks like you are right. I have set  $env:DNX_HOME and $env:DNX_GLOBAL_HOME  manually and install script was completed successfully. But I think install script should be updated to resolve this situation. Thanks.

@Daniel15 Thank. I'm using "Visual Studio 2015" as OS Settings but prefer to keep script as much independent as possible.

**Comment by Eneuman** [comment] 2015-09-09 10:40
@VeselovAndrey Can you please share your workaround?
This error also occures when running builds on VSO when you need to install mutiple clrs.

**Comment by VeselovAndrey** [comment] 2015-09-09 10:58
$env:DNX_HOME="Path to .dnx folder here like C:\Users\yourUserName\.dnx"
$env:DNX_GLOBAL_HOME="same path here"

**Comment by dougbu** [comment] 2015-09-18 18:14
This is a duplicate of aspnet/dnvm#422. Will track the fix there.

**Closed by dougbu** 2015-09-18 18:14 UTC
