### ISSUE TITLE
CallbackPath on Oauth Authentication cannot specify HTTPS or HTTP protocol

### ISSUE THREAD

**Issue by gornialberto** [aspnet/Home#2219] opened 2017-09-29 12:26 UTC
Hi, using Oauth for the authentication  
```

          .AddOAuth(OpenIdConnectDefaults.AuthenticationScheme, x =>
            {
                x.SignInScheme = "Cookies";
                x.ClaimsIssuer = Configuration.GetSection("UAA").GetChildren().Where(y => y.Key == "ClaimsIssuer").First().Value;
                x.AuthorizationEndpoint = Configuration.GetSection("UAA").GetChildren().Where(y => y.Key == "AuthorizationEndpoint").First().Value;
                x.TokenEndpoint = Configuration.GetSection("UAA").GetChildren().Where(y => y.Key == "TokenEndpoint").First().Value;
                x.UserInformationEndpoint = Configuration.GetSection("UAA").GetChildren().Where(y => y.Key == "UserInformationEndpoint").First().Value;

                x.CallbackPath = new PathString("/signin-oidc"); /* provider specific DO NOT MODIFY */


```
You can't specify if the Callback Path runs on HTTPS instead of HTTP.

This lead to scenario where if your web server runs HTTP behind an SSL Accelerator or a Load Balancer that expose your app as HTTPS the call back page cannot be reached by the external Oauth login page simply because to the OAuth is provided the callback to the HTTP endpoint that doesn't really exist.

If you have NO control on the Load Balancer or the SSL Accelerator (like we DO NOT have within Cloud Foundry) it doesn't work.

**Comment by Tratcher** [comment] 2017-09-29 16:04
Duplicate of https://github.com/aspnet/Security/issues/757

**Closed by Tratcher** 2017-09-29 16:04 UTC
Labels: duplicate
