### ISSUE TITLE
Test failure: EnableCoreHostTraceLogging_TwoLogFilesCreated

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#3442] opened 2018-08-21 23:06 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=536571&buildTypeId=Lite_IISIntegration) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (Operation did not succeed after 48 retries (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables'
) (Filename: \\?\C:\b\t\buildTmp\6d022585-6553-4af7-94a1-eeaf2292d515\applicationHost.config
Line number: 130
Error: Unrecognized element 'environmentVariables
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-21 23:06
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment] 2018-08-23 17:05
@muratg - can you assign? Test failure in IISIntegration.

**Comment by muratg** [comment] 2018-08-23 17:43
These three failures seem to have the same root cause: https://github.com/aspnet/Home/issues/3442, https://github.com/aspnet/Home/issues/3441, https://github.com/aspnet/Home/issues/3440

(And several failure reports in IISIntegration repo look similar as well. It would be good to look into how we can reduce duplication like this in RaaS.)

Assigning to @pakrym to take a look.

**Comment by pakrym** [comment] 2018-09-18 17:14
Mass failures that were fixed in IISIntegrations. Closing.

**Closed by pakrym** 2018-09-18 17:14 UTC
Labels: test-failure
