### ISSUE TITLE
asp.net mvc template app crashes with exceptions on raspian ARM

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#2831] opened 2018-01-28 01:19 UTC
_From @Buzze11 on January 27, 2018 11:32_

## Steps to reproduce

    1. create example mvc app with "dotnet new mvc -n test"
    2. Disable HttpsRedirect comment out (//app.UseHttpsRedirection();)
    3. Disable Cookie Policies comment out (//app.UseCookiePolicy();)
    4. publish with "dotnet publish -r linux-arm" and deploy it to the raspberry pi
    5. run app on raspberry device with ./test
    6. place a webrequest from any browser to the server

## Expected  behavior
MVC Example App shows up in browser window

## Actual behavior
- Exceptions get thrown.

- Even without modifying the example app (not deactivating https) the app is throwing exceptions on requests.

## Environment data
`dotnet --info` output:
Product Information:
Version: 2.2.0-preview1-007947
Commit SHA-1 hash: e8f7ddd01b

Runtime Environment:
OS Name: Windows
OS Version: 10.0.10586
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.2.0-previe

Microsoft .NET Core Shared Framework Host

Version : 2.1.0-preview1-26116-04
Build : eeb3a84e2142aba791fe003564b8afd048c45ff9

[Exception.log](https://github.com/dotnet/cli/files/1670022/Exception.log)

_Copied from original issue: dotnet/cli#8490_

**Comment by rynowak** [comment] 2018-01-28 02:39
@mkArtakMSFT @javiercn @pranavkm this is a crash in the view loading codepath that's been getting lots of changes lately. This is a possible 2.1.0-preview1 regression.

**Comment by mkArtakMSFT** [comment] 2018-01-28 05:10
@NTaylorMullen, can you please investigate this? Thanks!

**Comment by pranavkm** [comment] 2018-01-28 20:40
Looks like a dup of https://github.com/aspnet/templating/issues/233 that was fixed by https://github.com/aspnet/Mvc/commit/b20e35e76abf78f3f99e52e336ff429083b9cb8c. Would be good to determine if this still reproduces using a newer runtime, but my guess is this was likely fixed.

**Comment by Buzze11** [comment] 2018-01-28 21:59
Today I installed the latest SDK & Runtime and tested again. The Issue is still reproducable.

**Comment by Eilon** [comment] 2018-01-29 06:23
This issue was moved to aspnet/Mvc#7309

**Closed by Eilon** 2018-01-29 06:23 UTC
Labels: 1 - Ready, bug
