### ISSUE TITLE
Asp.net Core still not supported for azure web roles

### ISSUE THREAD

**Issue by MartinDawson** [aspnet/Home#1698] opened 2016-07-30 15:11 UTC
I don't know if this responsibility belongs to azure team or asp.net core team but this is a huge problem. Does anyone have any information regarding when azure web/worker roles we be supported for asp.net core? Here's a SO link from last year: http://stackoverflow.com/questions/31669008/asp-net-5-web-application-as-azure-web-role

**Comment by muratg** [comment] 2016-08-02 16:06
@MartinDawson do you have a good reason to use Cloud Services (Web/Worker roles) instead of other options?  https://azure.microsoft.com/en-us/documentation/articles/choose-web-site-cloud-service-vm/ is a good article to check out what to use.

**Comment by MartinDawson** [comment] 2016-08-02 21:53
@muratg I need it soley for using azure cloud's LocalResource class which I use to temp store files. At the moment I am having to use local file directory for development.

Is there any way to use the LocalResource class without making your application a web role then for azure storage emulator?

**Comment by muratg** [comment] 2016-08-02 22:42
@MartinDawson I recommend asking at StackOverflow. Because there are a lot of advantages of App Service (AKA Web Apps which manages more stuff for you) as well as VMs (where you can contol everything.)

**Comment by AerisG222** [comment] 2016-08-04 12:21
I am curious about this as well.  I like the idea of going to web apps, but need to stay on cloud services because we need to further limit the ciphers available on TLS (by updating registry settings on startup).  My understanding is this is not possible with web apps.

Going to VMs is not a great alternative, as we would have to start managing/patching the vms ourselves, which is one of the selling points for us to go to cloud services in the first place.

Will there be a path to upgrade on cloud services?

**Comment by muratg** [comment] 2016-08-04 15:47
@AerisG222 You can do this with Azure App Service Environments (A premium service where you get the whole VM for all your web apps, mobile apps etc.)  See https://azure.microsoft.com/en-us/documentation/articles/app-service-app-service-environment-custom-settings/ fot limiting the ciphers for example.

**Comment by AerisG222** [comment] 2016-08-04 17:22
Thanks for the pointer to the article, had not seen this before.

**Comment by AerisG222** [comment] 2016-08-05 13:58
After going through the article and trying to test this out, I am now realizing that updating a regular web app to live within an 'app service environment' is significantly more expensive for our needs (low traffic / strong security requirements), especially when contrasting with what we are paying for Cloud Services today.

Given this, I believe we will have to stay on cloud services from a cost perspective and to meet the requirement of limiting ciphers.  This brings us back to the original question of whether there would be an upgrade path on cloud services?

**Comment by GuardRex** [comment] 2016-08-05 15:37
> to meet the requirement of limiting ciphers

Unfortunately, it looks like it will be a longstanding issue: Since Kestrel uses `SslStream`, which relies upon Schannel in Windows (https://github.com/aspnet/KestrelHttpServer/issues/1018), shared hosting of Cloud Services apps on a VM within Azure seems like it would be an intractable problem for them. If you really need the fine control over cipher suites (as I do! :smile: ), then you probably will need to move to full Azure VM's or follow @muratg's advice. Even when Kestrel gets standalone Internet-facing features (https://github.com/aspnet/KestrelHttpServer/issues/957), I don't expect this situation to change ... moving off of Schannel probably isn't a "feature" that Kestrel is going to get.

**Comment by michaelaird** [comment] 2016-08-17 10:32
My $0.02 on why we want kestrel/.net core on Azure Web Roles: web roles are **significantly** cheaper than web apps

A2 Web Role : $145/month
S2 App Service: $181/month

**Comment by muratg** [comment] 2016-08-17 16:12
@michaelaird VM's even cheaper.

A2 VM: $70/mo

**Comment by michaelaird** [comment] 2016-08-17 16:15
True. I'm willing to pay a bit extra for package based deployments, a
slider to control scale, time of day auto scaling, etc. I don't understand
why websites cost more for less

**Comment by mms-** [comment] 2017-02-09 01:00
I also would like to see .Net Core on PaaS Cloud Services. Not sure why Azure is not developing this further, it is now quite annoying to see PaaS ignored by Azure. Why is it not on Resource Manager yet?

I do not want to run VMs which are a legacy out dated approach, App Service doesn't offer enough control and hide too much of the hardware specifics, CPU cycles matter. Cloud Services let me focus on my app with all the control I need, without caring about the OS, deployment and scale, best of both worlds. People should explore this a bit before just going with VMs.

**Comment by Lutando** [comment] 2017-04-21 11:12
So I take it this has not been revisited by anyone on any of the teams mentioned?

**Comment by onovotny** [comment] 2017-10-16 16:05
I've just blogged on how to do this (with VS tooling support!) here: https://oren.codes/2017/10/16/using-asp-net-core-with-azure-cloud-services/

**Comment by mms-** [comment] 2017-10-16 19:16
Let us know your plans for Cloud Services Microsoft. Ideally make App Service price competitive.

**Comment by Eilon** [comment] 2018-07-11 16:15
Closing because this issue because it is not directly an issue about ASP.NET Core.

My personal feeling is that the added value of Azure Web Services is worth the extra cost, given how smoothly and automatically it works from within VS, all the great debugging and diagnostic features, etc.

**Closed by Eilon** 2018-07-11 16:15 UTC

**Comment by michaelaird** [comment] 2018-07-11 16:17
Is there a place to open this issue for the azure sdk folks? I have a
feeling they’re going to say the issue is IIS support.

**Comment by Eilon** [comment] 2018-07-11 16:29
There are several different components to the Azure SDK, and you should be able to find them here: https://github.com/azure

If there's a specific one you can't find let me know and I'll see what I can dig up.
