### ISSUE TITLE
Enabling VaryByOrigin in Cors Options

### ISSUE THREAD

**Issue by kekedk** [aspnet/Home#3299] opened 2018-07-06 09:31 UTC
Hi

I was wondering if it could be possible to move the hidden logic of `VaryByOrigin` out of the count of origins?

https://github.com/aspnet/CORS/blob/fb4d7e5db1ccfcc7c8eaa52cb34b4a21776bf1d3/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsService.cs#L275
```
  if(policy.Origins.Count > 1)
  {
       result.VaryByOrigin = true;
  }
```

at the moment i have to use this code `WithOrigins("1", "2")` for enabling `VaryByOrigin ` when using `SetIsOriginAllowed`

```
services.AddCors(options =>
{
    options.AddPolicy("Policy1",
        builder => builder
            .SetPreflightMaxAge(TimeSpan.FromMinutes(1)) // This enables automatic preflight reponses
            .AllowAnyMethod()
            .AllowCredentials()
            .WithExposedHeaders("LOCATION")
            .WithHeaders("CONTENT-TYPE")
            .WithOrigins("1", "2")// Enables VaryByOrigin
            .SetIsOriginAllowed(IsOriginAllowed(env))
    );
});
```

**Comment by FlyingWraptor** [comment] 2018-07-20 09:19
Would adding a new variable configurable to override the existing functionality work for you?
Perhaps `CorsPolicy.ForceVaryByOrigin`    and    ``CorsPolicyBuilder.ForceVaryByOrigin()`?

**Comment by kekedk** [comment] 2018-07-20 10:45
Would it be better name with just VaryByOrigin()?

**Comment by FlyingWraptor** [comment] 2018-07-20 18:50
The function is made to force override already existing functionality so I believe it suits better.

VaryByOrigin() just sounds like a function enabling the header for a specific request.

**Comment by FlyingWraptor** [comment] 2018-07-23 20:19
@javiercn You are right. I will apply this to the pull request instead.

**Comment by mkArtakMSFT** [comment] 2018-09-27 17:51
Closing as a dupe of https://github.com/aspnet/Home/issues/3452.

**Closed by mkArtakMSFT** 2018-09-27 17:51 UTC
Labels: repo:CORS
