### ISSUE TITLE
View Components from a Class Library compilation after changes.

### ISSUE THREAD

**Issue by artiom-matusenco** [aspnet/Home#1905] opened 2017-01-18 09:24 UTC
Hi,
I have implemented embed view as is described in this article: http://www.davepaquette.com/archive/2016/07/16/loading-view-components-from-a-class-library-in-asp-net-core.aspx

The problem is that when I change embed view file .net compiler does not detect changes in the view.
The view is compliled only if I manually start rebuild process or do some changes in c# code (for example in controller).

**Comment by valentin78** [comment] 2017-01-18 09:26
I have similar issue

**Comment by Tratcher** [comment] 2017-01-18 13:30
@NTaylorMullen

**Comment by dpaquette** [comment] 2017-01-19 16:39
I do remember encountering a compiler bug where the compiler did not recognize changes to the resource. I had assumed this was fixed by now but I guess not.

**Comment by valentin78** [comment] 2017-01-19 16:49
> I do remember encountering a compiler bug where the compiler did not recognize changes to the view file and did not update the embedded resource. I had assumed this was fixed by now but I guess not.

can I find this bug report? 

> @NTaylorMullen 

what this meaning?

**Comment by dpaquette** [comment] 2017-01-19 16:54
@valentin78 The only but report I can find is this one https://github.com/aspnet/dnx/issues/3396 but it is referencing the old dnx tooling which is no longer being used.

**Comment by Ponant** [comment] 2017-01-21 18:18
@dpaquette , I also look at your blog and I like your suggestion about plugins. However, any idea on how to include the cshtml files as embedded resources in the class library with .Net Core 1.1 which has csproj instead of project.json? That will be great because I am blocked for now.

**Comment by Ponant** [comment] 2017-01-23 14:09
That worked with csproj
    <EmbeddedResource Include="Views/**/*.cshtml" />

**Comment by valentin78** [comment] 2017-01-24 13:05
> csproj

as I understand, by extension, you use VS2017 ? Possible this issue appears only in VS2015

**Comment by pranavkm** [comment] 2017-01-24 17:39
@dpaquette \ @valentin78, the CLI had a similar issue - https://github.com/dotnet/cli/issues/3176 where the application does not rebuild when content files change. According to the work item, the issue is no longer reproducible with the MSBuild tooling. So yes, the issue should not appear once the project retargets VS 2017.

**Comment by Ponant** [comment] 2017-01-24 21:15
@valentin78 , correct I am using VS 2017, buggy but funny IDE! However, I also need to recompile the project to make it work, but it works.

**Comment by valentin78** [comment] 2017-01-25 06:03
I understan, thnk you all
for VS2015 now I made crutch, PS script, which watch for *.cshtml files changed, created and so on, and change LastWriteTime
I paste here my script, maybe someone will be useful

$global:Folder = "E:\Projects\MyProject"

### SET FOLDER TO WATCH + FILES TO WATCH + SUBFOLDERS YES/NO
    $watcher = New-Object System.IO.FileSystemWatcher
    $watcher.Path = "$global:Folder"
    $watcher.Filter = "*.cshtml"
    $watcher.IncludeSubdirectories = $true
    $watcher.EnableRaisingEvents = $true  

### DEFINE ACTIONS AFTER AN EVENT IS DETECTED
    $action = { 
				#$path = $Event.SourceEventArgs.FullPath
                #$changeType = $Event.SourceEventArgs.ChangeType
                #$logline = "$(Get-Date), $changeType, $path"
                #Add-content "D:\log.txt" -value $logline
				
				$file = "$global:Folder\project.json"
				(Get-Item -Path $file).LastWriteTime = Get-Date
              }    
### DECIDE WHICH EVENTS SHOULD BE WATCHED 
    Register-ObjectEvent $watcher "Created" -Action $action
    Register-ObjectEvent $watcher "Changed" -Action $action
    Register-ObjectEvent $watcher "Deleted" -Action $action
    Register-ObjectEvent $watcher "Renamed" -Action $action
	
    while ($true) {sleep 1}

my be someone can help me, how I can point multiple filters with one watcher?

**Comment by aspnet-hello** [comment] 2017-12-30 23:39
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment] 2017-12-30 23:39
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (240/200 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:48912 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQix-0000VV-C0
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:31 -0600
Date: Sat, 30 Dec 2017 15:39:11 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677151;
	bh=2zwD4fYiiqfw1vj34cz2AvbNPCL2muF81mOhzDaYeKY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LptWmU3gSZzwCj9R0ijjNCKfuhHH99TE5Z9r1o0QPyqC6X07UtZQ86s5NIIOwv1MR
	 uOP3E+4M47yf9fkM4skOrOT9TTURk5XuXmHp8+UIPbst4wEOXLzrNNKQtKylghiEBC
	 oIog1nF7r5BihYECjAC17aw9BKK6oqv7sh8BvCk4=

**Comment by davidalpert** [comment] 2017-12-30 23:39
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (241/200 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:55503)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQj0-0000Vw-5E
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:34 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=68gkNMYcXQGRJxa33aXGANbQqco=; b=f1D5ZAdWrTLbm/HT
	3r7+itRn74VNWCcldedAqGUGvL1MUEZrqA35fP6bUkrA9v63GUeNeLcwvCxR614R
	IBXqUj2aPs+qpXbbF/Q/lCH1rYRsSzpG86OjoCc2Wb57GcVFl7Or+ImoH3C/92Qz
	3n+ek0vPQfdgAClLTyZHJbiAsz4=
Received: by filter0989p1mdw1.sendgrid.net with SMTP id filter0989p1mdw1-18898-5A4823A2-1
        2017-12-30 23:39:14.215765091 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0022p1iad2.sendgrid.net (SG) with ESMTP id flnkt0f7TEWaeUf3jdVsYg
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:39:14.212 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:39:14 +0000 (UTC)

**Closed by aspnet-hello** 2017-12-30 23:39 UTC
