### ISSUE TITLE
Adding resource file in .Net Core 2.0 Preview 1 crashes VS 2017!

### ISSUE THREAD

**Issue by Ponant** [aspnet/Home#2075] opened 2017-06-27 18:50 UTC
moved from
https://github.com/aspnet/Localization/issues/388

Did anyone experience this issue or has a workaround for it?
https://developercommunity.visualstudio.com/content/problem/73457/adding-resource-file-in-net-core-20-preview-1-cras.html

repro https://github.com/Ponant/ResourceFileCrashCore20-preview1

same issue (closed by VS Team while people continue complaining)
https://developercommunity.visualstudio.com/content/problem/22058/crash-when-editing-resource-resx-files.html

**Comment by Ponant** [comment] 2017-06-28 11:07
@davkean ?

**Comment by natidea** [comment] 2017-07-21 05:52
This is a duplicate of https://github.com/dotnet/project-system/issues/2512 and is fixed now

**Closed** 2017-07-21 07:26 UTC
