### ISSUE TITLE
why web.config in the publish folder?

### ISSUE THREAD

**Issue by ahdung** [aspnet/Home#2206] opened 2017-09-20 03:36 UTC
- VS2017
- asp.net core 2.0 project
- publish to folder
in bin\xx\netcoreapp2.0 no web.config, but bin\xx\PublishOutput has web.config, the content:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\xxx.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
<!--ProjectGuid: 9e4e704c-869f-41da-9668-d4ea1d44002d-->
```
I try remove web.config, all thing are work fine, is this a issue?

**Comment by Tratcher** [comment] 2017-09-20 03:45
It's there so you can run the site in IIS. You can remove it if you're going to run elsewhere.

**Comment by ahdung** [comment] 2017-09-20 04:57
@Tratcher  as you said, it should be a option, not always give me.

**Comment by natemcmaster** [comment] 2017-09-20 17:09
You can suppress web.config generation by setting IsTransformWebConfigDisabled to true, either in csproj, or on command line. For example:

```
dotnet publish /p:IsTransformWebConfigDisabled=true
```

See https://github.com/aspnet/websdk/issues/28

**Comment by ahdung** [comment] 2017-09-21 01:02
@natemcmaster Thanks, it's worked.

**Comment by natemcmaster** [comment] 2017-09-21 16:40
Happy to help.

Closing as a duplicate of aspnet/websdk#28.

**Closed by natemcmaster** 2017-09-21 16:40 UTC
