### ISSUE TITLE
ASP.NET Core 5.0 or ... Core .NET 5.0?

### ISSUE THREAD

**Issue by Mike-EEE** [aspnet/Home#972] opened 2015-10-06 19:42 UTC
_From @Michael-DST on August 9, 2015 13:32_

(Apologies if this is in the wrong place.  There are four pages -- ! -- of repos and this seemed like the best fit.)

I have an easy (hopefully) issue here.  It could be a bug or could simply be based off my misunderstanding.

I finally had the joy of installing the latest build (Beta 6) and tried looking into moving my current PCLs to the new Core .NET.  However, when I viewed my PCL targets, the following was displayed:

![](http://content.screencast.com/users/MichaelDBang/folders/Jing/media/3a635f7e-347c-4f7b-acbb-4e1a03a613c2/2015-08-09_0923.png)

I thought the new ASP.NET was based on Core .NET libraries, and not vice versa.  Shouldn't "ASP.NET Core 5.0" read "Core .NET 5.0" ?

Thank you for any clarification you can provide.

_Copied from original issue: aspnet/Tooling#139_

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @Eilon on August 9, 2015 18:12_

This indeed looks like it's the wrong string. At one point a long time ago it was indeed ASP.NET Core 5.0, but that hasn't been the case for a while.

@yishaigalatzer do you know the right people to correct this in PCLs?

**Comment by Michael-DST** [comment] 2015-10-06 19:42
Cool!  Sanity restored/verified... for now. :smile:

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @yishaigalatzer on August 9, 2015 19:27_

@pilchie 's team owns this ui

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @sayedihashimi on September 30, 2015 16:52_

I don't think that this repository is the best place for this feedback. @yishaigalatzer or @pilchie what do you guys think?

**Comment by Michael-DST** [comment] 2015-10-06 19:42
Yeah as I mentioned in the initial post there are four pages of repos for this project, so landing on the right one was quite the challenge for one of my first reports. ;)  I am open to moving it to another repo if it makes more sense... and of course ensures that the issue is addressed.  I am also (of course) interested in which repo would be better suited for this issue so that I can learn from my mistakes. :)

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @Pilchie on September 30, 2015 17:1_

We just put the string that @davidfowl told us to put there.  "Core.NET 5.0" is definitely not right either, since UWP is *also* based on CoreCLR.  The dialog is less interested in what technology you run on, and more on what app platform stack do you run on.

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @lucamorelli on September 30, 2015 17:11_

when in doubt I suggest to post in "Home"

**Comment by Michael-DST** [comment] 2015-10-06 19:42
Cool.  Thanks @lucamorelli.  Pardon the mess all as I learn all of this (story of my life!). :smile:

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @sayedihashimi on October 6, 2015 17:42_

I'm still not sure which repo is the best place for this feedback, but we don't have the right people watching this repo for this issue. I think for now we should move this item to https://github.com/aspnet/Home.

Closing this now.

**Comment by Michael-DST** [comment] 2015-10-06 19:42
To be sure @sayedihashimi, are you saying that this was moved or do you need me to do that for you?

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @sayedihashimi on October 6, 2015 18:17_

@Michael-DST if you can move it that would be great.

**Comment by Michael-DST** [comment] 2015-10-06 19:42
@sayedihashimi How is the best way of doing that?  I do not see that option here in GitHub.

**Comment by Michael-DST** [comment] 2015-10-06 19:42
_From @Eilon on October 6, 2015 19:13_

You can use this tool: https://github-issue-mover.appspot.com/

All it does is open a new issue and copy all the info over.

**Comment by sandersaares** [comment] 2015-10-13 12:05
What exactly does that dialog even do in the modern projects?

**Comment by Pilchie** [comment] 2015-10-13 12:21
It changes the `supports` clause in the project.json, which allows NuGet to ensure that there is a deployable asset for the platforms you have selected.

**Closed** 2017-02-19 09:09 UTC
