### ISSUE TITLE
ASP .NET Core: Sporadic 503 responses from web app hosted on azure services 

### ISSUE THREAD

**Issue by suejon** [aspnet/Home#2262] opened 2017-10-31 02:26 UTC
My web app is hosted on azure and will run normally for about 3 - 4 days before it fails and returns 503 messages to requests. This issue is resolved after a restart but occurs again after a few days. 

I am running ASP .NET Core 1.1 but targeting the NET461

I have contacted the Azure support team and they have indicated that these 503 messages are related to the web app and not the Azure hosting platform. Here is the FREB trace given:

`#1 GENERAL_REQUEST_START @0ms
|#25 HANDLER_CHANGED @0ms
OldHandler: , NewHandler: aspNetCore, NewHandlerType: 
|#73 NOTIFY_MODULE_START @0ms
Module: AspNetCoreModule, Notification: EXECUTE_REQUEST_HANDLER
|#75 GENERAL_REQUEST_START @0ms
|#81 HANDLER_CHANGED @0ms
OldHandler: , NewHandler: aspNetCore, NewHandlerType: 
|#129 NOTIFY_MODULE_START @0ms
Module: AspNetCoreModule, Notification: EXECUTE_REQUEST_HANDLER
|#130 MODULE_SET_RESPONSE_STATUS_ERROR @0ms
Module: AspNetCoreModule, Notification: EXECUTE_REQUEST_HANDLER, Status: 503, SubStatus: 0, HttpReason: Service Unavailable, Win32ErrorCode: 0x00000000, ConfigException: 
|#131 NOTIFY_MODULE_END @0ms
`
The Azure support worker indicated that this issue could either have been related to the ASP .NET Core framework or the SignalR (.NET) being used in the app.

Any ideas or help on this issue would be great

**Comment by Tratcher** [comment] 2017-10-31 22:06
Why is SignalR in your app? That's not supported on Core yet.

**Comment by suejon** [comment] 2017-11-01 03:27
The app is a .NET Core project but targets the .NET 461 framework. So we are able to use the .NET SignalR package

**Comment by Tratcher** [comment] 2017-11-01 03:37
The old verion of SignalR is not supported on ANY version of ASP.NET Core. There are some new alpha packages, but that's it.

**Comment by alejandromelis** [comment] 2017-12-04 12:38
I've the same problem and I'm not using SignalR. It happens with netcore 1.1 and netcore 2.0, even with webapp with only static content and one middleware mapped to specific path. I've the same issue in multiple kind of web apps, it happens with webapps with very low usage, webapps with medium usages and webapps with 4M+ requests per day.

Some webapps are running without code update for a long time, until approximately 2 months ago when they start crashing randomly. 

No log info, the stdoutLogFile is set to "\\?\%home%\LogFiles\stdout" and when stdoutLogEnabled is enabled log does not display any error.

Sometimes there are many instances failing, and sometimes only one instance is failing. The process explorer show me a clue, the broken instance does not have a dotnet child process running as the image show.

![net-core-process](https://user-images.githubusercontent.com/1795442/33552489-53ea45f6-d8f5-11e7-9022-cc01bf783a97.PNG)

Since last Saturday I've upgraded one site to net core 2.0.3 and I'm currently monitoring, but I need several weeks without crashes to be sure this solve the issue.

**Comment by Syalas** [comment] 2018-03-07 14:28
I encounter exactly the same issue. But I'm running our .NET Core 2.0 App on a Linux hosting with Apache and ProxyPreserveHost. Sometimes after a few days sporadic 503 Errors appear. Funny thing is, it can happen on one client while another can still access the website. Though it's a really bad error, because I can't explain this our customer.

**Comment by Tealons** [comment] 2018-05-14 17:53
@Syalas did you find out what the issue was? I have the same problem with the same setup. The logs don't give any clue about what's the problem.

**Comment by Eilon** [comment] 2018-08-28 22:33
Hi. We're closing this issue because we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by Eilon** 2018-08-28 22:33 UTC

**Comment by olssonjoakim** [comment] 2018-10-01 14:03
I'm getting the exact same problem on one of our api apps in azure.
It shows 0x800705b4 in eventlog.xml.
stdout is enabled, the log files are created but there is no data in them. They have no file size when i look in SCM.

**Comment by Tratcher** [comment] 2018-10-02 17:19
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
