### ISSUE TITLE
Microsoft.AspNet.WebApi.Client does not support Xamarin.iOS and MonoDroid targets

### ISSUE THREAD

**Issue by alot1** [aspnet/Home#1760] opened 2016-09-20 05:09 UTC
Hi,

Looks like Microsoft.AspNet.WebApi.Client 5.2.3 nuget package is not compatible with Xamarin.iOS and MonoDroid projects. 
When trying to add the package using VS2015 or Xamarin Studio the package manages gives an error:

> Could not install package 'Microsoft.AspNet.WebApi.Client 5.2.3'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The package manager in VS2013 is less strict with validation and does allow to install the package to Xamarin.iOS and MonoDroid projects adding a reference to assembly in `lib\portable-wp8+netcore45+net45+wp81+wpa81\System.Net.Http.Formatting.dll`. And it does compiles and runs correctly.

Would it make sense to update the package to support the Xamarin targets properly?
Probably just adding `+monoandroid+monotouch+xamarin.ios10` should be enough?

Thank you,
Alexey.

**Comment by WillooWisp** [comment] 2017-04-30 17:54
Why no progress on this annoying issue?

**Comment by usagi70** [comment] 2017-04-30 18:51
Sen, 1 Mei 2017 pukul 00.54 Joel <notifications@github.com> menulis:

**Comment by natemcmaster** [comment] 2017-05-01 17:05
Checkout this: https://dotnet.myget.org/feed/aspnetwebstack-dev/package/nuget/Microsoft.AspNet.WebApi.Client. It's a nightly build, so not officially supported. But this new build targets .NET Standard 1.1 which means it installs in:

- .NET Core 1.0
- .NET Framework 4.5
- Mono 4.6
- Xamarin.iOS 10.0
- Xamarin.Android 7.0
- Universal Windows Platform 10
- Windows 8.0
- Windows Phone 8.1

We haven't thoroughly tested the nightly build with Xamarin. If you find issues, you can open them here: https://github.com/aspnet/AspNetWebStack

Closing as a duplicate of https://github.com/aspnet/AspNetWebStack/issues/4.

**Closed by natemcmaster** 2017-05-01 17:05 UTC
