### ISSUE TITLE
Error 500 unacceptable

### ISSUE THREAD

**Issue by j-nord** [aspnet/Home#3129] opened 2018-05-09 14:24 UTC
MiMicrosoft.AspNetCore Version: 2.02:

It can not be that the server returns an error message 500 without any error message !!!

"stdout" protocol does not work either!

Just do not catch on talking to you, with server log, etc. That's and remains a no go!

We need "proper" error messages for net core!

Regards
j.nord

**Comment by Eilon** [comment] 2018-07-10 17:36
Hi. We're closing this issue as we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by Eilon** 2018-07-10 17:36 UTC
