### ISSUE TITLE
ASP.NET Core 1.1 fails to deploy to azure web app via CI web.config is not created with the correct values

### ISSUE THREAD

**Issue by philipp985** [aspnet/Home#1842] opened 2016-11-23 10:20 UTC
I updated my existing web app from 1.0.1 to 1.1. I have set up a continuous deliver process from the azure portal before I updated the app and all went without problems. After updating the app to 1.1 the continuous delivery still works but the app stopps with a "HTTP Error 502.5 - Process Failure".
I created a new app from scratch updated to 1.1 and tried to upload it to azure and I get the same result. I investigated the error and from what I see the problem is that the web.config file is not automatically updated. The web.config on azure looks like:
 `   <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="false" /> `
so none of the placeholders is filled out.

The project.json looks like this

```
{
  "userSecretsId": "8272f1fc-3e6e-44fc-b1af-54bfabe2a6ba",

  "dependencies": {
    "AutoMapper": "5.1.1",
    "BundlerMinifier.Core": "2.2.306",
    "MailKit": "1.10.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.AzureAppServicesIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Newtonsoft.Json": "9.0.1",
    "StructureMap.Microsoft.DependencyInjection": "1.2.0",
    "WindowsAzure.Storage": "7.2.1"
  },

  "tools": {
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },


  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    ]
  }
}
```

The continoous delivery is set up like this:
Azure portal -> App Services -> Continuous Delivery -> Choose a repo from VSTS and thats it. As said before with 1.0.1 it worked pretty good but now it stopped. If I change the web.config by hand and enter  values like this
```
<aspNetCore processPath="dotnet"
        arguments=".\MyApp.dll"
        stdoutLogEnabled="true"
        stdoutLogFile="\\?\%home%\LogFiles\aspnetcore-stdout">
</aspNetCore>
```

I can make the app running.

Thanks for your help in advance!

**Comment by Tratcher** [comment] 2016-11-23 22:08
It sounds like `dotnet publish` isn't being run. Not sure how that fits in with continuous delivery.

**Comment by philipp985** [comment] 2016-11-24 06:41
If I locally publish it to filesystem it works. If I right click on the solution and publish it to azure it also works. If I try to build it Visual Studio Team Services I checked the logs while building and it gives the following warning
2016-11-23T16:30:02.3252189Z The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.
2016-11-23T16:30:02.3252189Z   - Check application dependencies and target a framework version installed at:
2016-11-23T16:30:02.3252189Z       C:\Program Files\dotnet\shared\Microsoft.NETCore.App
2016-11-23T16:30:02.3252189Z   - The following versions are installed:
2016-11-23T16:30:02.3252189Z       1.0.0
2016-11-23T16:30:02.3252189Z       1.0.1
2016-11-23T16:30:02.3252189Z   - Alternatively, install the framework version '1.1.0'.

Maybe there is a command I have to run but I don't know how to solve this problem. Or is .net core 1.1. being deployed dto vsts at a later moment?

Thanks for your help!

**Comment by Tratcher** [comment] 2016-11-24 16:38
@glennc what do we know about the VSTS deployment of .NET Core 1.1?

**Comment by Tratcher** [comment] 2016-11-24 16:46
You may be able to continue using: 
`"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",`

**Comment by philipp985** [comment] 2016-11-25 10:21
If I use 
`"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"`
as you suggest, it all works fine.
Maybe you or someone else can inform me, if it is also working with 1.1 or I will try on an unregular interval.
But for so far my problem seems to be solved. Thank you very much. It made my life a lot easier!
Have a nice weekend
Philipp

**Comment by baywet** [comment] 2016-11-25 20:30
Ran into the same issue today. The VSTS hosted agent still has .net core 1.0 preview 2 installed. So until they update the version they have installed I'm afraid we won't be able to to much. However the dotnet build process could tell we're building against the wrong version of the SDK at some point.
[VSTS Hosted Agent documentation](https://www.visualstudio.com/en-us/docs/build/admin/agents/hosted-pool)

**Comment by glennc** [comment] 2016-12-08 22:21
Yeah, if you want to use 1.1 you will need to get a build agent that has 1.1 on it. Probably a custom VM. If the hosted agents have Docker now (which I think they do) then you could also change your build to work inside a container, and add 1.1 to the container. That way you can continue to use the hosted agent. Are either of those work arounds ok for you?

**Comment by baywet** [comment] 2016-12-09 01:25
We will delay our migration to version 1.1 in our case, we don't need it right now. The problem is mostly with hosted agent being behind. https://github.com/Microsoft/vsts-agent/issues/693 
However it'd be great to have the build fail or warn or something when version of tooling is not supporting the target version. It'd have helped troubleshooting the issue a great deal.

**Comment by philipp985** [comment] 2016-12-09 07:30
As I see it the problem should be fixed in the next few days. 
[https://blogs.msdn.microsoft.com/visualstudioalm/2016/12/08/december-hosted-build-image-updates/](url)
So there should be no more probles for me. But troubleshooting could have been easier. I agrre to @baywet 
Thanks for the help!

**Comment by baywet** [comment] 2016-12-09 13:27
That's good news! Thanks

**Comment by glennc** [comment] 2016-12-13 18:26
Closing this one as solved shortly then.

**Closed by glennc** 2016-12-13 18:26 UTC

**Comment by sturatcliffe** [comment] 2017-02-20 15:19
I have a similar issue, and can't seem to get the right combination of package versions to allow azure to git deploy my app successfully. Manual web deploy works perfectly, whereas git deploys will build, but throw 502 errors when accessing the app from the browser.

project.json as follows:

```
{
  "dependencies": {
    "Microsoft.DotNet.InternalAbstractions": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "IdentityServer4.AspNetIdentity": "1.0.0",
    "IdentityServer4.EntityFramework": "1.0.0",
    "BundlerMinifier.Core": "2.3.327"
  },

  "tools": {
    "BundlerMinifier.Core": "2.2.281",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "net461": {}
  },

  "runtimes": {
     "win7-x64": {}
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": [ "idsvr.pfx" ]
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config",
      "idsvr.pfx"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

global.json as follows:

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}
```

I've enabled the developer exception page, and then receive the following error in the browser:
"502 - Web server received an invalid response while acting as a gateway or proxy server."

I've tried creating a brand new web app from the templates in VS2015, updating all package references to 1.1 and git deployments are working fine, so I presume the build agents have now been updated to use 1.1?

I've also checked what my web.config looks like in Kudu, and it seems to be fine:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\Web.exe" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

When checking the logfiles directory, I can see the following error:

Application 'MACHINE/WEBROOT/APPHOST/APP_NAME' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline '"D:\home\site\wwwroot\Web.exe" ', ErrorCode = '0x80004005 : e0434352.

Does this sound similar to the issue raised here? Am I missing something simple? Or should I be raising this as it's own separate issue? (And if so, what is the actual issue I'm reporting?!) 

Thanks!!

**Comment by GuardRex** [comment] 2017-02-20 18:22
@sturatcliffe The exception you show looks like an Application Log entry (i.e., Event Viewer) not from the stdout log. Did you enable the stdout log and see if you get some additional info: `stdoutLogEnabled="true"`?

**Comment by sturatcliffe** [comment] 2017-02-21 07:59
@GuardRex I've set stdoutLogEnabled to true, and for some very strange reason my app started deploying successfully from github (we use VSTS at work, but I've been testing in a new azure app service pointing at github so as not to keep breaking our manual app deployments)

I then pointed the second app service at VSTS and did a git push and all was working well. Thought that somehow the problem was resolved, just by enabling the stdout log (would have been very weird!) However, when turning back on the VSTS git deployments on the original azure app service, I still receive 502's, and can't for the life of me work out what's different in the setup of these app services, they look identical!

Anyway, stdout log is reporting this error shortly after failing to startup:

System.AggregateException: One or more errors occurred. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

So ultimately, I now have 2 azure app services both configured to automatically deploy from the same VSTS git repo, and only one works!

**Comment by GuardRex** [comment] 2017-02-21 15:03
> System.BadImageFormatException

Occurs when there is a bitness mismatch: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#platform-conflicts-with-rid

One thing that can go sideways with Azure App deployments is incompatible assemblies hanging around. Some devs have had to go in and manually delete every file+folder in an Azure App deployment ... then redeploy to clear a problem. You might want to try that on your 1st app service to see if you can clear it.
