### ISSUE TITLE
与System.Net.Http.dll 这个版本4.6.25220.1及 以上版本不兼容

### ISSUE THREAD

**Issue by ghd258** [aspnet/Home#2279] opened 2017-11-17 08:48 UTC
与System.Net.Http.dll 这个版本4.6.25220.1及 以上版本不兼容，如果不引用会自动增加 System.Net.Http.dll 4.6.25514.4这个版本，但是在NuGet就没有4.6.25514.4这个版本号；引用了System.Net.Http.dll 这个版本4.6.25220.1及 以上版本会把项目的引用Dll变为感叹号

**Comment by Tratcher** [comment] 2017-11-17 16:46
Auto-Translation:
"System.Net.Http.dll not compatible with this version 4.6.25220.1 and above, if you do not reference will automatically increase System.Net.Http.dll 4.6.25514.4 this version, but there is no 4.6.25514.4 NuGet this version number; Reference System.Net.Http.dll This version 4.6.25220.1 and above will be the project's reference Dll into an exclamation point"

Which AspNetCore package did you reference that caused this error? I see you opened the same issue in https://github.com/aspnet/HttpAbstractions/issues/970 and https://github.com/aspnet/Diagnostics/issues/424

**Comment by ghd258** [comment] 2017-11-23 00:54
这几个只有有一个 ，就会造成这个问题，引用任何一个都会出现的

**Comment by MaximRouiller** [comment] 2017-11-23 13:13
Bing Translation:

> There's only one of these, and that's the problem.

**Comment by Eilon** [comment] 2017-11-27 18:48
@ghd258 please upload your project to GitHub so we can take a look. There is not enough information for us to reproduce this problem.

**Comment by Eilon** [comment] 2017-12-13 19:49
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-12-13 19:49 UTC
