### ISSUE TITLE
.csproj reference

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#1912] opened 2017-01-25 21:27 UTC
As the universum will be running on `.csproj` based configuration soon, can we have a specs published and maintained somewhere similar to dreaded/rip `project.json` specs, please?
https://github.com/aspnet/home/wiki/project.json-file
https://docs.microsoft.com/pl-pl/dotnet/articles/core/tools/project-json
I'll have to tinker about migrating 3rd party code to use `.csproj` without VS tooling support, so knowing some internals would help.
Thanks!

**Comment by moozzyk** [comment] 2017-01-25 22:04
@natemcmaster wrote a nice post on this very subject: http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/

**Comment by peterblazejewicz** [comment] 2017-01-25 22:25
@moozzyk Thanks! Appreciated!
But one still needs something more definitive as guide for .NET core migration. For example I could read all possible scripts values for `project.json` just by following still valid specs:
http://json.schemastore.org/project
At least something like:
https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file
**NOTE** I've found this one, but still it seems to be just too generic:
https://docs.microsoft.com/pl-pl/visualstudio/msbuild/msbuild-project-file-schema-reference
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/csproj
and later this:
https://msdn.microsoft.com/en-us/library/5dy88c2e.aspx
but I would welcome the draft docs used to create `new3` (dotnet/cli) tooling migration output to be released if possible
Thanks!

**Comment by natemcmaster** [comment] 2017-01-30 17:24
Our docs team is on it. Closing as a duplicate of the effort tracked here: https://github.com/dotnet/docs/projects/5.

**Closed by natemcmaster** 2017-01-30 17:24 UTC

**Comment by peterblazejewicz** [comment] 2017-01-30 19:48
@natemcmaster appreciated!

x-ref: https://github.com/dotnet/docs/issues/1456
