### ISSUE TITLE
Unable to bind route parameters

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2291] opened 2017-11-27 19:10 UTC
@pavankoppineni opened this here: https://github.com/dotnet/core/issues/1099#issuecomment-347278404

# Issue Title

Unable to bind route parameters

# General

I am not able to bind route parameters or query parameters to an action and am getting following error.

**Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.**

For my project, I am using 'System.ComponentModel.TypeConverter, Version=4.3.0.0' and .Net Core 1.1.

**Comment by Tratcher** [comment] 2017-12-05 05:25
Please share the list of your project dependencies and versions. These types of issues are often caused by dependency mismatches.
/cc: @rynowak

**Comment by Eilon** [comment] 2018-01-10 19:02
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2018-01-10 19:02 UTC
