### ISSUE TITLE
Test failure: StringSegment_ImplicitConvertToSpan

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#3544] opened 2018-09-20 20:42 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=557737&buildTypeId=XPlat_Windows_Win8_Universe) occasionally with the following error:
```
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.MemoryExtensions.AsSpan(String text, Int32 start, Int32 length)
   at Microsoft.Extensions.Primitives.StringSegmentTest.StringSegment_ImplicitConvertToSpan() in /_/test/Microsoft.Extensions.Primitives.Tests/StringSegmentTest.cs:line 48
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-09-20 20:42
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-09-20 20:42
StringSegment_AsSpan [failed with about the same error](http://aspnetci/viewLog.html?buildId=557737&buildTypeId=XPlat_Windows_Win8_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment] 2018-09-20 22:45
@pranavkm do we know more about these bad packages? Do we need to get in touch with CoreFX folks to find the cause?

**Comment by pranavkm** [comment] 2018-09-20 22:56
Just a guess since the package was updated recently - https://github.com/aspnet/Universe/commit/48e66d3d101de3b34344d735340118061a5e6949#diff-30dcc9789f8ea3c7632e4f054e60c072R22

**Comment by Eilon** [comment] 2018-09-20 23:11
@Petermarcu / @weshaggard - do you know of any package issues regarding System.Runtime.CompilerServices.Unsafe in the 3.0 branches?

**Comment by weshaggard** [comment] 2018-09-20 23:42
No issue that we are aware of. I just opened up the package from https://github.com/aspnet/Universe/commit/48e66d3d101de3b34344d735340118061a5e6949#diff-30dcc9789f8ea3c7632e4f054e60c072R22 and it looks correct to me from a quick look. One think I did notice is that the newer version has a higher assembly version. It has 4.0.5.0 but the error you guys have something seems to be looking for 4.0.4.0. I wouldn't expect that to be an issue on .NET Core but if you are running on .NET Framework you might need to update a binding redirect somewhere.

**Comment by pranavkm** [comment] 2018-09-20 23:45
The test failures appear on desktop (.NET Framework).  Wouldn't NuGet handle binding redirects for us?

**Comment by weshaggard** [comment] 2018-09-21 00:17
I don't think it is Nuget but msbuild that should be generating binding redirects depending on how the test projects are built and assuming they reference the new package as well.

**Comment by muratg** [comment] 2018-09-21 17:58
What's the next action on this issue? Investigating assembly version mismatch? Trying to work around it (with binding redirects)? Further root cause analysis?

**Comment by ryanbrandenburg** [comment] 2018-09-21 18:49
Yeah, this issue seems to fail ~70 tests on a 3.0 Universe build.

**Comment by weshaggard** [comment] 2018-09-21 23:03
I don't know enough about your test infrastructure but I'd suggest someone get on a machine and look at the binding redirects being used and see if they have they are correct (i.e. they bind everything up to the newer version 4.0.5.0) If the don't that should be investigated further to see why not. It is also potentially worth looking at which component you guys are consuming that is still referencing the 4.0.4.0 version of this dependency and see if you need to update that as well.

**Comment by dougbu** [comment] 2018-09-24 17:32
Taking this one because it appears to have the same root cause as aspnet/MusicStore#869 and other MusicStore and ServerComparison tests. But, these tests should have much left cruft in the way of _finding_ that root cause.

**Comment by dougbu** [comment] 2018-09-24 17:59
Searched a diagnostic build log and found no version conflicts for System.Runtime.CompilerServices.Unsafe, System.Memory or System.IO.Pipelines.

Resolved versions are not quite as expected:
- System.Runtime.CompilerServices.Unsafe: 4.6.0-preview1-26907-04 _and 4.5.0_
- System.Memory: 4.5.0
- System.IO.Pipelines: 4.6.0-preview1-26907-04

In this repo at least, tests fail **only** when multiple assemblies are tested in parallel. Working to narrow it down&hellip;

**Comment by Tratcher** [comment] 2018-09-24 18:02
MSBuild node re-use?

**Comment by dougbu** [comment] 2018-09-24 18:03
@Tratcher could be. I'm seeing if I can reproduce the issue with `dotnet vstest` and multiple test assemblies.

**Comment by dougbu** [comment] 2018-09-24 18:11
Got one:
```
dotnet vstest .\Sample.Tests\bin\Debug\net461\Sample.Tests.dll .\Microsoft.Extensions.Primitives.Tests\bin\Debug\net461\Microsoft.Extensions.Primitives.Tests.dll
```
Tests work fine if the assemblies are reversed on the command line.

**Comment by dougbu** [comment] 2018-09-24 18:53
Looks like the generated binding redirects are incomplete for Microsoft.Extensions.Primitives.Tests.dll. The test assembly references `System.Memory, Version=4.0.1.0` and that references `System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0`. However the `System.runtime.compilerservices.unsafe\4.6.0-preview1-26907-04\lib` versions are all `Version=4.0.5.0`. A binding redirect is necessary.

It's possible `System.Memory` has moved along enough that we need to unpin that package version. But, the lack of a binding redirect is very strange. Has generation or loading of `*.dll.config` files changed lately?

Note: This rash of test failures occur only for .NET 4.6.1 runs.

**Comment by Eilon** [comment] 2018-09-24 19:28
Any help would be appreciated - we have tons of test failures across the board that all seem related to this.

**Comment by Eilon** [comment] 2018-09-24 19:29
We're not sure if it's a packaging issue with the .NET packages, a NuGet issue, or something we did wrong in our product/test code.

**Comment by pranavkm** [comment] 2018-09-24 19:44
Should we roll back the package upgrade until we've figured this out - https://github.com/aspnet/Universe/commit/48e66d3d101de3b34344d735340118061a5e6949#diff-30dcc9789f8ea3c7632e4f054e60c072R22?

**Comment by weshaggard** [comment] 2018-09-24 19:49
>@weshaggard @ericstj - can either of you provide any insights here?

Sorry I don't have any insight here as I would expect the binding redirects to get generated correctly. Perhaps @dsplaisted understands more about how the binding redirects get generated and might be able to shed some light.

**Comment by dsplaisted** [comment] 2018-09-24 20:40
@dougbu Can you provide .binlogs for builds which don't seem to be generating binding redirects correctly?  That would help to investigate the issue.

**Comment by dougbu** [comment] 2018-09-24 21:01
Attached the `.binlog` for a build from root i.e. `.\build.cmd /p:skiptests=true /bl`
[msbuild.zip](https://github.com/aspnet/Home/files/2412845/msbuild.zip)

**Comment by dougbu** [comment] 2018-09-24 21:06
Ignore everything but .NET 4.6.1 and note Microsoft.Extensions.Primitives.Tests.dll.config exists but Sample.Tests.dll.config does not. (Can't find any references to System.Memory or System.Runtime.CompilerServices.Unsafe in Sample.Tests.)

I've attached the former project's `bin` files.
[net461.zip](https://github.com/aspnet/Home/files/2412853/net461.zip)

**Comment by dougbu** [comment] 2018-09-24 21:19
Groan, looks like `dotnet vstest`, xUnit or the platform aren't copying everything that's needed for execution. If I copy the Microsoft.Extensions.Primitives.Tests and Sample.Tests to a single directory, `dotnet vstest .\Sample.Tests.dll .\Microsoft.Extensions.Primitives.Tests.dll` works fine.

Anyone from VSTest team involved in this issue yet?

FYI the net461.zip file I attached above includes only the test assemblies. I left out System.Memory.dll and System.Runtime.CompilerServices.Unsafe.dll and other assemblies from that test folder.

**Comment by Tratcher** [comment] 2018-09-25 00:30
@dougbu branch is release/2.2?

**Comment by dsplaisted** [comment] 2018-09-25 00:32
I have no idea why if you run `dotnet vstest` on these DLLs separately, or in the opposite order, you don't get a failure.

However, I did figure out why the binding redirect for `System.Runtime.CompilerServices.Unsafe` is not getting generated for the `Microsoft.Extensions.Primitives.Tests` project.  The issue is that the compile-time reference to System.Memory is to the `ref/netstandard2.0` reference assembly from that package.  The reference assembly for System.Memory doesn't have any assembly references besides netstandard.dll.  However, the `lib/netstandard2.0` implementation assembly has additional dependencies, including System.Runtime.CompilerServices.Unsafe 4.0.4.0.  However, RAR only operates over the assemblies that are passed to the compiler, so it doesn't see the implementation assembly, and hence the need for the binding redirect.

This is a fundamental problem with how we use the ResolveAssemblyReference task to help generate binding redirects, which I don't think so far has bitten us too hard.  I don't know what the best fix for you is.  @weshaggard or @ericstj may be able to suggest something.  You might just explicitly add this binding redirect (though that seems fragile), or you might be able to change which packages or which versions you reference.

**Comment by dougbu** [comment] 2018-09-25 04:14
> @dougbu branch is release/2.2?

No, `master`, the default branch for the Common repo.

----
@dsplaisted excellent you were able to get to an explanation here! Much appreciated.
> you might be able to change which packages or which versions you reference.

Any suggestions on better choices e.g. should we pin System.Runtime.CompilerServices.Unsafe back at 4.5.0 too? What about System.Buffers, System.Numerics.Vectors and their dependencies?

----
Separately, are customers likely to hit similar issues? I'm wondering whether we'll need a fix to the ResolveAssemblyReference task so that it honours dependencies from the System.Memory package dependencies in this case or some other fix?

**Comment by ericstj** [comment] 2018-09-25 16:03
> Any suggestions on better choices e.g. should we pin System.Runtime.CompilerServices.Unsafe back at 4.5.0 too? What about System.Buffers, System.Numerics.Vectors and their dependencies?

You don't need to "pin back", just reference the same version you're already using directly without ExcludeAssets="Compile".

The packages could change to never use `exclude="compile"` for desktop frameworks where bindingRedirects matter.  We do other things to try to ensure that RAR sees the same assemblies as runtime on desktop.

I've filed issue https://github.com/dotnet/corefx/issues/32457 to track a fix for this.

**Comment by dougbu** [comment] 2018-09-25 17:07
> The packages could change to never use exclude="compile" for desktop frameworks where bindingRedirects matter.

That or another fix for dotnet/corefx#32457 would be awesome!

> reference the same version you're already using directly without ExcludeAssets="Compile".

When we reference the System.Memory package, is there a way to override the `exclude="compile"` qualifications in system.memory.nuspec -- at least as a temporary workaround to get our builds going?

**Comment by dougbu** [comment] 2018-09-25 23:51
Thanks to @natemcmaster for pushing aspnet/Universe#1420 'til this problem disappeared!

Probably best for us to stick with the orphaned System.Memory 4.6.0-preview1-* version until we have a solid dotnet/corefx#32457 fix e.g. a new System.Memory 4.5.2 package without `exclude="compile"` attributes (where they cause problems).

Of course a dotnet/corefx#32457 workaround to let us use System.Memory 4.5.1 without introducing test failures (or worse) would be much appreciated.

**Closed** 2018-09-25 23:54 UTC
Labels: 1 - Ready, Branch:master, blocked, test-failure

**Comment by natemcmaster** [comment] 2018-09-25 23:57
I agree we with @dougbu. We are reverting dependencies to old stuff from early September which includes packages that we know won't RTM, but its the only combination of stuff that appears to work. 

This means we are blocked on consuming new 3.0 builds until https://github.com/dotnet/corefx/issues/32457 is resolved.

**Comment by weshaggard** [comment] 2018-09-26 00:05
Depending on this dead-end 4.6.0-* version of System.Memory package is probably not the best place to be. Instead I think it would be better to downgrade to the last stable version of System.Runtime.CompilerServices.Unsafe that way you are on supported versions and would be on a shipping set of packages that wouldn't block you from shipping something if needed.

**Comment by natemcmaster** [comment] 2018-09-26 00:10
@weshaggard we tried that, but there are several layers to this onion. If we downgrade System.Runtime.CompilerServices.Unsafe, we also have to downgrade System.Memory which means we have to downgrade System.Threading.Tasks.Extensions...etc...the ripple affect was at least 3 or 4 layers deep. We didn't reach the bottom before deciding that we're okay pinning to Sept. 7 bits until corefx packaging/versioning issues are resolved.

**Comment by natemcmaster** [comment] 2018-09-26 00:29
We can use https://github.com/aspnet/Universe/pull/1421 to track this. I was planning to leave the PR open until we figure out a way forward.

**Comment by weshaggard** [comment] 2018-09-26 00:33
OK I expect that https://github.com/dotnet/corefx/issues/32457 will be open for a while and even if we do fix it we would need to do it in a servicing release which will delay getting a fix. So you might need to manually submit any other updates in the mean-time, if you need them.

**Comment by natemcmaster** [comment] 2018-09-26 01:03
We're still focused on 2.2 work, so I'm not terribly concerned if 3.0 is blocked on this for several weeks. Obviously it's not ideal, so if there are other good workarounds, I'm all ears.

**Comment by weshaggard** [comment] 2018-09-26 16:13
The fix that @ericstj had in mind for https://github.com/dotnet/corefx/issues/32457 will not fix this particular issue. There is a gap in how binding redirects are generated automatically. That gap being RAR doesn't consider the implementation assemblies that are getting deployed when finding version conflicts, it only looks at the references passed to the compiler. 

There are only a couple workarounds I can think of:
1) Manually provide the binding redirect.
2) Find some way to force RAR to see the conflict so that it automatically generates the binding redirect.
3) Force your tests to only use a consistent set of references. So downgrade the Unsafe package to the version that the System.Memory package is referencing.

None of these are great but I'm not aware of any better solutions.
