### ISSUE TITLE
No AccountController and ManageController from auth Individual template

### ISSUE THREAD

**Issue by leecow** [aspnet/Home#3270] opened 2018-06-26 19:55 UTC
Submitted by @retifrav in https://github.com/dotnet/core/issues/1731

-----------------

# No AccountController and ManageController from auth Individual template

Template

```
dotnet new mvc --auth Individual
```

no longer provides `AccountController` and `ManageController`.

## Description

With host version 2.0.5 this template generates those controllers and with host version 2.1.0 it does not. See the listings below.

### Host 2.0.5

```
$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Folder structure after `dotnet new mvc --auth Individual`:

```
$ tree
.
├── Controllers
│   ├── AccountController.cs
│   ├── HomeController.cs
│   └── ManageController.cs
...
```

### Host 2.1.0

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]
```

Folder structure after `dotnet new mvc --auth Individual`:

```
$ tree
.
|-- Controllers
|   `-- HomeController.cs
...
```

## Question

Was this change intentional?
If yes, then how does one gets those controllers generated with host version 2.1.0 (or later)?
If no, then I guess it is a bug.

*If I chose the wrong tracker to report this issue, sorry for that and please guide me to the right one.*

**Comment by pranavkm** [comment] 2018-06-26 21:12
This got moved in to a package taking advantage of [Razor UI in class libraries](https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries). https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/ more details on how this works. You may use Scaffolding to re-add the components in to the project. See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio for more details. 

cc @javiercn

**Comment by javiercn** [comment] 2018-06-26 21:22
Thank you for your feedback. We're closing this issue as the behavior discussed is by design.

In our 2.1 release we moved all the UI code into a library and switched to a single implementation using Razor Pages. See the link above and the following link for more details https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x for more details.

**Closed by javiercn** 2018-06-26 21:22 UTC

**Comment by rpokrovskij** [comment] 2018-08-23 15:35
I'm shocked. Why you can't leave old MVC Controllers based Scaffolding?  What is so good in new Scaffolding method?

Why you can't inform developers that Scaffolding will be changed ? All Internet full of articles about AccountController and ManageControllers and now ... all documentation (not large) is gone at one moment.
