### ISSUE TITLE
2.1.0 gives HTTP 404 errors for routes to class library controllers (and only when published)

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#3253] opened 2018-06-21 18:12 UTC
_From @gordon-matt on June 21, 2018 5:14_

I have just recently moved from 2.0 to 2.1 and everything seemed fine in my development environment, but as soon as I deployed the code, I got HTTP 404 errors for my routes to controllers in class libraries. This did not happen in 2.0 and I don't know how to solve it yet.

My solution is rather large, but I have extracted parts of it into a small-ish demo you can find here: https://github.com/gordon-matt/LibraryRoutesNotWorking. Instructions for setup are in the README.md.

_Copied from original issue: dotnet/sdk#2350_

**Comment by gordon-matt** [comment] 2018-06-24 23:45
I hope someone can look at this soon, as it's quite a big issue - why something that worked perfectly fine in 2.0 is now broken in 2.1 and worse yet - it behaves perfectly fine still in Visual Studio / IIS Express.. but when publishing it to full IIS, then we get the 404s. That doesn't make much sense. Last note: I also just updated to 2.1.1 to try and it's the same thing there as well. What can I do?

**Comment by nartalex** [comment] 2018-07-01 18:21
Quite similar issue here with Asp Net Core 2.1.1

I have configured my method to use route param like this:
```
[HttpGet, Route("Services/{id=1}")]
public IActionResult Services(int id)
{}
```
Is there anything I can do to fix it?

When I follow link `mysite/Services` I get everything rigth, but when I try to use param `id` like `mysite/Services/1` I've got all my .css and .js files not found:
```
Failed to load resource: the server responded with a status of 404 (Not Found): site.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found): site.css:1
... 
```

**Comment by Eilon** [comment] 2018-07-11 16:07
@mkArtakMSFT / @kichalla / @rynowak / @JamesNK - any ideas on this?

**Comment by kichalla** [comment] 2018-07-11 17:19
Investigating this now...

**Comment by nartalex** [comment] 2018-07-11 19:53
@Eilon @kichalla 
Looks like I've fooled myself.
I've received this error again now and I've looked at full .js and .css files paths in DevTools.
All of a sudden the path was like `mysite/Services/wwwroot/css/site.css`
This happened because of the `src` attr in the `link` tag in my layout page. I've written `css/site.css`, but should have written `~/css/site.css`.
Sorry for bothering.
But nevertheless it's still a question for me: why my app tried to get files not in root folder, but in folder from route.

**Comment by gordon-matt** [comment] 2018-07-11 23:45
@nartalex I might be wrong, but I don't think your issue is related here... unless your "Services" action is inside a class library and works during development, but not in production. If that's not the case for you, you might want to consider opening a separate issue.

**Comment by kichalla** [comment] 2018-07-12 17:03
@gordon-matt Could you please slim down your repro? I am having difficulty using your repro currently.

**Comment by gordon-matt** [comment] 2018-07-12 23:34
@kichalla Believe it or not, what you are looking at is already very much slimmed down. Could you elaborate on what difficulties you are having? I'm pretty sure all the setup instructions are in the README, but it's possible I have missed a step, Please let me know what the problem is.

**Comment by kichalla** [comment] 2018-07-12 23:59
> If you're trying to find where the admin pages are located, they're in the Framework.Web project, under Areas/Admin

Are these the only controllers that are causing the problem and they exist in a different class library than the main app? Can these just be put in a simple repro app without all other dependent components? basically controllers and actions and minimal code in those actions(return null etc.)?

**Comment by gordon-matt** [comment] 2018-07-13 04:39
Did you even look at the code yet?

"Are these the only controllers that are causing the problem and they exist in a different class library than the main app?"
- The main app is called "MainApp". I did that to make it obvious. The only admin controller in the main app is the admin home page and you can ignore it.

"Can these just be put in a simple repro app without all other dependent components? basically controllers and actions and minimal code in those actions(return null etc.)?"
- If you look at the controllers, you'll see they just return a partial view - there's no real logic in them at all.. everything is handled in JavaScript, because the admin are is an SPA (using Aurelia). You can't get much simpler than just returning a partial view. Please do look closer - I;m sure you will see it's very simple already. See the [TenantController](https://github.com/gordon-matt/LibraryRoutesNotWorking/blob/master/Framework.Web/Areas/Admin/Tenants/Controllers/TenantController.cs) for a simple example... just test that and see what happens... it's fine during development but gives a 404 in IIS. This does not happen in 2.0 - only in 2.1 and 2.1.1.

**Comment by Eilon** [comment] 2018-07-13 18:06
@gordon-matt - thank you for sharing the repro. The more it is slimmed down to the core problem, the easier it will be for us to look at and get a faster response to you. By removing any unnecessary parts of the app, we should be able to investigate very quickly.

**Comment by gordon-matt** [comment] 2018-07-14 02:12
Look guys, I appreciate that you are very busy and all... and I'm not trying to be a pain. On the contrary I am actually trying to make things easy - it took me a few hours already to slim down my repo to what it currently is - removing stuff that is not necessary... and when @kichalla asked me to do something specific (minimal code in the actions), then I answered that it is already done. I mean, look at this one:

```
[Route("")]
public IActionResult Index()
{
	if (!CheckPermission(StandardPermissions.FullAccess))
	{
		return Unauthorized();
	}

	WorkContext.Breadcrumbs.Add(T[FrameworkWebLocalizableStrings.Tenants.Title].Value);

	ViewBag.Title = T[FrameworkWebLocalizableStrings.Tenants.Title].Value;
	ViewBag.SubTitle = T[FrameworkWebLocalizableStrings.Tenants.ManageTenants].Value;

	return PartialView();
}
```

If you want, just comment out everything except the last line there and run it. I mean really guys.. ignore 99% of the code in the rep and just focus on the few controllers in **Framework.Web** - Run the MainApp, go to the admin area, click on Configuration and choose "Tenants"... test that page, okay? I mean if it's absolutely necessary, I can try to slim down further, but it may take me several hours more and really, I don't see the point. You can ignore the other code...

Tell you what, I will try to find time within the next few days to slim it further, but please do at least try to reproduce the problem first - it should be very easy... just look at any page - use the Tenants page for example... look at it in Visual Studio and then try to browse to it when deployed to IIS. You will see it only works in development and not in production. This shouldn't take long to test.

I will message back here once I've had the time to slim it down further as well.

**Comment by gordon-matt** [comment] 2018-07-17 05:47
@kichalla / @Eilon OK guys, I have stripped out a bunch of code. There's only the 1 controller in the library now for you to focus on: "TenantController". I retested it and same results - works in Visual Studio, but not in IIS.

**Comment by kichalla** [comment] 2018-07-17 13:06
@gordon-matt Thanks for making the changes, but I see that the repro still needs a database setup. Can you further slim it down? We need a minimal repro for this. Could you repro it with a File -> New project and just putting in relevant controllers and show us the issue?

![image](https://user-images.githubusercontent.com/6559784/42819065-5118fc94-8987-11e8-9d5c-b307a573775d.png)

**Comment by gordon-matt** [comment] 2018-07-17 13:19
@kichalla As per the README (step 8), you can find the database in the **_Database** directory in the solution root. It's very small.

**Comment by mkArtakMSFT** [comment] 2018-07-17 22:08
Hi @gordon-matt.
While we understand the repro you've provided seems small in comparison to the full project you have, it's not what is expected from our end. The state we expect a repro project to be is a simple ready-to-run project, without much setup requirements. And the instructions for the repro are mainly navigation related (after running click this, then that - and it'll repro).
There is a reason for this. That is, in many cases customer identify the issues they run into on their own, when starting to slim down the project to a minimal repro state. In many cases, the root cause for issues ends up being in their own code. Hence, we ask customers to remove all the unnecessary aspects from repro projects.

**Comment by gordon-matt** [comment] 2018-07-27 07:11
Quick update: I have further slimmed it down, but probably not enough to your liking yet. Please be patient, as I am very busy at the moment, juggling various projects. I will post a message here once done slimming it down as far as I can.

**Comment by smithaitufe** [comment] 2018-07-28 00:14
ASPNET Core project is becoming a pain in the ass. 
One issue after another.
I have been struggling with simple routing for over 18 hours.
I declared a simple controller, simple action and when I navigate to it, I get 404.
I sympathize with you @gordon-matt 

I may have to reimplement my project in another language

**Comment by smithaitufe** [comment] 2018-07-28 19:12
@kichalla There would be no need. Thanks so much. 
I actually migrated from 2.0 to 2.1 and started experiencing that issue. 
I had to create a new 2.1 project and followed the arrangement of the middlewares in the StartUp class.
I noticed that the arrangement is important and it is working now.
Thanks for reaching out. I was frustrated yesterday

**Comment by gordon-matt** [comment] 2018-07-30 03:57
I think that both @nartalex and now @smithaitufe are having 404 issues that are totally unrelated here. FYI to anyone else with 404 issues: this issue is only for cases that meet the following conditions:

1. The route that is failing is in a class library (not the main app)

2. The problem only happens in IIS (but works fine in Visual Studio)

3. The code worked perfectly fine in 2.0, but moving to 2.1 broke it.

If this is not your scenario, please open a different issue. Thanks.

**Comment by Eilon** [comment] 2018-07-30 04:34
@smithaitufe if you have more info about what you discovered regarding the middleware, we would certainly appreciate if you would share that with us. We are looking at some improvements to routing for the 2.2 and future 3.0 releases of ASP.NET Core so maybe there's something we could do to make it easier to diagnose the type of error(s) and problem(s) you were seeing.

**Comment by gordon-matt** [comment] 2018-07-30 05:18
OK guys, I removed caching, localization, settings, helper classes, scheduled tasks, logging, the dynamic navigation system, the theme engine, the multi tenancy system and a whole lot more... And as for the database. it now only has membership tables and 1 table for testing the problem with the library routes. Please tell me this is now a sufficient amount of slimming down...

**Comment by kichalla** [comment] 2018-07-30 18:02
@gordon-matt Thanks for working on this, but is the database here required to repro it? can it be avoided?

**Comment by gordon-matt** [comment] 2018-07-30 23:50
OMG... seriously? The database is tiny and takes a few moments to restore in SQL Server. Yes, it's necessary.. Come on, I've spent countless hours already on this to make changes as you've asked. You're not going to make me spend a few more hours rewriting it so you can avoid a 30 second database restore, are you?

**Comment by kichalla** [comment] 2018-08-04 14:54
As @mkArtakMSFT had mentioned earlier, we want to make sure that the issue you are seeing is not something related to your code itself (as this is what we have seen in many circumstances), so it would be great if you can slim down the application which focuses the problem that you mentioned in the OP i.e hitting a 404 when trying to reach controllers.

**Comment by gordon-matt** [comment] 2018-08-04 23:24
Have you even tried to look at it yet?

1. How would removing the database help? The action in the controller is NEVER hit (when in IIS), so it doesn't even get so far as to execute any db related code for that page... thus, the db related code is NOT an issue to be considered.

2. As I have mentioned before, it works 100% perfectly fine in 2.0.. it's only when I move to the 2.1 NuGet packages that it stops working properly. This is with zero changes to my own code between 2.0 and 2.1 packages...

I guess I have no choice but to try to slim it down further, but honestly I'm getting very frustrated now because it really seems to me like you've not even tried to have a look since this last time I slimmed it down heavily. I've spent a great deal of time on doing that already and now I need to do more which IMHO is completely unnecessary. If you want me to completely remove the databse, I am going to have to rewrite the thing to remove the identity membership system... and for what? To save you a 30 second db restore.. because like I said above: the db is obviously NOT a factor here.. because the action in the controller is never hit in the first place and all it's supposed to be doing anyway is returning a partial view. I mean look at this:

```
public class TenantController : Controller
{
    [Route("")]
    public IActionResult Index()
    {
        return PartialView();
    }
}
```

Do you really think the database is a factor here?

**Comment by gordon-matt** [comment] 2018-08-14 20:50
@kichalla : I found some time and removed the database and all membership code for you. That was completely unnecessary IMHO, but since you were insistent, it is now done and as expected, same results still. I really hope this can be solved soon.

**Comment by kichalla** [comment] 2018-08-14 23:55
@gordon-matt Thanks for the update. I am able to reproduce the issue i.e hitting `/admin/tenants` gives a 404 response. When I take a look at the log file, I see the following:

```
2018-08-14 16:51:17.9661 - INFO: Request starting HTTP/1.1 GET http://localhost:8080/admin/tenants  
2018-08-14 16:51:17.9661 - INFO: Request starting HTTP/1.1 GET http://localhost:8080/admin/tenants  
2018-08-14 16:51:17.9694 - INFO: Route matched with {area = "Admin/Tenants", action = "Index", controller = "Tenant"}. Executing action Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web)
2018-08-14 16:51:17.9694 - INFO: Route matched with {area = "Admin/Tenants", action = "Index", controller = "Tenant"}. Executing action Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web)
2018-08-14 16:51:17.9694 - INFO: Executing action method Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web) - Validation state: Valid
2018-08-14 16:51:17.9694 - INFO: Executing action method Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web) - Validation state: Valid
2018-08-14 16:51:17.9694 - INFO: Executed action method Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web), returned result Microsoft.AspNetCore.Mvc.PartialViewResult in 0.5603ms.
2018-08-14 16:51:17.9694 - INFO: Executed action method Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web), returned result Microsoft.AspNetCore.Mvc.PartialViewResult in 0.5603ms.
2018-08-14 16:51:18.2508 - INFO: Executed action Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web) in 281.3225ms
2018-08-14 16:51:18.2508 - INFO: Executed action Framework.Web.Areas.Admin.Tenants.Controllers.TenantController.Index (Framework.Web) in 281.3225ms
2018-08-14 16:51:18.2752 - ERROR: An unhandled exception has occurred while executing the request.
EXCEPTION: System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.FindView(ActionContext actionContext, PartialViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2018-08-14 16:51:18.2752 - ERROR: An unhandled exception has occurred while executing the request.
EXCEPTION: System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.FindView(ActionContext actionContext, PartialViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2018-08-14 16:51:18.2961 - INFO: Request finished in 329.977ms 404 
2018-08-14 16:51:18.2961 - INFO: Request finished in 329.977ms 404 
```

cc @pranavkm

**Comment by kichalla** [comment] 2018-08-15 00:07
@gordon-matt You can fix your issue by having the following line in `MainApp.csproj` file:

` <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>`

Just FYI...you can read about  `Razor Class Library` and convert your `Framework.Web` project to that.

**Comment by gordon-matt** [comment] 2018-08-15 01:57
@kichalla I appreciate your finally looking at this. Thank you. So why is it that referenced assemblies are copied to the publish directory in 2.0 but not in 2.1? Could someone explain the reasoning for changing this?

**Comment by pranavkm** [comment] 2018-08-15 02:36
>  So why is it that referenced assemblies are copied to the publish directory in 2.0 but not in 2.1? Could someone explain the reasoning for changing this?

There's some documentation about it here: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1#runtime-compilation-of-razor-views. Part of the change in 2.1.0 was to enable build and publish time compilation of views by default. For most users, the experience using this is pretty transparent. Embedded views is one of the few cases that this doesn't really migrate very well. Admittedly we didn't do a good job of calling this out as part of our 2.1 migration notes. I've sent a PR to call this out in the migration notes: https://github.com/aspnet/Docs/pull/8091

**Comment by gordon-matt** [comment] 2018-08-15 04:29
@pranavkm Thanks for the explanation and the documentation link. I will look into migrating to "Razor Class Libraries" in future. For now, setting `CopyRefAssembliesToPublishDirectory` to **true** seems to be working fine. Feel free to close this issue unless there's something you guys would like to add here first.

**Comment by pranavkm** [comment] 2018-08-15 04:42
Thanks for your patience with this issue!

**Closed by pranavkm** 2018-08-15 04:42 UTC
Labels: 2 - Working, cost: S, repo:Routing
