### ISSUE TITLE
Flaky Test: AutobahnTests.AutobahnTestSuite

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2471] opened 2018-01-01 22:36 UTC
_From @mikeharder on Wednesday, April 12, 2017 5:54:45 PM_

Test `AutobahnTests.AutobahnTestSuite` failed during Win2012-Universe #24410:

```
Failed   Microsoft.AspNetCore.WebSockets.ConformanceTest.AutobahnTests.AutobahnTestSuite
Error Message:
 System.OperationCanceledException : Failed to connect, retry canceled.
Stack Trace:
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.<RetryRequest>d__0.MoveNext()
```

_Copied from original issue: aspnet/WebSockets#164_

**Comment by aspnet-hello** [comment] 2018-01-01 22:36
_From @jkotalik on Thursday, September 21, 2017 6:30:46 PM_

I ran into this too. This test seems to be failing more often than not. Stack Trace:
```
System.Exception : Command exited unexpectedly with exit code: 1
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<StartSelfHostAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<DeployAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.Autobahn.AutobahnTester.<DeployTestAndAddToSpec>d__12.MoveNext() in C:\b\w\ccaf4d19a6a87f\test\Microsoft.AspNetCore.WebSockets.ConformanceTest\Autobahn\AutobahnTester.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.AutobahnTests.<AutobahnTestSuite>d__2.MoveNext() in C:\b\w\ccaf4d19a6a87f\test\Microsoft.AspNetCore.WebSockets.ConformanceTest\AutobahnTests.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by aspnet-hello** [comment] 2018-01-01 22:36
_From @jkotalik on Thursday, September 21, 2017 6:35:48 PM_

More details from the autobahn script:

```
Successfully built autobahntestsuite txaio autobahn markupsafe wsaccel ujson Twisted pycparser
Installing collected packages: six, txaio, wsaccel, ujson, constantly, incremental, attrs, Automat, hyperlink, Twisted, autobahn, markupsafe, jinja2, Werkzeug, klein, asn1crypto, enum34, ipaddress, pycparser, cffi, idna, cryptography, pyopenssl, pyasn1, pyasn1-modules, service-identity, linecache2, traceback2, unittest2, autobahntestsuite
  Found existing installation: six 1.5.2
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.5.2:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/six-1.5.2.egg-info'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
The command "pip install autobahntestsuite "six>=1.9.0"" failed and exited with 2 during .
```

**Comment by Eilon** [comment] 2018-04-10 21:28
@muratg / @anurse - what are our plans for this issue? Critical to investigate now? 2.2.0-mq?

**Comment by anurse** [comment] 2018-04-10 22:36
If it needs to be investigated now, someone else will likely need to do it, unless you want me to deprioritize something on SignalR. I don't think there's a product issue here.

**Comment by ryanbrandenburg** [comment] 2018-08-07 21:01
AutobahnTestSuite [failed with about the same error](http://aspnetci/viewLog.html?buildId=525193&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-08 21:01
AutobahnTestSuite [failed with about the same error](http://aspnetci/viewLog.html?buildId=525931&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by anurse** [comment] 2018-08-08 21:16
These failures are occurring because @mikeharder is setting up a new agent.

**Comment by ryanbrandenburg** [comment] 2018-08-17 02:02
AutobahnTestSuite [failed with about the same error](http://aspnetci/viewLog.html?buildId=533540&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by anurse** [comment] 2018-08-17 17:06
I'm going to close this as the previous issues were caused by agents build rebuild. If the issue reoccurs, RaaS can open a new issue.

**Closed by anurse** 2018-08-17 17:06 UTC
Labels: Branch:2.1, repo:WebSockets
