### ISSUE TITLE
Web.config generation in broken after updating to 2.1.400 SDK

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Home#3437] opened 2018-08-17 20:46 UTC
_This issue was moved here from https://github.com/dotnet/core/issues/1861_

__From @glad: https://github.com/dotnet/core/issues/1861#issuecomment-413487044__

I've an issue about transformation of web.config.

Trasformation of:

processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt"

occurs by adding a new row in another <location> zone. See attached files 
[web.config.before.txt](https://github.com/dotnet/core/files/2293188/web.config.before.txt)
[web.config.after.txt](https://github.com/dotnet/core/files/2293189/web.config.after.txt)

Previous SDK (302) worked correctly. I just upgraded to VS 15.8.0

Kind regards

__From @natemcmaster__

@vijayrkn PTAL. 

For reference, the diff is:
```diff
--- web.config.before.txt	2018-08-17 13:41:29.000000000 -0700
+++ web.config.after.txt	2018-08-17 13:41:29.000000000 -0700
@@ -38,7 +38,9 @@
     <system.webServer>
       <handlers>
         <remove name="aspNetCore" />
+        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
       </handlers>
+      <aspNetCore processPath="dotnet" arguments=".\App.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
     </system.webServer>
   </location>
   <location path="wwwroot/css/bundles">
@@ -97,4 +99,5 @@
       </handlers>
     </system.webServer>
   </location>
-</configuration>
\ No newline at end of file
+</configuration>
+<!--ProjectGuid: 76566af5-8a6c-4750-be96-0969bc67b266-->
\ No newline at end of file

```

**Comment by vijayrkn** [comment] 2018-08-17 21:25
Looks like an issue here - https://github.com/aspnet/websdk/blob/master/src/Publish/Microsoft.NET.Sdk.Publish.Tasks/WebConfigTransform.cs#L26

**Comment by glat** [comment] 2018-08-18 06:45
I think so. Anyway I do not understand why to modify the content of a <location> tag.

**Comment by glat** [comment] 2018-08-20 07:26
Resolved moving the handler into first location tag:

`  <location path=".">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" forwardWindowsAuthToken="false" stdoutLogEnabled="false" startupTimeLimit="3600" requestTimeout="23:00:00" />
    </system.webServer>
  </location>
`

**Comment by vijayrkn** [comment] 2018-08-20 15:59
yes, this is a change in the latest sdk. We will fix this issue in an upcoming update. WebSdk needs to handle scenarios where the first location tag might not have the aspNetCore element.

**Comment by vijayrkn** [comment] 2018-08-20 20:23
This https://github.com/aspnet/websdk/pull/395 should fix the issue.

**Comment by vijayrkn** [comment] 2018-08-24 22:28
This issue is fixed pending release.

**Comment by ggirard07** [comment] 2018-08-27 11:44
@vijayrkn do you plan to release a hotfix for this or is it going to be delayed until `2.2.0`?

**Comment by vijayrkn** [comment] 2018-08-27 16:10
@ggirard07 - This will be fixed in the sdk targeting 2.1.

**Comment by Eilon** [comment] 2018-08-28 18:44
@vijayrkn - can we close this issue if it's already fixed, pending release?

**Comment by vijayrkn** [comment] 2018-08-28 18:48
@Eilon - Yes, we can close this issue.

**Closed** 2018-08-28 22:26 UTC
Labels: bug

**Comment by memark** [comment] 2018-11-14 10:54
@vijayrkn I'm still experiencing this problem in 2.1.500 (it works correctly in 2.1.302).
Granted I am not _replacing_ anything, just doing `dotnet publish` on a project with a regular Web.config, but the <handlers> and <aspNetCore> elements still end up in the wrong place (i.e. inside <location>). Do you want me to produce a minimal test case for this? Should I open a new bug?

**Comment by vijayrkn** [comment] 2018-11-14 14:16
@memark - can you give us a sample project where the issue can be reproduced? I will take a look.

**Comment by memark** [comment] 2018-11-14 14:47
@vijayrkn Here is a repro repo. I have also added a README.md with steps to reproduce.
https://github.com/memark/dotnet-publish-location-repro

**Comment by vijayrkn** [comment] 2018-11-15 03:07
@memark - This is by design. If you have a location tag in the web.config then, it takes priority over the root system.webserver unless the root system.webserver has the aspNetCore tag.

https://github.com/aspnet/websdk/pull/395/files#diff-0ecb9220b3459f4cdbead5de2247946bR36

for e.g if your web.config is like below, then it would update the root system.webServer instead of the location tag.

```
<configuration>
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" stdoutLogEnabled="false" />
    </system.webServer>
  <location path="test"></location>
</configuration>
```

**Comment by memark** [comment] 2018-11-15 08:52
@vijayrkn The tooling behaves as you stated. But this makes no sense to me. What is the reasoning behind this? The tooling knows nothing about the purpose of the location tag! In my case I only use it to change the ssl settings for a particular API call. Why would it infer that only that part of the structure should have the <aspNetCore> element, and hence run my AspNetCore application, leaving the rest of the application out in the wild?

More importantly, running the repro application on IIS (IIS 8, WS 2012 R2 Data Center) doesn't really work.
A request to / gives 403 (Forbidden, which is kinda expected)
A request to /test gives 502.5 (Process failure)

All in all, no parts of my application are reachable with this web.config transformation logic.

**Comment by memark** [comment] 2018-11-15 09:06
Additional info:

It seems to arbitrarily pick the **first** location tag it finds. I.e.

```
<configuration>
  <system.webServer></system.webServer>
  <location path="test1/test2">
  </location>
  <location path="test1">
  </location>
</configuration>
```

gives

```
<configuration>
  <system.webServer></system.webServer>
  <location path="test1/test2">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Repro.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
  <location path="test1">
  </location>
</configuration>
```

Which, IMHO, makes even less sense.
