### ISSUE TITLE
Unable to add duplicate usernames/roles with different company IDs (Multi-tenant users/roles)

### ISSUE THREAD

**Issue by whizkidwwe1217** [aspnet/Home#2298] opened 2017-12-06 00:25 UTC
**Use case**: I'm using a multi-tenancy for my asp.net core app however, different tenants/companies are stored on the same schema and the same database. Since each tenant/company is different from each other and have no access to each other, the app should allow registering users that are unique within a company. In otherwords, it should allow saving users to the database with the same username but have different tenant/company id.
**Issue**: ASP.NET Core 2 is creating a UniqueUsername index that does not allow me to add a user with the same username. Is there another way to override this index in Code-First approach? Something like transforming this UniqueUsername index to UniqueUsername+company id, wherein the user is unique per username per company. The issue also applies to Roles.

To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:

Common ASP.NET and Entity Framework repos and projects:

 - Documentation: https://github.com/aspnet/Docs
 - MVC: https://github.com/aspnet/Mvc
 - Entity Framework Core: https://github.com/aspnet/EntityFramework
 - Entity Framework 6: https://github.com/aspnet/EntityFramework6
 - SignalR: https://github.com/aspnet/SignalR
 - ASP.NET Core in Docker: https://github.com/aspnet/aspnet-docker
 - Microsoft.NET.Sdk.Web: https://github.com/aspnet/websdk
 - Kestrel HTTP Server: https://github.com/aspnet/KestrelHttpServer
 - ASP.NET Katana: https://github.com/aspnet/AspNetKatana
 - and more! See a full list here: https://github.com/aspnet

Other common projects:

 - NuGet: https://github.com/NuGet/home
 - .NET Core CLI, SDK, or runtime: https://github.com/dotnet/core
 - Visual Studio: https://developercommunity.visualstudio.com
 - Visual Studio Code: https://github.com/microsoft/vscode
 - Omnisharp (C# support for VS Code): https://github.com/omnisharp/omnisharp-vscode

**Comment by Tratcher** [comment] 2017-12-06 03:10
@HaoK

**Comment by HaoK** [comment] 2017-12-12 18:14
Dupe of https://github.com/aspnet/Identity/issues/1518

**Closed by HaoK** 2017-12-12 18:14 UTC
