### ISSUE TITLE
.Net Core 2.1 Identity don't load Roles

### ISSUE THREAD

**Issue by minhtaimc** [aspnet/Home#3200] opened 2018-06-05 17:14 UTC
User.IsInRole always false.
[Authorize (Roles = "Admin")] always returns access is denied. 
User.Identities.First().Claims have no roles claims.

**Comment by blowdart** [comment] 2018-06-05 17:47
Dupe of https://github.com/aspnet/Identity/issues/1813

**Closed by blowdart** 2018-06-05 17:47 UTC

**Comment by zoidhddhdd** [comment] 2018-06-05 20:18
Ok+++
