### ISSUE TITLE
Can't reference a PCL project from an ASP.NET core project.

### ISSUE THREAD

**Issue by gugavaro** [aspnet/Home#1356] opened 2016-03-16 05:29 UTC
I have 3 projects:
- My Xamarin mobile app (my UI)
- My PCL (my Models)
- My ASP.NET core (my Web api)

I would like to share my model project between my Xamarin UI and my ASP.NET core, so I can have a single project that holds the Models.
I can reference my PCL project from my Xamarin project without any problem, but when I try to reference the PCL from the asp.net core, the reference window does not give me any warning when I select the PCL project, but the reference does not gets added after a select and click okay.

Any hints on how to solve this issue?

thanks,
Gustavo.

**Comment by davidfowl** [comment] 2016-03-16 05:32
It's currently not supported but will be in RC2.

**Comment by jcapellman** [comment] 2016-04-02 02:10
Similar situation on my end except with just a UWP app and several ASP.NET Core WebAPI services - wanted PCLs between them with RC1.

In case someone was curious in the latest RC1 (1.0.0-rc1-update2) it's still not functional.

**Comment by marce155** [comment] 2016-05-19 15:57
Just wanted to point out that I'm on RC2 and [didn't get it to work yet](http://stackoverflow.com/questions/37274240/how-to-use-pcl-in-asp-net-core-1-0-rc2-project/37287715#37287715).
Hints on how to get those scenarios to work are appreciated.

**Comment by MihaMarkic** [comment] 2016-06-23 19:19
Yep, can confirm, no go with RC2.

**Comment by rdefreitas** [comment] 2016-06-23 19:47
@MihaMarkic I've actually gotten this working myself, in RC2... it was much-required for one of the projects I'm working on.

Are you getting any specific errors when trying to reference it? Can you elaborate on exactly what's happening with it?

**Comment by MihaMarkic** [comment] 2016-06-23 21:08
Create a .net core libarary project A, a PCL (.net 4.5 + asp.net core 1.0) B.
When I try to reference B from A it says:
---------------------------
Microsoft Visual Studio
---------------------------
The following projects are not supported as references : 

  - Arso.Weather has target frameworks that are incompatible with targets in current project A. 

A:

	.NETStandard,Version=v1.5

B:

	.NETPortable,Version=v4.5,Profile=Profile75

Perhaps PCLs can be referenced from only asp.net core projects, but not from .net core console/libraries?

**Comment by marce155** [comment] 2016-06-28 08:30
Just a quick update: it doesn't work for me with 1.0 RTM either. @rdefreitas if you could elaborate how you did it (or answer my SO question directly) I would be grateful.
@MihaMarkic doesn't seem to be a console app issue since I can't get it to work with asp.net either.

**Comment by netStandardCoreFramework** [comment] 2016-06-29 11:51
Does not work with Update3 + 1.0.0 preview2 tooling on 1.0.0
What is the recommended way to use dll's friendly with NetStandard1.0 ASP sites and 4.6.x framework code?  Just want to share the dll.  It seems this has been broken for a release now and does not work as described here: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by prilutskiy** [comment] 2016-08-03 20:13
What's the current status? I'm experiencing the same issue trying to reference PCL from aspnet core application. Is there another way to share code between aspnet core and xamarin application?

**Comment by kewur** [comment] 2016-08-03 20:17
@prilutskiy 

I got around the problem until the issue is fixed by making the referenced project .netcore instead of PCL. But you need to reference the dll itself instead of the project. And you'll have to build the referenced project when you make changes.

**Comment by prilutskiy** [comment] 2016-08-03 20:24
@kewur Thanks for the workaround. But what about Xamarin application? Won't there be troubles with referencing core assembly?

**Comment by kewur** [comment] 2016-08-03 20:32
I was able to run it on the emulator, never tried on the device though.

**Comment by prilutskiy** [comment] 2016-08-03 20:36
@kewur I have just created .NET Core .dll assembly and referenced it from both aspnet and Xamarin.Android applications. I haven't run it, but build succeeded. Maybe that's workaround I've been looking for. Anyway, thanks for your help.

**Comment by cspaniard** [comment] 2016-08-05 13:42
I am sorry to say that I have been trying to get this to work and "no luck". I have projects I need to share between ASP.Net Core 1.0 RTM and Xamarin and it is trouble all the way.

**Problem #1**: I cannot reference the PCL project from the .net core project. I added the compat layer and the "imports" and the reference dialog box works, but the solution does not compile. It seems like the compiler does not "see" the PCL project. It cannot resolve `using` statements or classes that live in the PCL project.

**Problem #2**: If I convert the PCL project to Standard Library, then Xamarin Forms PCL has problems saying that the v4.5 (Xam PCL) is not compatible with the v5.0 (std lib). I am lost...

**Problem #3**: If I try to convert the entire Xamarin project to Standard Library then the problem is that many dependencies are not ported to .Net Core / Std Libs yet. For example, many of the Xamarin libs and even MvvmLight. I talked to both, James Montemagno and Laurent Buignion, and both have confirmed that there is clear a plan to port, but we are not there yet. As Montemagno said, "Standard Libraries are still new".

Anyhow, a real mess... I still wonder if it is a tech. problem, or a tooling problem... I don't know where to log issues or give input... ;)

Thanks...

**Comment by prilutskiy** [comment] 2016-08-05 13:59
That's what I'm having right now.

1. I've logged into OS X and from Xamarin Studio created Portable Library to reference it from Xamarin iOS. Obviously, build succeeded.
2. After that I've logged into Windows, opened the same solution in Visual Studio (2015) and found out that Portable library I've created from Xamarin is not actually a PCL, but a library targeting .NET Standart.
3. Then I've tried to reference this library from ASP.NET Core project. Reference was added, build succeeded BUT: I was unable to see any namespaces/types from the referenced library, Visual Studio underscored all external types and painted them in red. This is mindblowing, I didn't expect such flaw from Microsoft.

But there's more.
I've made a research and it turned out that that's not a problem with Visual Studio... It's all about ReSharper I've been using: the syntax analyzer wasn't smart enough to see referenced types.
The solution is to update ReSharper tool to [2016.2 EAP (Early Access Program) 11](https://confluence.jetbrains.com/display/ReSharper/ReSharper+2016.2+EAP). As JetBrains team says this issue was resolved in EAP 2.

So, to share code base between ASP.NET Core and Xamarin we need both projects reference .NET Standart targeted library. And use ReSharper 2016.2 EAP 2 or higher or not to use ReSharper at all.

Hope somebody will find this useful.

**Comment by cspaniard** [comment] 2016-08-05 14:33
@prilutskiy It seems like we are in rather similar situations. That is good in the terms of consistency.

BTW, is is thread closed ? Is anyone from MS reading this? Should we be posting somewehere elese ?

**Comment by prilutskiy** [comment] 2016-08-05 14:37
@cspaniard I'm not sure. Let's try reaching someone.

@glennc Hi Glenn, what do you think on this point?

**Comment by cspaniard** [comment] 2016-08-05 14:43
@prilutskiy The reason I think It might be closed is this:

![captura](https://cloud.githubusercontent.com/assets/5539214/17440114/782324cc-5b2b-11e6-9994-a686b1bf3294.PNG)

So I wonder if were are "screaming" in the desert... hahahaha

cheers

**Comment by gugavaro** [comment] 2016-08-05 14:57
This thread is still opened.

@davidfowl any update on it ?

thanks,
Gustavo.

**Comment by davidfowl** [comment] 2016-08-05 15:16
It would be helpful if we could all work off the same sample projects. I can reproduce some of the many problems described in this thread. The move back to msbuild should make most of this work more seamlessly than today.

- .NET Core applications can reference .NET Standard class libraries (csproj based and non csproj based)
- .NET Core applications can reference .NET Standard packages and PCL **packages** (with imports). It seems as though PCL projects are broken in the IDE, the compiler works fine.
- You need the latest NuGet and Xamarin tooling to use .NET Standard in your projects. 
- .NET Standard != .NET Core. You can use .NET Standard projects and packages with .NET Framework, Xamarin and .NET Core.

/cc @abpiskunov

**Comment by cspaniard** [comment] 2016-08-05 15:30
@davidfowl I agree with all your points. 

Nuget: 3.5.0.1484  (is this the latest ?, VS says nothing about a newer update available)
Xamarin: 4.1.2.18 (just installed 2 days ago)

My solution still does not compile from within VS. All I am doing is a .Net Core console app with imports trying to reference a PCL.

Any ideas ?  I am missing something ? Can we confirm is a VS/Tooling issue ?

**Comment by davidfowl** [comment] 2016-08-05 15:33
> My solution still does not compile from within VS. All I am doing is a .Net Core console app with imports trying to reference a PCL.

I specifically called this out saying .NET Core applications don't work with PCL **projects** in the IDE. Intellisense isn't working. That's likely a bug because packages work fine.

Convert the PCL to a .NET Standard project.

**Comment by cspaniard** [comment] 2016-08-05 15:41
@davidfowl I know, I was trying to support your point. **I was with you...** I was trying to say you were right.

I cannot convert the PCL to a .NET Standard project because it does not work with Xamarin if converted. Some kind of v4.5 vs v5.0 collision I don't understand very well. I can reproduce it if you want.

I really appreciate all your help with this.

**Comment by davidfowl** [comment] 2016-08-05 16:01
> I cannot convert the PCL to a .NET Standard project because it does not work with Xamarin if converted. Some kind of v4.5 vs v5.0 collision I don't understand very well. I can reproduce it if you want.

Can you clarify this point? What fails? Do you have a **minimal** project you can push to github to show the issue?

**Comment by cspaniard** [comment] 2016-08-05 16:27
@davidfowl I will work on it and I will put it together... I can get it done by tomorrow...

**Comment by cspaniard** [comment] 2016-08-06 12:48
@davidfowl Hi... uploaded the minimal project to github that shows the issue. A Xamarin Forms PCL project trying to reference a Standard Library project.

This is the issue itself:
`The primary reference "C:\zzzzJunk\MyTestApp\TestLib\bin\Debug\TestLib.dll" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".`

Here is the github link:
[https://github.com/cspaniard/MyTestApp](url)

Once gain... thank you for looking into it.

**Comment by gugavaro** [comment] 2016-08-06 16:57
Hey @cspaniard,
 
I was able to reference the Standard Library from the Xamarin PCL, the trick was to unreference all nugget packages, retarget to Standard Library and then re-add the nuget references.
The problem I have is that after I target my Xamarin PCL to Standard Library, my Xamarin projects iOS and Android still work fine, but my Xamarin UWP does not accept the Xamarin PCL reference anymore.

The repro is easy, just target a Xamarin PCL to standard library and try to add the reference on the xamarin uwp project.

Any thoughts on that @davidfowl 

thanks a lot,
Gustavo.

**Comment by davidfowl** [comment] 2016-08-06 17:16
> I was able to reference the Standard Library from the Xamarin PCL, the trick was to unreference all nugget packages, retarget to Standard Library and then re-add the nuget references.

What is a Xamarin PCL? 

> The problem I have is that after I target my Xamarin PCL to Standard Library, my Xamarin projects iOS and Android still work fine, but my Xamarin UWP does not accept the Xamarin PCL reference anymore.

What is a Xamarin UWP project? Is it just a UWP project?

Are all projects using `project.json` or are some using `packages.config`. Are these projects used in both Xamarin Studio and in Visual Studio or just visual studio. AFAIK you can't mix `project.json` and `packages.config`.

/cc @emgarten

**Comment by cspaniard** [comment] 2016-08-06 17:34
Hi @gugavaro,

If I understand your process correctly, you converted your Xamarin PCL project to Standard Library. Is that correct ?

If that is the case, I run into all sorts of trouble since a lot of the libs/pkgs I use are not converted to Std Libs yet. I contacted James Montemagno about this and he mentioned that the commitment is to move to the Std Libs, but since they are kind of new, they are not there yet. Lots of work ;)

**Comment by cspaniard** [comment] 2016-08-06 17:38
Hi @davidfowl,

Xamarin PCL is the PCL version of a Xamarin project. Today Xamarin can be used in 2 modes:
  * Shared Project
  * PCL based Project

I am using the PCL version of Xamarin Forms.

BTW, where you able to clone the project OK ?
TIA ;)

**Comment by MihaMarkic** [comment] 2016-08-06 18:31
Xamarin PCL is a normal PCL. Nothing special, same goes for Xamarin UWP.

**Comment by gugavaro** [comment] 2016-08-06 21:08
Ok, I got it to work across all the platforms, have not tested yet running code, but at least it is compiling.
Would like someone else to double check it before we close the issue.

Here are the Steps:

1 - Created a PCL
2 - Target the PCL project .Net Standard
2.1 - If it is a Xamarin PCL, make sure to remove the nugget references, update the target and then re-add the nugget references.
3 - On the .Net Standard version, select 1.2, this will make your PCL be compatible with Asp.Net Core, Console Core and all Xamarin projects (iOS, Android and Windows UWP and 8.1)
3.1 - If you dont need windows phone 8.1 and windows 8.1, you can bump the target version to 1.4, otherwise 1.2 is the only version compatible cross all platforms.

If you select any higher version of the .Net Standard (i.e.: 1.3 and above) the UWP and Windows projects will not be able to reference the PCL, it seems they are only compatible with .Net Standard up to 1.2 version.

The problem is that I am seeing a lot of nugget packages already targeting higher versions, for example here:
Package Microsoft.IdentityModel.Clients.ActiveDirectory 3.13.1 is not compatible with netstandard1.2 (.NETStandard,Version=v1.2). Package Microsoft.IdentityModel.Clients.ActiveDirectory 3.13.1 supports:
- netstandard1.4 (.NETStandard,Version=v1.4)

There is a table with the compatibility support between platforms and versions:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

This table helped me understand the issues.

Could one of your guys verify it and I will close this issue, @cspaniard @MihaMarkic @prilutskiy @jcapellman ?

thanks a lot everyone here.
Gustavo.

**Comment by cspaniard** [comment] 2016-08-08 15:43
Hi @gugavaro,

I have not being able to replicate your example. However, it might be my fault. From my perspective, I am trying to find an equilibrium between 2 issues here.

* Calling a PCL from Net Core (Asp or Console, same problem)
* Calling a Standard Library from Xamarin Forms PCL

After a closer reading of your directions, I am not sure which one (if any) you are trying to work around. Both need attention and resolution.

* _PCL from Net Core_: seems to be a tooling problem from within VS. As @davidfowl pointed out, and later confirmed, it works from the CLI.
* _Standard Library from Xamarin PCL_: I still get the horrible message I mentioned in a previous comment. BTW in this context I can only reference the Std Lib if it is targetting v1.1. Anything higher tells me it can't be referenced by the "parent" project. However, with v1.1 I still get the errror.

`The primary reference "C:\Movil\Gustavo\TestLib1\bin\Debug\TestLib1.dll" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile7".`

As you can see I changed to Profile7, but with Profile111, it doesn't work either.

Right now the tooling issue is in MS' hands and I would like to continue working with all of you until we can identify the 2nd  issue.

Can you explain what is your starting point and where you are trying to get ? How were you able to point to StdLib v1.3 and still add the reference from within VS ?

Let´s stay in touch people ;)
Cheers,
David

**Comment by gugavaro** [comment] 2016-08-11 21:44
Hi @cspaniard 

I am able to call a PCL from asp.net core with no problem and even the tooling is working fine for me.

For the second issue, I see you are using Xamarin Forms and if you look on the nugget Xamarin forms info it does not support standard library, however it does support a normal .net PCL, in this case why you need to have a netstandard pcl ?

See if those steps help you:
- Create a PCL => C#, Class Library (Portable for iOS, ...)
After create, I edit the project target and removed both Silverlight, Windows Phone8.1 (you dont need to retarget to to netstandard)
- Create an ASP.NET Core
- Add the PCL reference on your ASP.NET core

let me know if so far it works for you.

If now you are also working with Xamarin Forms.
- Create a new Xamarin Forms Project.
- On The Portable project, remove the Xamarin Forms nugget reference.
- Edit the project Targets to be exact the same as your PCL, in this case remove Silverlight and Windows Phone 8.1
- Add the Xamarin Forms nugget reference back.
- Add the PCL reference to your Xamarin Forms project.

it should work.
let me know.

Thanks,
Gustavo.

**Comment by cspaniard** [comment] 2016-08-12 15:30
Hi @gugavaro 

You are "the man"... Kudos to you... it works just like you said it would... 

Just let me write a few notes about your comments/questions and confirm your points:

> I am able to call a PCL from asp.net core with no problem and even the tooling is working fine for me.

Samething here once I followed your directions... The tooling is still broken and autocompletion is not there. However, it does compile from within VS.

> For the second issue, I see you are using Xamarin Forms and if you look on the nugget Xamarin forms info it does not support standard library, however it does support a normal .net PCL

The latest Xamarin is supposed to be able to reference Standard Libs. Actually James Montemagno wrote a blog about it. I sent him a tweet about migrating to StandardLibs and he mentioned that the idea is to get there, but there are a lot of libs to port.

> why you need to have a netstandard pcl ?

I don't really, as long as I can run my code in all the different environments.

![architecture](https://cloud.githubusercontent.com/assets/5539214/17627325/26947c24-60b1-11e6-95d9-29097a3df952.PNG)

As you can see, I need my libs to run on Asp.Net Core, Desktop WPF, Console and Xamarin. Now, with your directions, I can.

I changed all my PCL projects (including Xamarin) to follow your directions and now they compile and work great.

All I can say is thank you...

Cheers,
David

**Comment by gugavaro** [comment] 2016-08-18 03:51
Hi @cspaniard,

I am glad you got it working.

- Try to update your VS with the latest tools, my vs was also broken, but it got fixed after some updates.

- For your second question. Xamarin does support netStandard, however Xamarin Forms is still not netStandard compatible, so be careful to not make a confusion here. you can reference your netstandard from your iOS or Droid projects with no problem, the issue is to reference the netstandard pcl in the same project that references xamarin forms. 

Let me know if you have any other question and I will be happy to try to help you.

take care,
Gustavo.

**Comment by bpaquin** [comment] 2016-08-25 14:00
So if I understand correctly, it compiles and runs but we are missing IntelliSense?

ben

**Closed** 2016-09-20 03:37 UTC
