### ISSUE TITLE
ASP.NET Core Web API async controller method fails to respond to client, should throw 500 due to serialization issue

### ISSUE THREAD

**Issue by andrewbadera** [aspnet/Home#3141] opened 2018-05-14 15:32 UTC
ASP.NET Core Web API async controller method fails to respond to client, should throw 500 due to serialization issue

ASP.NET Core 2.0
Microsoft.AspNetCore.All 2.0.6

A .NET Core Web API async controller method appears to execute successfully. The application registers a 200 response with Application Insights for the GET request, but no response is returned to client after successfully exiting the method via return Ok(data).

A second, serialization exception - unseen within Visual Studio while debugging - appears in Application Insights, indicating a JSON serialization issue with a data object to which I had recently added a second constructor. This object was being returned as a list from the controller method in question. Addressing this exception by marking the proper constructor returns the application to expected behavior.

This exception does not appear to be caught by implementation within UseExceptionHandler either.

```
          app.UseExceptionHandler(
                  builder =>
                  {
                      builder.Run(
                        async context =>
                        {
                            context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                            context.Response.ContentType = "text/html";

                            var error = context.Features.Get<IExceptionHandlerFeature>();
                            if (error != null)
                            {
                                await context.Response.WriteAsync($"<h1>Error: {error.Error.Message}</h1>").ConfigureAwait(false);
                            }
                        });
                  });
```

> Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type Posteriori.Data.Client. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Projects', line 1, position 48.
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
> at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
> at Microsoft.Azure.Documents.QueryResult.Convert(Type type)
> at Microsoft.Azure.Documents.QueryResult.AsTypeT
> at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
> at Microsoft.Azure.Documents.Client.FeedResponseBinder.Convert[T](FeedResponse1 dynamicFeed) at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) at Microsoft.Azure.Documents.Linq.DocumentQuery1.d__31.MoveNext()
> at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
> at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
> at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
> at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
> at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.AspNetCore.Builder.RouterMiddleware.d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.d__2.MoveNext()

**Comment by Tratcher** [comment] 2018-05-14 16:12
Likely a duplicate of https://github.com/aspnet/Home/issues/2285.

**Comment by khellang** [comment] 2018-05-14 16:14
The stack strace suggests that it's actually trying to deserialize something *while* serializing the JSON response. Is that right? That sounds like a really bad idea.

Do you have a lazy property on your model that does something with `Microsoft.Azure.Documents.Linq.DocumentQuery` or related types?

I think it would be better if you could show a bit more code. What does your controller/action method look like? What does your model look like? Can you push a repro project to GitHub and link it here?

**Comment by andrewbadera** [comment] 2018-05-14 16:46
Can't just push the whole project up right at the moment, unfortunately.

Don't believe there's anything circular in there.

No such declarations, either.

Controller method:
`
[HttpGet]
        public async Task<IActionResult> Get()
        {
            Trace.TraceInformation($"Client.Get()");

            try
            {
                Trace.TraceInformation($"Trying to get all clients.");
                var clients = await _clientRepo.GetAll();
                Trace.TraceInformation($"Got all clients.");
                return Ok(clients);
            }
            catch (ArgumentException ex) // probably irrelevant here
            {
                Trace.TraceError(ex.Message);
                return StatusCode(400, ex.Message);
            }
            catch (ApplicationException aex)
            {
                Trace.TraceError(aex.Message);
                return StatusCode(500, aex.Message);
            }
        }
`

"Client" data object with JsonConstructor commented out for testing:
`
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

using Posteriori.Common;
using Posteriori.Common.DataAnnotations;
using Posteriori.Data.DataAnnotations;

using Newtonsoft.Json;

namespace Posteriori.Data
{    
    public class Client : PosterioriObjectBase
    {
        [Required(ErrorMessage = "Client name is required."), ValidateObject]
        public string Name { get { return _name;  } }
        private string _name = "ClientName";

        public bool Enabled { get { return _enabled; } }
        private bool _enabled = true;        

        public List<ClientProject> Projects = new List<ClientProject>();

        public Client(Guid id, string name) : base(id, "", false)
        {
            _name = name;
        }

        //[JsonConstructor]
        public Client(Guid id, string name, string notes = "", bool isEnabled = true, bool isDeleted = false, ClientProject[] projects = null ) 
            : base(id, notes, isDeleted)
        {
            _name = name;
            Notes = notes;
            _enabled = isEnabled;
            Deleted = isDeleted;
            Projects.AddRange(projects);
        }

        public void EnableClient()
        {
            _enabled = true;
        }

        public void DisableClient()
        {
            _enabled = false;
        }
    }
}
`

"ClientProject" shallow data object, used to prevent circular references between domains:

`
using System;
using System.Collections.Generic;
using System.Text;

namespace Posteriori.Data
{
    public class ClientProject
    {
        public Guid ClientId { get { return _clientId; } }
        private Guid _clientId = Guid.Empty;

        public string ClientName { get { return _clientName; } }
        private string _clientName = "";

        public Guid ProjectId { get { return _projectId; } }
        private Guid _projectId = Guid.Empty;

        public string ProjectName { get { return _projectName;  } }
        private string _projectName = "";
    }
}
`

**Comment by khellang** [comment] 2018-05-14 16:56
Hmm. That returns a lazy enumeration. Try returning `Ok(clients.ToList())` and see if that changes anything.

**Comment by andrewbadera** [comment] 2018-05-14 17:01
Using ToList, I do get the error spit back as an HTML page, which I would expect from the global exception handler.

I also realized I wasn't catching a base Exception in the controller method. If I do so, it does trap the serialization exception.

**Comment by pranavkm** [comment] 2018-06-29 16:16
Past discussion on similar issue about errors during deserialization  - https://github.com/aspnet/Mvc/issues/5083#issuecomment-235631483. 

Closing this since the behavior is by design.

**Closed by pranavkm** 2018-06-29 16:16 UTC
