### ISSUE TITLE
Key material should be able to be stored in a database

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2528] opened 2018-01-01 23:42 UTC
_From @GrabYourPitchforks on Tuesday, October 28, 2014 6:27:46 PM_

This would be implemented as an additional IXmlRepository.

_Copied from original issue: aspnet/DataProtection#37_

**Comment by aspnet-hello** [comment] 2018-01-01 23:43
_From @GrabYourPitchforks on Saturday, February 28, 2015 12:40:41 AM_

Very difficult to make this generic - might be better as a sample? Can we do what Identity does for generic DB access?

**Comment by aspnet-hello** [comment] 2018-01-01 23:43
_From @muratg on Thursday, July 23, 2015 11:37:09 AM_

Maybe better to have this as a sample.

**Comment by natemcmaster** [comment] 2018-08-18 16:52
Closing as a duplicate of https://github.com/aspnet/Home/issues/2505. We have a PR in the works to add this. See https://github.com/aspnet/DataProtection/pull/303

**Closed by natemcmaster** 2018-08-18 16:52 UTC
Labels: repo:DataProtection
