### ISSUE TITLE
Microsoft.AspNetCore.MiddlewareAnalysis not available from nuget

### ISSUE THREAD

**Issue by michaelsogos** [aspnet/Home#2124] opened 2017-08-12 10:41 UTC
Dear,

Few days ago all packages around Microsoft.AspNetCore.* has been updated from 2.0.0-preview2 to 2.0.0 stable release.

But when we try to update the package Microsoft.AspNetCore.All to latest stable version it fails because the package Microsoft.AspNetCore.MiddlewareAnalysis 2.0.0 is not available on nuget repository.

Investigating a bit more on NuGet website there is a warning message saying "This package has not been indexed yet".

Unfortunately some other our libraries has been updated to Microsoft.AspNetCore.* 2.0.0 successfully because uses few some other Microsoft.AspNetCore.* that do not have a dependency with Microsoft.AspNetCore.MiddlewareAnalysis, so is too late to revert back everything.

Do you have plan to resolve this issue?

**Comment by joeaudette** [comment] 2017-08-12 12:18
+1 on this issue, looks like this package was uploaded yesterday but some glitch prevents it being indexed meanwhile the other 2.0 packages are ready, but this one broken dependency is breaking the whole stack

**Comment by joeaudette** [comment] 2017-08-12 17:08
the package has been indexed now, hope the new sdk is released soon

**Comment by natemcmaster** [comment] 2017-08-14 16:13
A member of the NuGet team manually resolved this for us. Closing as a duplicate of https://github.com/NuGet/NuGetGallery/issues/3991.

**Closed by natemcmaster** 2017-08-14 16:13 UTC
