### ISSUE TITLE
Microsoft.Extensions.Primitives 2.0.0 NuGet package is missing

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Home#2130] opened 2017-08-15 20:44 UTC
_From @conniey on August 11, 2017 18:52_

**Repro steps:**
* Create a .NET Core 2.0 project
* Right-click -> Manage NuGet packages
* Search for "Microsoft.Extensions.Configuration.Json"
* Click "Install" on latest stable version, 2.0.0.

**Expected:** It installs
**Actual:**
Error		Unable to find metadata of Microsoft.Extensions.Primitives.2.0.0

_Copied from original issue: aspnet/Configuration#710_

**Comment by pranavkm** [comment] 2017-08-15 20:48
Likely a dup of https://github.com/aspnet/Home/issues/2124 \ https://github.com/NuGet/NuGetGallery/issues/3991. The 2.0.0 package exists in the feed: https://www.nuget.org/packages/Microsoft.Extensions.Primitives/2.0.0

**Comment by natemcmaster** [comment] 2017-08-18 08:25
Closing as a duplicate of NuGet/NuGetGallery#3991.

**Closed by natemcmaster** 2017-08-18 08:25 UTC
