### ISSUE TITLE
it is succeed to execute dotnet .dll command,but put they on iis or jexus,get Exception:Views/XXX/xxx.cshtml" was not found

### ISSUE THREAD

**Issue by liuyl1992** [aspnet/Home#2294] opened 2017-11-30 07:34 UTC
I execute the dotnet .dll command in the publish file, everything works, but put the publish file on iis or linux jexus, the site is up and running, but some pages get an exception: "Views/XXX/xxx.cshtml" was not found

i'm sure the program is not path

**Comment by MichaelVincentHubbard** [comment] 2017-11-30 10:06
Hey thanks fir the note what do you normally with this site or code what str you expecting?  Thanks sounds interesting.  
By the site what do you mean pornhub or something?  

Sent from my Samsung Galaxy , an AT&T LTE smartphone
-------- Original message --------From: Chaunce <notifications@github.com> Date: 11/29/17  11:34 PM  (GMT-08:00) To: aspnet/Home <Home@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [aspnet/Home] it is succeed to execute dotnet .dll command,but put
  they on iis or jexus,get Exception:Views/XXX/xxx.cshtml" was not found (#2294) 
I execute the dotnet .dll command in the publish file, everything works, but put the publish file on iis or linux jexus, the site is up and running, but some pages get an exception: "Views/XXX/xxx.cshtml" was not found

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aspnet/Home","title":"aspnet/Home","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aspnet/Home"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"it is succeed to execute dotnet .dll command,but put they on iis or jexus,get Exception:Views/XXX/xxx.cshtml\" was not found (#2294)"}],"action":{"name":"View Issue","url":"https://github.com/aspnet/Home/issues/2294"}}}

**Comment by pranavkm** [comment] 2017-12-01 16:58
@liuyl1992 could you share more details? What version of Asp.Net Core \ Mvc and .NET SDK are you targeting? Do you see only see this errors with a published application and not when you do `dotnet run`?

**Comment by liuyl1992** [comment] 2017-12-02 01:33
.NET SDK:2.0.1
ASP.NET Core :2.0.0

detail:https://github.com/blogifierdotnet/Blogifier/issues/67

**Comment by Eilon** [comment] 2018-01-10 19:10
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2018-01-10 19:10 UTC
