### ISSUE TITLE
ProtectKeysWithCertificate only searches the "My" StoreName

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2524] opened 2018-01-01 23:09 UTC
_From @DavidChenware on Thursday, March 3, 2016 7:37:21 AM_

We push various certificates to workstations and server groups via GPO, and sometimes these end up in the Trusted Root Certification Authorities store.

ProtectKeysWithCertificate(thumbprint) seems to only search StoreName.My by default, e.g. the Personal store for both the Current User and the Local Computer accounts.

This means that we cannot use certificates in anything but the Personal stores to encrypt keys at rest.

**A)** Can this be a feature added? The ability to either automatically search all stores, or the ability to search specific StoreNames. e.g. StoreName.Root.

`configure.ProtectKeysWithCertificate("thumbprint", StoreName.Root);`

**B)** Or...is it the intention that if I need to search for a certificate by thumbprint in a different StoreName, that I just duplicate the code already in the CertificateResolver and search my own stores with the X509Store.

```
var store = new X509Store(StoreName.Root, StoreLocation.LocalMachine);
try
{
    store.Open(OpenFlags.ReadOnly);
    var matching = store.Certificates.Find(
        X509FindType.FindByThumbprint,
        "thumbprint",
        validOnly: true);
}
finally
{
    store.Close();
}
```

Thanks.

_Copied from original issue: aspnet/DataProtection#125_

**Comment by aspnet-hello** [comment] 2018-01-01 23:09
_From @muratg on Thursday, March 3, 2016 9:11:56 AM_

@blowdart thoughts?

**Comment by aspnet-hello** [comment] 2018-01-01 23:09
_From @blowdart on Thursday, March 3, 2016 9:12:47 AM_

By design. You can of courser provide your own X509Certificate2 when configuring.

**Comment by aspnet-hello** [comment] 2018-01-01 23:09
_From @soeron on Wednesday, March 23, 2016 7:33:55 AM_

Providing certificate doesn't solves anything.
Using `ProtectKeysWithCertificate( X509Certificate2 )` still searches the stores and if the certificate is not there raises `Cryptography_Xml_MissingDecryptionKey` (System.Security.Cryptography.Xml.EncryptedXml).
If the certificate is in the store then the exception becomes `Bad key\r\n` which is guess is because of the certificate purposes.

**Comment by aspnet-hello** [comment] 2018-01-01 23:09
_From @pksorensen on Monday, March 13, 2017 1:56:34 PM_

I also ran into:
```
System.InvalidOperationException: A certificate with the thumbprint 'C03BB5A6410741CDD2927B4FF88C3E67215A393B' could not be found.
```

and looking at the code here - i get the impression that it should be implemented such it first look in User Store, then Machine. Therefore I am confused that it fails with above when below works- where I find the certificate myself.

```
services.AddDataProtection()                     .ProtectKeysWithCertificate(X509.LocalMachine.My.Thumbprint.Find("C03BB5A6410741CDD2927B4FF88C3E67215A393B", validOnly: false).FirstOrDefault())
```

Anyway, the latter solution is fine for me - just expected the overload to work also

**Comment by aspnet-hello** [comment] 2018-01-01 23:09
_From @natemcmaster on Monday, May 8, 2017 12:44:03 PM_

Remarking for triage: .NET Core 2.0 adds support for EncryptedXml, however, at the moment, the X509Store on Linux will only support the 'LocalMachine\Root' and 'LocalMachine\CertificateAuthority' stores.

See this issue: https://github.com/dotnet/corefx/issues/3690 - currently marked as <kbd>up-for-grabs</kbd>

**Comment by aspnet-hello** [comment] 2018-01-01 23:09
_From @natemcmaster on Monday, May 8, 2017 3:26:22 PM_

To clarify my last comment, `CurrentUser\My` is supported on Linux in .NET Core 2.0. It's `LocalMachine\My` that isn't which means there's no good machine-wide place to add store certs.

**Comment by blowdart** [comment] 2018-01-01 23:13
Closed as by design.

**Closed by blowdart** 2018-01-01 23:13 UTC
Labels: repo:DataProtection
